### ISSUE TITLE
 Spider 类 onError时没有将异常信息带过去，导致监听无法收到异常信息。希望优化下，谢谢

### ISSUE THREAD

**Issue by chouway** [code4craft/webmagic#1008]
Spider 类 onError时没有将异常信息带过去，导致监听无法收到异常信息。希望优化下，谢谢

---
 Spider

                  try {
                            processRequest(request);
                            onSuccess(request);
                        } catch (Exception e) {
                            onError(request);
                            logger.error("process request " + request + " error", e);
                        } finally {
                            pageCount.incrementAndGet();
                            signalNewUrl();
                        }

---

**Comment by sutra** [comment]
See #1005
