### ISSUE TITLE
在Maven仓库官方库中的RedisScheduler代码未更新问题

### ISSUE THREAD

**Issue by 404area** [code4craft/webmagic#1032]
Maven仓库中的RedisScheduler类代码未更新，GitHub上代码已更新的RedisScheduler部分代码没有和Maven中代码保持一致，导致redis-client只能用低版本2.x不能使用3.x及以上版本，因为低版本（pool.returnResource(jedis);已弃用 ； 在redis去重时报错, pool.returnResource(jedis); 报IllegalAccessError）建议重新更新上传Maven官方仓库中的jar包 更新一个小版本。 （这个故障经排查最后发现是maven官方库中代码未使用已更新代码，大坑！！！）

**Comment by sutra** [comment]
`mvn dependency:tree` 看下？

**Comment by 404area** [comment]
> `mvn dependency:tree` 看下？

这个maven 官方的jar包已经手动下载下来了，发现使用了弃用的api，GitHub上是更新之后的，没有用弃用api，请看我上传的jar，本人后来已将源码加入到项目中编译！运行之后
![image](https://user-images.githubusercontent.com/50036307/126586694-777bdc53-de5c-4450-8c49-087231fea7bc.png)

出现了这种情况如图所示的情况，后在redis库中发现只有开始爬取的这一条url，程序停止。

**Comment by 404area** [comment]
> > `mvn dependency:tree` 看下？
> 
> 这个maven官方的jar包已经手动下载下来了，发现使用了弃用的api，GitHub上是更新之后的，没有用弃用api，请看我上传的jar，我已经将源码加入到项目中编译！运行之后
> ![图像](https://user-images.githubusercontent.com/50036307/126586694-777bdc53-de5c-4450-8c49-087231fea7bc.png)
> 
> 出现了这种情况就像所示的情况，之后在redis库中发现只有开始爬取的这一条url，程序停止。

备注：所有使用情况是基于最新的 0.7.4这个版本！！！

**Comment by 404area** [comment]
> `mvn dependency:tree` 看下？

![image](https://user-images.githubusercontent.com/50036307/126587179-af6e2aa4-9aa0-4e02-897d-1c82bae9ffb8.png)

**Comment by sutra** [comment]
0.7.4 依赖的本来就是 jedis 2.x。 https://github.com/code4craft/webmagic/blob/WebMagic-0.7.4/webmagic-extension/pom.xml#L16

你看到的已经依赖了 jedis 3.x 的是 develop 分支，还没有上传到 maven central repository.

**Comment by 404area** [comment]
> 0.7.4 依赖的本来就是jedis 2.x。https://github.com/code4craft/webmagic/blob/WebMagic-0.7.4/webmagic-extension/pom.xml#L16
> 
> 你看到的已经依赖了 jedis.x 是开发分支 3，还没有上传到 maven 中央存储库。
> 
> 在 commit [0e01550](https://github.com/code4craft/webmagic/commit/0e01550a79883e7df6c0bd8d0b0ab31156a9412a)（日期：Wed Jan 6 03:13:50 2021 +0800）中更新到 jedis 3.x 的，但是 0.7.4 是[1068e18](https://github.com/code4craft/webmagic/commit/1068e185a0a005403d14e3e498fc2a1017ebbca8)（日期：Thu Jun 3 11:34:10 2021 +0800）

好的，我知道了，谢谢。

**Comment by 404area** [comment]
> > > `mvn dependency:tree` 看下？
> > 
> > 
> > 这个maven官方的jar包已经手动下载下来了，发现使用了弃用的api，GitHub上是更新之后的，没有用弃用api，请看我上传的jar包，我已经将源码加入到项目中了！运行之后
> > ![图像](https://user-images.githubusercontent.com/50036307/126586694-777bdc53-de5c-4450-8c49-087231fea7bc.png)
> > 出现了这种情况就像所示的情况，之后在redis库中发现只有开始爬取的这一条url，程序停止。
> 
> 备注：所有使用情况是基于最新的0.7.4这个版本！！！

那请问 ，这种情况是怎么回事呢？

**Comment by sutra** [comment]
稍后你试试 0.7.5，刚 upload 到 maven central repository，它需要一点时间来同步才能被下载。

**Comment by 404area** [comment]
> 稍后你试试 0.7.5，刚 upload 到 maven central repository，它需要一点时间来同步才能被下载。

使用0.7.5 问题已经解决 多谢大佬！！！
