### ISSUE TITLE
SpiderListener无法监听超时或者http请求一些内部Exception

### ISSUE THREAD

**Issue by 3thinkthendoit** [code4craft/webmagic#1035]
SpiderListener无法监听超时或者http请求一些内部Exception？

**Comment by sutra** [comment]
我看了一下源码 `us.codecraft.webmagic.downloader.HttpClientDownloader.download(Request, Task)`，发生`IOException` 也是有调用 `onError` 的呀。

**Comment by 3thinkthendoit** [comment]
> HttpClientDownloader

还要很多异常unkonwhostException,timeout之类的 就不会回调onError了

**Comment by sutra** [comment]
UnknownHostException 不是 IOException 的子类么？

**Comment by 3thinkthendoit** [comment]
> HttpClientDownloader

**Comment by 3thinkthendoit** [comment]
> HttpClientDownloader
看了源码，调用的是Downloader 的onError，并不是SpiderListener的onerror.差点被你带到沟里

**Comment by konglquan** [comment]
请问怎么解决
