### ISSUE TITLE
ThreadSafe相关

### ISSUE THREAD

**Issue by kangyu06** [code4craft/webmagic#1068]
项目里用的0.7.3版本，然后看源码@ThreadSafe找不到，并发的时候，会有什么影响吗。。。。
![image](https://user-images.githubusercontent.com/53601447/167570106-55a179eb-d61e-4f5a-ba80-095e138f0977.png)

**Comment by kangyu06** [comment]
![image](https://user-images.githubusercontent.com/53601447/167572777-ea758ddb-36aa-4402-82ed-cc2cea43e9db.png)
我其实有点没看懂，项目里引用的确实是4.4.13，但是这个包下的@ThreadSafe确实不存在，为什么作者不删除这个注解。。。。。
[INFO] +- us.codecraft:webmagic-core:jar:0.7.3:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile

**Comment by sutra** [comment]
不存在的话，编译还能通过？

**Comment by sutra** [comment]
`webmagic-0.7.3` 所依赖的 `httpcore` 是`4.4.4`哦，不是你说的 `4.4.13`。
```
[INFO] us.codecraft:webmagic-core:jar:0.7.3
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
```

**Comment by kangyu06** [comment]
> `webmagic-0.7.3` 所依赖的 `httpcore` 是`4.4.4`哦，不是你说的 `4.4.13`。
> 
> ```
> [INFO] us.codecraft:webmagic-core:jar:0.7.3
> [INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
> [INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
> ```

仔细看了下，是的，引用的是4.4.4

**Comment by kangyu06** [comment]
`<dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.4</version>
        </dependency>`
被其他项目的jar包给覆盖掉了，自己在pom里重新引用一下就好了，谢谢[sutra](https://github.com/sutra)提醒。
