### ISSUE TITLE
Cannot compile project

### ISSUE THREAD

**Issue by alexandrujecan** [code4craft/webmagic#1077]
i get the following compile errors:

```
[ERROR] /E:/oferte/crawler/webmagic/webmagic-samples/src/main/java/us/codecraft/webmagic/main/QuickStarter.java:[27,20] incompatible types: java.util.LinkedHashMap<java.lang.String,java.lang.Class> cannot be converted to java.util.Map<org.mapdb.Atomic.String,org.jsoup.select.Evaluator.Class>

[ERROR] /E:/oferte/crawler/webmagic/webmagic-samples/src/main/java/us/codecraft/webmagic/main/QuickStarter.java:[28,22] incompatible types: java.lang.String cannot be converted to org.mapdb.Atomic.String
```

**Comment by sutra** [comment]
Have you changed `QuickStarter.java`?

**Comment by alexandrujecan** [comment]
@sutra 
No, I didn't change it.

I want to mention that I am using the develop branch.

If I am using the latest release branch then it is working.

Anyway, QuickStarter.java looks different between the develop branch and the latest release branch.

**Comment by sutra** [comment]
I don't know why your `javac` consider `java.lang.String` as the `org.mapdb.Atomic.String`, and `java.lang.Class` as the `org.jsoup.select.Evaluator.Class`, that is abnormal.

**Comment by alexandrujecan** [comment]
I reinstalled the project again and now it works.
I will close the issue
