### ISSUE TITLE
某些情况下爬虫会莫名其妙卡住不动，但状态是Running

### ISSUE THREAD

**Issue by 653603927** [code4craft/webmagic#1096]
![图片](https://user-images.githubusercontent.com/57738324/203198178-ee9e7318-b266-40df-8f97-4942d52cef27.png)

**Comment by sutra** [comment]
有一個已知問題是，如果使用`us.codecraft.webmagic.scheduler.QueueScheduler`並且開啓了 cycle retry(`us.codecraft.webmagic.Site.setCycleRetryTimes(int)`)，在 Queue 滿（缺省是 Integer#MAX_VALUE）的時候就會形成死鎖。

**Comment by 653603927** [comment]
我确实用了setCycleRetryTimes，但是不确定是否Queue满，大概率没有满，我在看我代码里面的其他错误。此外我知道setCycleRetryTimes是把重试请求放到队列里，但是setRetryTimes的作用不不知道是什么，实际使用的时候好像没有作用，文档里面也没有介绍

**Comment by sutra** [comment]
`setRetryTimes` 是讓 HttpClient 自己去重試（`org.apache.http.impl.client.DefaultHttpRequestRetryHandler.DefaultHttpRequestRetryHandler(int, boolean)`）。
