### ISSUE TITLE
建议在request中添加HttpProxy的关闭功能，将代理的粒度控制到URL级别

### ISSUE THREAD

**Issue by usenrong** [code4craft/webmagic#116]
嘿嘿 又来提issue了，如在site中设置了代理，那该process中的所有url都启用了，有些站点的子域名或者子站点在不同的服务器上，有些并不需要代理，甚至有些加了代理反而无法访问，建议在request中添加HttpProxy的关闭功能，将代理的粒度控制到URL级别。webmagic未来可能真的还是需要扩展request，提供更多的可定制参数。修改代码如下，HttpClientDownloader中
        if (site != null && site.getHttpProxy() != null && request.isUseHttpProxy() ) {
            requestConfigBuilder.setProxy(site.getHttpProxy());
        }
request中再提供个关闭方法即可。

**Comment by code4craft** [comment]
已经被代理池方案代替，后面会完善代理池方案为主，关闭此issue。
