### ISSUE TITLE
请问webmagic是否考虑过从多个site（或者domain）抓取信息？

### ISSUE THREAD

**Issue by stonesun** [code4craft/webmagic#135]
先来说下我对`webmagic`的理解，有不对的地方敬请指出。谢谢。

貌似`webmagic`是_只针对一个域名的垂直爬虫_。因为我看到`Spider`的`create`方法只能对应一个`PageProcessor`。而`PageProcessor`只能有一个`Site`。`Site`里有属性`domain`。有理由相信`webmagic`是只针对_一个域名_的垂直爬虫。

当然，如果我添加多个URL并在PageProcesser.process(Page page)中处理各域名下页面也能实现抓取多个domain。如下：

```
public static void main(String[] args) {
    Spider.create(new SomeProcessor())
        .addUrl("http://www.website_a.com/")
        .addUrl("http://www.website_b.com/")
    ...
}   

public void process(Page page) {
    page.addTargetRequests(page.getHtml().links()
            .regex("(http://[^.]+.website_a.com/.*)").all());
    page.addTargetRequests(page.getHtml().links()
            .regex("(http://[^.]+.website_b.com/.*)").all());
    ...
}
```

但是由于同一个Spider只能有一个`Site`，而`Site`中含有domain、charset、cookies等信息。如果按照以上写法必然导致第二个url中的domain、charset、cookies等信息错误。
Site类：

```
public class Site {
    private String domain;
    private String userAgent;
    private Map<String, String> defaultCookies = new LinkedHashMap<String, String>();
    private Table<String, String, String> cookies = HashBasedTable.create();
    private String charset;
    ...
}
```

另一个方案是创建多个Spider对象：

```
public static void main(String[] args) {
    Spider.create(new SomeProcessor())
        .addUrl("http://www.website_a.com/")
        .addPipeline(new MovieDaoPipeline())
        .thread(10)
        .run();
    Spider.create(new SomeProcessor())
        .addUrl("http://www.website_b.com/");
        .addPipeline(new MovieDaoPipeline())
        .thread(10)
        .run();
    ...
}
```

如果是这样的话，又有另一个问题。就是说线程池不是统一管理的，而是每个Spider自己一个线程池。这将导致线程不能被合理分配和利用。

以上我对`webmagic`的理解，有不对的地方敬请指出。

我的问题是，针对多domain，`webmagic`有实例吗？有没有最佳实践或者demo？谢谢。

**Comment by niuhw** [comment]
对于站点跳转的URL爬取如何处理？
例如，我们要从rss列表（http://rss.com）中获得具体内容的URL（http://www.fileXXX.com），这里的没有一个URL是在一个domain中的，请问这中情况如何处理呢？

**Comment by qinxiaoyao** [comment]
比较关注楼主的问题，有没有好的解决方案~

**Comment by cxc222** [comment]
我也有这样的问题, 在A页面中process, 需要跳到 指定URL(自定义的)

**Comment by jinhaolin** [comment]
也在关注这个问题，准备自己对框架做部分改进。
