### ISSUE TITLE
遇到内容分页的问题有解决方案吗？

### ISSUE THREAD

**Issue by hetian9288** [code4craft/webmagic#143]
抓取新闻站页面，内容页通常会有分页，将分页链接也放入对了，最终如何将采集的分页组合到一起？

**Comment by xlyytcyfei** [comment]
https://github.com/code4craft/webmagic/blob/master/webmagic-extension/src/main/java/us/codecraft/webmagic/pipeline/MultiPagePipeline.java
参考以上
