### ISSUE TITLE
定期抓取文档

### ISSUE THREAD

**Issue by zhugw** [code4craft/webmagic#151]
作者好，
谢谢你们开发的webmagic，让我这个新手也能便利的开发爬虫。
目前业务有定期抓取的需求，但文档中缺失定期抓取的部分，不知是目前的webmagic版本还不支持定期抓取，还是没有来得及准备这部分的文档？若目前版本支持的话，能否提供一些资料、例子？感激不尽！

**Comment by code4craft** [comment]
[https://github.com/webmagic-io/docs/issues/16](https://github.com/webmagic-io/docs/issues/16)
