### ISSUE TITLE
webmagic使用咨询--表格中每行的列数不一致时的抽取方案

### ISSUE THREAD

**Issue by zhugw** [code4craft/webmagic#152]
你好，
现在遇到了这么一种情况，不知有什么好的抽取策略没有。
第一行有9列，剩下的行只有8列，第一行多出的一列跨越了其他行，代码如下所示：
<td rowspan="11" id="g_0">北京</td>  
这样的话就有一个问题，比如对某个欲抽取元素，对于第一行是在第3列，但对其他行来说却是第2列。
那么到底该怎样定义抽取规则呢？
最初想到如下的定义：
@ExtractBy("//table[@id=\"tab_01_ctn\"]/tbody/tr[1]/td[3]/text() | table[@id=\"tab_01_ctn\"]/tbody/tr/td[2]/text()")
即抽取第一行的第三列，其他行的第二列。但好像行不通。不知有没更好的抽取方案？
如
 table[@id=\"tab_01_ctn\"]/tbody/tr[>1]/td[2]/text()

**Comment by code4craft** [comment]
你说的对，这里确实没有短路原则，因为不是逻辑运算。
