### ISSUE TITLE
完善代理池文档

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#155]
目前代理池的策略是：
1. 在添加时连接相应端口做校验
2. 每个代理有1.5S的使用间隔 
3. 每次失败后，下次取出代理的时间改为1.5S*失败次数
4. 如果代理失败次数超过20次，则直接丢弃

这样的策略应该是没有什么太大的问题，但是在代理较少的情况下，容易出现卡死的情况(无代理可用)。可以考虑如何优化一下。

目前想到的：
1. 完善代理相关文档
2. 使用间隔可配置

**Comment by weishaohua** [comment]
我是单独整了一个代理服务，会根据不同网站维护一个单独的代理池，如果匹配不到，就会调用使用默认代理池中代理。并且爬虫这边会对每个代理ip进行反馈。
