### ISSUE TITLE
如何高效的抓取增量更新(结合使用FileCacheQueueScheduler)

### ISSUE THREAD

**Issue by zhugw** [code4craft/webmagic#160]
假设第一遍抓取已经全部抓取完毕,因网站肯定会有更新,如抓取时只有10页,抓取结束后变成了12页,想反过头了再补抓这2页,若使用FileCacheQueueScheduler的话,第二遍来抓取时,必须先将已有的urls.txt文件删除,否则因入口地址已在urls.txt中了,会直接跳过,程序可能刚启动就结束了.
但若删除urls.txt的话,又得重头抓取一遍,即前10页的数据还会重新抓取一遍.
不知有没更好的方案,使得第二遍来抓取的时候能利用已有的urls.txt文件,跳过针对这些url的页面抽取和持久化,仅仅利用这些url来获得新url,同时又不影响正常的url去重机制.

**Comment by gglinux** [comment]
同问。。。建议作者可以加一个API，抓取指定更新时间的url。自己也可以实现吧，判断下页面的最后一次修改时间（Last-Modified）。如果在指定时间内，则爬取。

**Comment by ywooer** [comment]
这个可以在request.putExtra中加一个标记，然后重写一下Scheduler，根据标记判断是否加入到已抓取url列表
