### ISSUE TITLE
Site类中的setHttpProxy()方法被废弃了吗？

### ISSUE THREAD

**Issue by SiQLuxe** [code4craft/webmagic#163]
0.5.2版本Site的setHttpProxy()方法被废弃了吗？
HttpClientDownloader访问网页时，没有使用到我设置的代理
现在只能使用ProxyPool来设置代理

**Comment by code4craft** [comment]
#198 已经有朋友修复了

**Comment by hwanmd** [comment]
请问webmagic怎么使用有用户名和密码验证的代理IP，如下：
//httpClient实现方式，设置用户名和密码
Credentials upcreds = new UsernamePasswordCredentials("name","password");
httpClient.getState().setProxyCredentials(AuthScope.ANY,upcreds);

**Comment by robin-obrien** [comment]
@hwanmd, How do you add the username and password?

**Comment by code4craft** [comment]
已经增加此功能。#290

**Comment by jindx86109** [comment]
List<String[]> poolHosts = new ArrayList<String[]>();
poolHosts.add(new String[]{"101.101.101.101","8888"});

SimpleProxyPool
ublic void addProxy(String[]... httpProxyList) {
        isEnable = true;
        for (String[] s : httpProxyList) {
            try {
                if (allProxy.containsKey(s[2])) {
                    continue;
                }
                HttpHost item = new HttpHost(InetAddress.getByName(s[2]), Integer.valueOf(s[3]));
                if (!validateWhenInit || ProxyUtils.validateProxy(item)) {
                    Proxy p = new Proxy(item, reuseInterval, s[0], s[1]);
                    proxyQueue.add(p);
                    allProxy.put(s[2], p);
                }
            } catch (NumberFormatException e) {
                logger.error("HttpHost init error:", e);
            } catch (UnknownHostException e) {
                logger.error("HttpHost init error:", e);
            }
        }
        logger.info("proxy pool size>>>>" + allProxy.size());
    }  处理中s[] 最大长度就是2  怎么还会取值 s[2] s[3]呢  使用版本0.6.0
