### ISSUE TITLE
log4j.xml会导致用户自己的工程里边的log4j.properties失效

### ISSUE THREAD

**Issue by ghost** [code4craft/webmagic#169]
log4j貌似首先会找log4j.xml，找不到的情况下才会找log4j.properties，因此webmagic里边的log4j.xml就会导致用户自己的工程里边的log4j.properties失效。而使用maven的时候webmagic里边的log4j.xml用户没办法控制哎.这算个问题吗？

**Comment by code4craft** [comment]
0.5.2版本的jar包是没有log4j.xml的。
