### ISSUE TITLE
Xpath 获取问题

### ISSUE THREAD

**Issue by dllen** [code4craft/webmagic#170]
采用 "/html[@class='hb-loaded']/body/div[@class='wrap']/div[@class='main clearfix']/div[@class='blkContainer']/div[@class='blkContainerSblk collectionContainer']/div[@class='blkContainerSblkCon']/table[@class='booklist']/tbody/tr/td[@class='title']/a/@href"  这种获取不到元素

采用 "//body/div[@class='wrap']/div[@class='main clearfix']/div[@class='blkContainer']/div[@class='blkContainerSblk collectionContainer']/div[@class='blkContainerSblkCon']/table[@class='booklist']/tbody/tr/td[@class='title']/a/@href"
就获取到了元素

**Comment by code4craft** [comment]
看起来没有不支持的语法，是否有一些元素写的有误？
/html[@class='hb-loaded']这种用法是不符合html规范的。
