### ISSUE TITLE
JsonFilePipeline类，接收到以"/"分隔的路径时，会报错

### ISSUE THREAD

**Issue by xticfc** [code4craft/webmagic#179]
new JsonFilePipeline("D:/data/webmagic")
这种初始化方式，程序可以帮助创建D:/data/webmagic文件夹，但是代码自动生成的task.getUUID()这一级文件夹不能自动创建，会报java.io.FileNotFoundException: D:\data\webmagic\api.budejie.com\2d041a957ca6b59b0b54b53e08ce92a8.json (系统找不到指定的路径。)。
使用new JsonFilePipeline("D:\\data\\webmagic")一切正常。
所使用版本为0.5.2，运行环境为eclipseJEE,win7。

**Comment by code4craft** [comment]
看描述，似乎是路径的问题，windows下默认就是D:\data\webmagic风格的路径。个人觉得这种兼容没有必要做，留给用户自己设置比较好。
