### ISSUE TITLE
Enhance:Requset最好有个变量存储错误信息

### ISSUE THREAD

**Issue by friddle** [code4craft/webmagic#181]
Request暂时只有存取状态的Code.但是这个对于某些需求不太灵活.
需要Request可以加一个字段来存储错误信息(ErrorMessage).这样在SpiderLinstener里面.可以针对不同的错误做出不同的处理.

这个需求是蛮大的.比如我想判断抓不了是因为网络没连接.还是因为用的HttpProxy连接不上.还是其他的特殊原因.通过这些原因对爬虫进行不同的状态处理.

这个错误信息应该返回给上层逻辑处理.而不简单的只是应该Log输出.

**Comment by code4craft** [comment]
这个错误信息应该返回给上层逻辑处理.而不简单的只是应该Log输出.

同意这个说法。会考虑在Request里附加一些错误信息。

**Comment by code4craft** [comment]
在0.7.0版本有更新，这些信息带到了Page对象而不是Request里。

**Comment by friddle** [comment]
加油。虽然暂时不写爬虫和不用Webmagic了。但确实是Java最好用的爬虫
