### ISSUE TITLE
us.codecraft.webmagic.Page中是否可以返回Response的Header中的信息？

### ISSUE THREAD

**Issue by zhaoxingyun** [code4craft/webmagic#182]
us.codecraft.webmagic.Page中是否可以返回Response的Header中的信息？

**Comment by chuxi** [comment]
实践证明不可以。。。自己extends HttpClientDownloader，添加一个HttpResponse类变量，然后可以override handleResponse，记录下response。。。。。。。其实吧，这个拿来做解析跳转之类的是有必要的。。。（当然，禁止用于非法途径。。。）

**Comment by code4craft** [comment]
@chuxi 自动301/302跳转已经在HttpClient里做掉了。不过Header确实有必要，已经在改造计划中了。
