### ISSUE TITLE
抽取网页内容使用注解

### ISSUE THREAD

**Issue by krisjin** [code4craft/webmagic#183]
抽取网页内容使用注解方式，如果这些抽取规则需要动态的配置（在web界面中修改），这样使用是不是不太灵活了

**Comment by code4craft** [comment]
这种情况建议是不要使用注解形式，可以使用PageProcessor自己实现配置化。已经有很多朋友是这么做的了。

**Comment by krisjin** [comment]
谢谢，我也在按照这种方式去做！
