### ISSUE TITLE
能否使用webmagic进行自动填写一个网站的表单并提交

### ISSUE THREAD

**Issue by mamacmm** [code4craft/webmagic#187]
如题，能否使用webmagic进行自动填写一个网站的表单并提交？

**Comment by code4craft** [comment]
不清楚“自动填写”是什么意思，多数表单提交最终都是一个POST请求，模拟这个POST请求还是比较容易的。

**Comment by mashuai** [comment]
应该是想说像用selenium或者HtmlUnit这样的测试工具，找到表单自动填写吧。

**Comment by mamacmm** [comment]
好长时间没登陆，是mashuai说的这个意思，网站表单里面还有些选项是ajax动态加载的。
用winform的webbrowser倒是可以实现自动填充，还可以实时预览。
