### ISSUE TITLE
请教：如果页面时鼠标滚动后动态加载的，JSON还加密了

### ISSUE THREAD

**Issue by Xiaoshuai** [code4craft/webmagic#190]
如题，鼠标滚动到底部，页面加载（JS控制），然后显示不来。返回的JSON数据也加密了。请问，这种情况下的处理思路是什么。

**Comment by Xiaoshuai** [comment]
这种情况的瀑布流页面如何抓取。

**Comment by Xiaoshuai** [comment]
补充下，Xpath应该更新频率会很低，但是js接口修改比较频繁，而且还带了加解密。

**Comment by Xiaoshuai** [comment]
我来回答，WebMagic集成了Selenium。欢迎补充

**Comment by code4craft** [comment]
可以模拟浏览器，另：一般来说js接口修改频率会远小于页面改版带来的XPath变动。
