### ISSUE TITLE
如何实现抓取js的dwr方式调用的数据。

### ISSUE THREAD

**Issue by wanghaile** [code4craft/webmagic#192]
例如，网易公开课中发出的请求http://c.open.163.com/search/search.htm?query=#/search/course返回课程数据是通过js调用服务器函数方式获得数据。大家有啥好的建议不？

**Comment by yudatou123** [comment]
模拟js请求

**Comment by code4craft** [comment]
dwr也是模拟js请求，只是响应格式比较特殊，我之前是使用正则来提取的。
