### ISSUE TITLE
V0.5.2解析页面出现内存泄露OOM

### ISSUE THREAD

**Issue by nevalosa** [code4craft/webmagic#204]
Html newpage = new Html(“...\u000a.....”);
newpage.parse(...)
在解析页面中含有\u000a等特殊符号是，导致Jsoup解析页面内存泄露，内存瞬间消耗几百兆，而且内存一直不释放。
建议: 更新Jsoup依赖包。

**Comment by code4craft** [comment]
我找了一遍，没有看到Jsoup官方有关于这个bug的issue，能否提供一个？

**Comment by nevalosa** [comment]
当时测试的是优酷的这个页面，在做一些解析工作时，就突然内存暴增。Profile分析是Jsoup问题。不过你可以在网上找到很多关于JSoup的OOM的例子。这是我一个同事分析出来的结果。但是我本地按照他的方式测，没有重现了。估计我实现的逻辑有些不同。
http://www.youku.com/v_olist/c_85_a_%E5%A4%A7%E9%99%86_s__g__r__lg__im__st__mt__d_1_et_0_fv_0_fl__fc__fe__o_7.html

**Comment by code4craft** [comment]
我这边测试没有重现。
```java
@Test
public void test() throws IOException {
	Document document = Jsoup.connect("http://www.youku.com/v_olist/c_85_a_%E5%A4%A7%E9%99%86_s__g__r__lg__im__st__mt__d_1_et_0_fv_0_fl__fc__fe__o_7.html").get();
	System.out.println(document);
}
```

网上的例子能否给一个链接？

**Comment by nevalosa** [comment]
无法重现。
