### ISSUE TITLE
对于不规范标签<a>的支持问题

### ISSUE THREAD

**Issue by ufo5260987423** [code4craft/webmagic#205]
对于http://www.zhihu.com/question/22434291
这个页面中的答案作者名字，使用这个spider去爬的时候发现无法抓取到作者名字。甚至作者名字前面那个<a>里面的href也是空的。

**Comment by code4craft** [comment]
你说的是这个\<a>吗？
\<a data-tip="p$t$ynyounuo" href="/people/ynyounuo">秋夕慕白</a>

**Comment by ufo5260987423** [comment]
是的，就是这个……囧死了……

**Comment by code4craft** [comment]
写了一段代码测试，貌似没发现问题，测试通过了？能否写个例子复现一下？

```java
@Test
public void testAHrefExtract(){
	Html html = new Html("<a data-tip=\"p$t$xxx\" href=\"/xx/xx\">xx</a>");
	assertThat(html.links().all()).contains("/xx/xx");
}
```

**Comment by ufo5260987423** [comment]
可能有帮助的几行代码：
Spider.create(processor).addUrl("http://www.zhihu.com/question/22434291").thread(1).run();

在processor当中：
List<String > authorList=page.getHtml().$("h3.zm-item-answer-author-wrap").all();
for(String tmp:authorList)
				System.out.println(tmp+"\n"+tmp.contains("people"));
非常诡异的是：第一个用户不但用户名现实为匿名用户，连href都……
更诡异的是下面的都是ok的……
