### ISSUE TITLE
建议将PageModelExtractor设置成public的类。

### ISSUE THREAD

**Issue by nevalosa** [code4craft/webmagic#206]
在基于Webmagic进行爬虫框架开发中，发现Model是最经典的模式。但是为了让Processor和Model的统一，需要一个基于WebMagic的一个转换协议。
实际上 PageModelExtractor 就是这种转换协议，只需要开放 public Object process(Page page)接口就安全，也可以说PageModelExtractor是一个协议转换类，建议开放。

**Comment by nevalosa** [comment]
实际上PageModelExtractor也是一个线程安全类，因为每个Class只对应一个PageModelExtractor，所以讲其作为协议转换类很合理。所有符合Webmagic的注解模式的，都可以通过这个协议类进行转换。

**Comment by code4craft** [comment]
不知道想要将`PageModelExtractor`设置成public做什么？
如果要直接调用，可以使用公开对外的API-`PageMapper`是，本质也是直接调用`PageModelExtractor`。

**Comment by nevalosa** [comment]
对的，有PageMapper，这个接口很好。
