### ISSUE TITLE
webmagic的爬取深度应该怎么设置

### ISSUE THREAD

**Issue by tangzk** [code4craft/webmagic#208]
想请问下如何控制webmagic的页面爬取深度呢？

**Comment by vyouman** [comment]
同问。

**Comment by code4craft** [comment]
你可以使用Request.setExtra将每层的深度带过去，下一层=上一层+1，直到达到指定深度。
因为目前更多的场景都是要尽可能抓得多，所以没有设置深度这种功能。

**Comment by 0604hx** [comment]
@code4craft 思路了解的，但是具体怎么实现呢？深度值不懂怎么获取=.=

**Comment by code4craft** [comment]
可以参考文章：http://my.oschina.net/flashsword/blog/155961
