### ISSUE TITLE
请教：如何抓取该论坛版块中特定日期的所有帖子的图片并下载到特定文件夹中

### ISSUE THREAD

**Issue by hebaijun12** [code4craft/webmagic#210]
我想要抓取该论坛版块中特定日期的所有帖子的图片并下载到特定文件夹中，应该如何构造processor类和客户端代码，网址如下：http://bbs.hupu.com/bxj

**Comment by code4craft** [comment]
不好意思才回复，估计题主问题已经解决了吧。关掉了。
