### ISSUE TITLE
[疑问] 目标网页返回404， 是否还会重试？

### ISSUE THREAD

**Issue by RangerWolf** [code4craft/webmagic#211]
已经在代码之中设置了setRetryTimes(3)

目前没想到很好的测试方法~ 所以上来问一下~
谢谢

**Comment by perfecking** [comment]
奇怪的想法，404是找不到目标URL，你不改变URL，重试100次不也是没用吗。。除非服务器的URL映射逻辑改变了，但是那是不可控制的。

**Comment by code4craft** [comment]
404是不会的，400开头的都是客户端错误，如 @perfecking 所说，重试多少次也没有用。
