### ISSUE TITLE
RedisScheduler 持久化队列

### ISSUE THREAD

**Issue by CainGao** [code4craft/webmagic#219]
RedisScheduler 持久化队列会把抓取过的URL加入到Redis中. 例如; https://github.com/code4craft 抓取作者的项目.. 或者是其他...只要是抓取过之后以后就不能再抓取了.因为 https://github.com/code4craft 链接已经存在. 所以任务虽然是持久化了,但是以后也还是无法抓取.

好吧,表达有问题.大概意思就是抓取到的链接去重方式不太合理.把抓取的所有链接存储之后,有一些链接会存在更新情况.需要抓取更新..  入口链接也持久化了,就不存在再次抓取的情况了.

**Comment by RangerWolf** [comment]
我的处理方式是给url 设置一个过期的时间。 比如每天最后一秒过期  
这样第二天还是可以再去抓一次，而且每天只会抓一次

使用redis的expireAt功能  
注意要更新redis的jar包以及使用新版的redis才行

之前的jar包虽然提供这个api但是好像不起作用

**Comment by CainGao** [comment]
呃,咱们两个的业务场景不一样...虽然说我做出来的效果也是这样..  类似   百度新闻入口...  http;//news.baidu.com  这个插入Redis之后就不会再抓取了...  但是这个是入口,需要适时进入更新的...  也许具体新闻内容可以使用失效. 但是入口我需要随时可以进入.

**Comment by yuchaozhou** [comment]
自己做个种子列表，定时将种子列表的URL先从去重集合中remove掉，然后再将种子URL推入到待抓取队列就可以。这样可以解决种子页面更新或发现URL问题。已抓取的URL怎么去处理更新呢？道理是一样的，对不对？
