### ISSUE TITLE
我看了一下代码。没法对目标URL排重吧。。用的好像是Aarraylist保存的数据。也没有排重方式呀

### ISSUE THREAD

**Issue by wanghaile** [code4craft/webmagic#221]

**Comment by blueswhisper** [comment]
你确定你看完源代码了？ [URL去重代码](https://github.com/code4craft/webmagic/tree/master/webmagic-core/src/main/java/us/codecraft/webmagic/scheduler/component)

**Comment by JimChen** [comment]
这不是去重吧. 我觉得在对url hash等操作前应该对url normalize下

**Comment by blueswhisper** [comment]
这个不是hash，只是用了hashset。 @code4craft 作者并没有在把URL添加到arraylist的时候去重,而是把去重工作放在了调度模块里，虽然从实现上来说有效率问题（对URL集合使用不同的集合框架多次承载），但是从设计上来说功能分离更加优雅，避免一个模块实现多个功能。 再说，URL去重未必是刚需，也有些人就想统计一下同样URL出现在不同页面的次数呢 :smirk:

**Comment by thuang136** [comment]
hashset 里的元素不是保证唯一吗，不就相当于去重了？

**Comment by wanghaile** [comment]
看到了。。是可以保证去重。但是有个缺点就是POST请求无法添加到里面因为很多post请求url可能是一致的。我这样改了一下。//whl 添加 适配POST请求
    	boolean finalflag = false;
    	if(request.getMethod()!=null &&request.getMethod().equals("POST")){
    		urls.add(getUrl(request));
    		return false;
    	}else{
    		finalflag = !urls.add(getUrl(request));
    	}
        return finalflag;
