### ISSUE TITLE
保存路径在哪里？

### ISSUE THREAD

**Issue by chy996633** [code4craft/webmagic#226]
public static void main(String[] args) {
    Spider.create(new GithubRepoPageProcessor())
            //从"https://github.com/code4craft"开始抓
            .addUrl("https://github.com/code4craft")
            .addPipeline(new JsonFilePipeline("D:\\webmagic\\"))
            //开启5个线程抓取
            .thread(5)
            //启动爬虫
            .run();
}

但是在D盘下没有找到爬下来的日志

**Comment by chy996633** [comment]
用的是gitbook上的标准用例

**Comment by hsqlu** [comment]
GithubRepoPageProcessor 里面的xpath有误  

改为
```java

githubRepo.setName(page.getHtml().xpath("//h1[contains(@class, 'entry-title') and contains(@class, 'public')]/strong/a/text()").toString());

```

**Comment by xiaohn2013** [comment]
是的，我也发现了，这个无法保存数据。不知道怎么回事

**Comment by xiaohn2013** [comment]
不好意思，发现是怎么回事了，原来是github的规则变掉了，所以导致取不到数据！
