### ISSUE TITLE
自带的json库不够稳定

### ISSUE THREAD

**Issue by luohaha** [code4craft/webmagic#232]
在有些情况下（不是所有），将string类型转换为json类型的时候，会出现错误，导致转换无法完成，也没有打印相关的错误信息。如：
Json get = (Json)string;

在使用其他的json库后，问题解决，说明并不是string变量本身的问题。。

**Comment by code4craft** [comment]
没见过哪个Json库可以这么转换的。你说的是哪个库？

**Comment by luohaha** [comment]
不好意思，确实不是这么转换的，当时问题描述得有点问题。好久之前遇到的问题了，等我回头复现一下当时的情况。
