### ISSUE TITLE
建议在文档中补充nameValuePair的描述

### ISSUE THREAD

**Issue by bugss** [code4craft/webmagic#236]
在 post请求的时候  往http的body里面加参数需要在request 的extras 中加上nameValuePair 数组
找了好久才在HttpClientDownloader里面找到这个,建议加到文档中去

``` java
 RequestBuilder requestBuilder = RequestBuilder.post();
            NameValuePair[] nameValuePair = (NameValuePair[]) request.getExtra("nameValuePair");
            if (nameValuePair.length > 0) {
                requestBuilder.addParameters(nameValuePair);
            }
            return requestBuilder;
```

并且建议在us.codecraft.webmagic.Request 对象上面加个header的map   .这样每次请求都可以自定义一些Http header 进去. 现在如果要加header 貌似只能在site上面加  而且全局的.
比如有的后台就会通过X-Requested-With:XMLHttpRequest 这个判断是不是ajax  做分支判断.如果是ajax的情况 就能得到json 数据 好做处理一些.
这个爬虫工具太好用了..

**Comment by FreeFinal** [comment]
楼上的建议不错  , 还要考虑分页的问题

**Comment by xchz** [comment]
确实应该加到文档里去。。刚copy一位兄弟的post例子，nameValuePair写成了nameValuePairs.........看上去好像很正确。。。

**Comment by code4craft** [comment]
已补充。
