### ISSUE TITLE
注解模式下的json不能解析啥时候更新，虽然我自己已经解决了

### ISSUE THREAD

**Issue by lcsan** [code4craft/webmagic#250]

**Comment by Salon-sai** [comment]
请问怎么解决呢？我也遇到这个问题。PageModelExtractor从Page中获取的是getHtml()而不是getJson()所以不知道怎么处理好

**Comment by lcsan** [comment]
第一种方式：参考us.codecraft.webmagic.model.AfterExtractor接口，定义一个BeforeExtractor接口，定义beforeProcess(Page page)方法。
在 us.codecraft.webmagic.model.PageModelExtractor的processSingle(Page page, String html, boolean isRaw)方法开始调用。这里要注意page最好clone。注解模版实现BeforeExtractor的beforeProcess方法，自己实现解析文本为json格式。
第二种方式：扩展ExtractBy注解，增加一个类似于TargetUrl的sourceRegion方法，支持正则提取。在实现模板规则时，在class上注解ExtractBy的sourceRegion实现正则处理json字符串。

**Comment by kenti-lan** [comment]
可以 pull request 啊

**Comment by code4craft** [comment]
新版本修复了，见 #589 。
