### ISSUE TITLE
setHttpProxyPool 和 Proxy的扩展不友好

### ISSUE THREAD

**Issue by fengxiaochuang** [code4craft/webmagic#251]
在Proxy代理这块停留了很久,无论从QQ群还是自己在不该代码的情况下,都无法实现代理功能

Site 的 httpProxyPool 只能传入httpProxyList,但是传入httpProxyList不能用.

所以从开放的接口来讲,需要使用enableHttpProxyPool打开代理,然后读取proxyFilePath的文件,但是因为这个封装在Site里面,直接修改proxyFilePath也是做不到的,继续挖掘代码,找到有saveProxyList,同样无法调用,重写一个saveProxyList,又发现us.codecraft.webmagic.proxy包内的Proxy没有Public,包外访问不了,只好修改了Proxy,给了Public,然后又写了一个saveProxyList才做到代理的功能.

这块太不友好了.希望Proxy 和 ProxyPool 开的接口有好一点.

**Comment by lanxinxichen** [comment]
webmagic 只能使用http代理,使用代理的请注意一下.今天忽然才意识到的,怪不得之前很多使用代理的时候采集不下来.

**Comment by q1335882** [comment]
lanxinxichen 你的解决方案能分享一下么

**Comment by code4craft** [comment]
ProxyPool后面会是一个接口，不知道能否满足你扩展的需要？见PR：#272
