### ISSUE TITLE
some poms' version are wrong

### ISSUE THREAD

**Issue by yimuniao** [code4craft/webmagic#252]
the version in following subproject pom are wrong,  they are referring to 0.53-snapshot

so totally project can not pass the build.

<module>webmagic-scripts/</module>
<module>webmagic-selenium</module>
<module>webmagic-saxon</module>
<module>webmagic-samples</module>
<module>webmagic-avalon</module>

**Comment by code4craft** [comment]
0.6.0重构过了，关闭issue。
