### ISSUE TITLE
log4j:WARN No appenders could be found for logger (us.codecraft.webmagic.scheduler.QueueScheduler).

### ISSUE THREAD

**Issue by Cathon** [code4craft/webmagic#253]
I am a beginner here, starting to use webmagic and have a small question.
When I run the sample code "GithubRepoPageProcessor" there are some warnings.
```
log4j:WARN No appenders could be found for logger (us.codecraft.webmagic.scheduler.QueueScheduler).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
The following output is the data, it runs well.

I searched on google but have no idea. Is the warnning an important thing?

**Comment by milk2007508** [comment]
我也遇到了一样的问题：运行第一个例子的时候告警。

log4j:WARN No appenders could be found for logger (us.codecraft.webmagic.scheduler.QueueScheduler).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by code4craft** [comment]
It is the log4j warning for no log4j.xml or log4j.properties. Just take a look at [https://wiki.apache.org/logging-log4j/Log4jXmlFormat](https://wiki.apache.org/logging-log4j/Log4jXmlFormat)

**Comment by coderbird** [comment]
just see http://blog.sina.com.cn/s/blog_5f7d1a610100ebph.html

**Comment by Richard-Cao** [comment]
加了log4j.properties还是不行……

**Comment by upsideDownBird** [comment]
@Richard-Cao 请确保你的log4j.properties在资源目录里

**Comment by Richard-Cao** [comment]
@upsideDownBird 资源目录是resource那个吗

**Comment by ruanfumin** [comment]
> @Richard-Cao 请确保你的log4j.properties在资源目录里

非常感谢。
