### ISSUE TITLE
求助，为何会出现 Exception in thread "pool-1-thread-1" java.lang.IllegalAccessError:

### ISSUE THREAD

**Issue by iwinder** [code4craft/webmagic#255]
在java1.7且 不使用Maven，导入 [http://webmagic.io/download.html](http://webmagic.io/download.html) 中0.5.2的所有jar包的情况下，运行 [http://webmagic.io/docs/zh/posts/ch2-install/first-project.html](http://webmagic.io/docs/zh/posts/ch2-install/first-project.html) 中的实例，结果报出以上错误，不知是什么原因呢？在网上搜索，就搜到一个提问的，却没找到对应的答案，只好向此处求助下

> 二月 12, 2016 11:50:02 下午 us.codecraft.webmagic.Spider run
> 信息: Spider github.com started!
> 二月 12, 2016 11:50:02 下午 us.codecraft.webmagic.downloader.HttpClientDownloader download
> 信息: downloading page https://github.com/code4craft
> Exception in thread "pool-1-thread-1" java.lang.IllegalAccessError: class com.google.common.collect.StandardTable$RowMap cannot access its superclass com.google.common.collect.Maps$ImprovedAbstractMap
>   at java.lang.ClassLoader.defineClass1(Native Method)
>   at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
>   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>   at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
>   at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>   at com.google.common.collect.StandardTable.createRowMap(StandardTable.java:698)
>   at com.google.common.collect.StandardTable.rowMap(StandardTable.java:694)
>   at com.google.common.collect.HashBasedTable.rowMap(HashBasedTable.java:55)
>   at us.codecraft.webmagic.Site.getAllCookies(Site.java:130)
>   at us.codecraft.webmagic.downloader.HttpClientGenerator.generateCookie(HttpClientGenerator.java:84)
>   at us.codecraft.webmagic.downloader.HttpClientGenerator.generateClient(HttpClientGenerator.java:73)
>   at us.codecraft.webmagic.downloader.HttpClientGenerator.getClient(HttpClientGenerator.java:45)
>   at us.codecraft.webmagic.downloader.HttpClientDownloader.getHttpClient(HttpClientDownloader.java:63)
>   at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:92)
>   at us.codecraft.webmagic.Spider.processRequest(Spider.java:408)
>   at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
>   at us.codecraft.webmagic.selector.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>   at java.lang.Thread.run(Thread.java:745)

**Comment by iwinder** [comment]
原因已找到，问题已解决。。。

**Comment by code4craft** [comment]
多了个环境是什么意思？

**Comment by HuCaresU** [comment]
哥 你倒是说出来 解决办法啊。。。多了个环境是几个意思啊。。。

**Comment by iwinder** [comment]
多了个1.6的java环境，之前忘了这边了。。搜了一下，看到了自己之前在http://www.oschina.net/question/2355295_2151179的回应（幸好回应了），
