### ISSUE TITLE
怎么获取除200以外的响应状态已经其他内容？

### ISSUE THREAD

**Issue by l81893521** [code4craft/webmagic#256]
我看了一下源码，源码只会返回状态为200的请求，200以外的请求都会只记录日志，然后返回空。
部分网站防爬虫，会增加验证码，这个时候返回的状态码不是200。

**Comment by code4craft** [comment]
Site.setAcceptStatCode()，设置成200+你想要的就可以了。
不过你说的情况，如果是反爬的话，多半也不会有内容给你，
