### ISSUE TITLE
作者你好，请问post请求抓取，这种情况怎么处理?

### ISSUE THREAD

**Issue by l81893521** [code4craft/webmagic#258]
1.使用List<NameValuePair>将参数组装好
2.request.putExtra("nameValuePair",param)
3.request.setUrl("http://www.test.com")
4.Spider.create(testCrawler).addRequest(request).thread(1).run();

上面4个步骤，我构造了一个Post请求的爬虫
但是因为post请求，每次请求的地址是一样的，只是post参数page在变化
所以我遇到的问题是，爬虫爬了一页就不动了

我目前的解决方案是在process方法里面
request.setUrl("http://www.test.com?now=" + new Date().getTime());
page.addTargetRequest(request);
重新增加一个待抓取页面，用date.getTime保证每次请求的页面地址有变化
同时改变page的参数

请问作者在这种情况应该怎么处理呢 ？

**Comment by code4craft** [comment]
建议是把key-value pair作为url的一部分。
你这样的方式是可以工作的，但是需要考虑重复抓取的问题。

**Comment by joy2github** [comment]
能否告知一下参数是如何设置的，需要site.addCookie(“”，“”)方法完成内容爬取吗？

**Comment by l81893521** [comment]
如果不需要登录的情况下，site.addCookie通常是用不上的，除非你需要服务器识别你当前的身份才要site.addCookie
