### ISSUE TITLE
作者你好，请问如果我要定期抓取，应该怎么做？我看到文档里面还没写到这一点

### ISSUE THREAD

**Issue by l81893521** [code4craft/webmagic#259]
1.要使用quartz框架吗？还是说webmagic已经有这个功能了？

**Comment by lanxinxichen** [comment]
最简单的办法,写一个bat或者sh,用系统级别的调度.当然如果你想动态调度的话,就用quartz

**Comment by code4craft** [comment]
我最近自己也在使用定期抓取的功能，下个版本会对定期抓取做一些简单的支持。

**Comment by code4craft** [comment]
为WebMagic in Action添加了issue，这个先关闭了。
[https://github.com/webmagic-io/docs/issues/16](https://github.com/webmagic-io/docs/issues/16)
