### ISSUE TITLE
作者你好，如果列表页和详情页的内容不同

### ISSUE THREAD

**Issue by l81893521** [code4craft/webmagic#260]
需要同时捉去列表页和详情页
那么我是不是应该写2个爬虫来抓，通过关系把它们对应起来？

**Comment by code4craft** [comment]
是的。可以参考例子：http://webmagic.io/docs/zh/posts/chx-cases/basic-list-target.html

**Comment by Veeson** [comment]
@l81893521 请问通过什么关系对应列表页和详情页的数据，比如列表页里面有些数据是详情页没有的，也想趴下来跟详情页对应起来，请问如何处理呢？谢谢！
