### ISSUE TITLE
抓取多页用户评论时，后面部分评论页无法抓取，用浏览器单独进行js请求有数据返回

### ISSUE THREAD

**Issue by liujianming2** [code4craft/webmagic#261]
比如：
pageCount=85 js请求：http://piao.ctrip.com/Thingstodo-Booking-ShoppingWebSite/api/TicketDetailApi/action/GetUserComments?productId=1811853&page=85

能抓到；

但是pageCount=86 js请求：http://piao.ctrip.com/Thingstodo-Booking-ShoppingWebSite/api/TicketDetailApi/action/GetUserComments?productId=1811853&page=86

就不能抓取了。

1-85页能抓取，86-95就不行了；其他工具能正常抓取数据。

请问作者，这是什么问题呢；

附：
private Site site = Site.me().setRetryTimes(3).setSleepTime(100);

**Comment by code4craft** [comment]
能否详细一点，你是使用什么方式来抓的？
具体不能抓是没有进队列，还是下载、解析环节失败？你可以debug downloader或者pageProccessor查看一下。

**Comment by liujianming2** [comment]
作者您好！
   经debug，是因为我一个函数将某段字符串转换为json格式get(key)后，因没有value，执行toString()就报异常，然后估计就跳过了那个页面的处理，所以有一些页面抓不到数据，后来修正了之后，正常了。
   因个人代码BUG提交githup，造成麻烦或者困扰，请见谅，再次感谢。
