### ISSUE TITLE
请问，webmagic怎么使用有用户名和密码验证的代理IP

### ISSUE THREAD

**Issue by hwanmd** [code4craft/webmagic#263]
请问，webmagic怎么使用有用户名和密码验证的代理IP，如下（httpClient实现方式）：
//设置代理IP和代理端口
httpClient.getHostConfiguration().setProxy(ip, port);
httpClient.getParams().setAuthenticationPreemptive(true);
//设置用户名和密码
Credentials upcreds = new UsernamePasswordCredentials("name","password");
httpClient.getState().setProxyCredentials(AuthScope.ANY,upcreds);

**Comment by code4craft** [comment]
好建议，我会加过去的。如果你有空，也欢迎提pull request给我。

**Comment by code4craft** [comment]
#290 已经有PR解决了，关闭此issue。

**Comment by wjmzmmd** [comment]
设置代理用户名密码并不起作用，请求返回407代理auth失败。我是用setHttpProxy设置代理，setUsernamePasswordCredentials设置用户名密码。
