### ISSUE TITLE
请问作者XPath函数中有没有filter函数

### ISSUE THREAD

**Issue by liujianming2** [code4craft/webmagic#264]
场景：网页文本里面有特殊字符 “& nbsp;”，导致持久化时转换为JSON字符串失败跳过该行；
目的：在持久化前先将特殊字符“& nbsp;”过滤掉

注："& nbsp; "中&和n之间没空格，不加空格，网页自动变成空格，要过滤的就是&+n+b+s+p+;；

想到了这个笨拙的方法：
page.putField("Introduction", Html.create(page.getHtml().replace("(& nbsp;)", "").toString()).xpath("//*[@id='J-Jdjj']/div[2]/tidyText()").replace("\s", "").toString());

使用replace("(& nbsp;)", "")函数之后，发现不能使用xpath在定位（执行无数据返回），所以只好再构造一个Html对象再定位，以上能初步满足需求。

查看文档只有regex提取符合表达式的内容，请问下作者有没有filter函数过滤不想要的内容？

**Comment by code4craft** [comment]
你是指XPath filter函数么？能不能写一下它的语法？

**Comment by liujianming2** [comment]
正常：page.putField("scenicIntroduction", Html.create(page.getHtml().replace("(& nbsp;)", "").toString()).xpath("//*[@id='J-Jdjj']/div[2]/tidyText()").replace("\\s", "").toString());
报异常：page.putField("scenicIntroduction", page.getHtml().replace("(& nbsp;)", "").xpath("//*[@id='J-Jdjj']/div[2]/tidyText()").replace("\\s", "").toString()); 异常如下：java.lang.UnsupportedOperationException

是不是执行了.replace("(& nbsp;)", "")替换后现在还不支持链式执行xpath？必须重新构造一个Html对象。

XPath filter函数大概跟replace功能一样，就是过滤掉不要的，如果如下代码能执行成功：
page.getHtml().replace("(& nbsp;)", "").xpath("//*[@id='J-Jdjj']/div[2]/tidyText()").replace("\\s", "").toString());
那就不用filter函数了，但debug后，报未支持异常。
