### ISSUE TITLE
目前的sample都是一个类一个爬虫，想多个爬虫协作怎么处理

### ISSUE THREAD

**Issue by tankilo** [code4craft/webmagic#265]
文档的列表详情示例，爬新浪微博的，运行了下，自己改了下，发现总是爬一个列表页，然后把列表里的每项爬到，然后再爬下一个列表页。想一个线程爬列表页，然后爬出的列表给给另一个线程爬详情页。生产者消费者的意思。

**Comment by tankilo** [comment]
知道了，用LinkedBlockingQueue来在两个线程间传递列表url
us.codecraft.webmagic.Spider.addUrl(String...)
us.codecraft.webmagic.Spider.setExitWhenComplete(boolean)

**Comment by Zjimily** [comment]
能不能分享下你的代码呀。多谢
