### ISSUE TITLE
关于说明文档中的正则表达式问题

### ISSUE THREAD

**Issue by lzjohnny** [code4craft/webmagic#267]
若想匹配 "https://github.com/code4craft/webmagic" ，正则表达式应为 `"(https://github\.com/\w+/\w+)"` ，而说明文档中为`"(https://github\\.com/\\w+/\\w+)"`，每处多了一个反斜杠。反斜杠作为转义字符前面不需要再次使用转义字符。

**Comment by code4craft** [comment]
从代码层面来说，Java的反斜杠是需要二次转义的，所以写成了\\w+。
这里贴的是Java代码，所以我觉得没什么问题。

**Comment by lzjohnny** [comment]
感谢作者解答！

**Comment by coderbird** [comment]
github规则 变了吗，为什么那个演示项目 爬取不到内容
