### ISSUE TITLE
pipeline和SpringMVC集成，用hibernate保存到MYSQL时，报错哦

### ISSUE THREAD

**Issue by wander555** [code4craft/webmagic#268]
Spider中的run方法报错， public void run() {
                        try {
                            processRequest(requestFinal);
                            onSuccess(requestFinal);
                        } catch (Exception e) {
                            onError(requestFinal);
                            logger.error("process request " + requestFinal + " error", e);
                        }
报NullPointerException异常，到底是哪个nullpointer啊？没查到啊

**Comment by herrygoon** [comment]
需要错误日志的堆栈信息

**Comment by code4craft** [comment]
没有办法确定问题，我先关闭issue了。
