### ISSUE TITLE
XPath获取指定父标签的所有子标签时，仅能获取到第一个子标签

### ISSUE THREAD

**Issue by lzjohnny** [code4craft/webmagic#271]
```
<div id="header"> 
      <a>登录</a> 
      <a>检索首页</a> 
      <a>我的图书馆</a> 
      <a>参数设置</a> 
      <a>结果列表</a> 
      <a>最近检索</a> 
</div> 
```

我想获取属性为header的div下的所有a标签。

在WebMagic使用`xpath("//div[@id='header']/a")`仅能获取到第一个子标签，即`<a>登录</a>`
在chrome下使用`$x("//div[@id='header']/a")`可以正常获取到所有<a></a>标签

请问这是我的使用方式有问题还是XPath不支持，有什么解决/替代方案么？

刚接触爬虫的新手~请原谅~

**Comment by code4craft** [comment]
用selectable.xpath("//div[@id='header']/a").all()试试？使用get()默认返回一个元素
