### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again Exception in thread "main" java.lang.NoClassDefFoundError: us/codecraft/webmagic/processor/PageProcessor

### ISSUE THREAD

**Issue by darren2900** [code4craft/webmagic#276]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: us/codecraft/webmagic/processor/PageProcessor

man生成jar包运行就报这个错误，直接在idea运行正常，我是JAVA新手，什么原因？

**Comment by code4craft** [comment]
可能是打包的问题，你用什么打包的？
