### ISSUE TITLE
HttpClientDownloader site为null时，没有有效处理

### ISSUE THREAD

**Issue by cheiftain** [code4craft/webmagic#277]
Line 80`if (site != null) {
            acceptStatCode = site.getAcceptStatCode();
            charset = site.getCharset();
            headers = site.getHeaders();
        } else {
            acceptStatCode = Sets.newHashSet(200);
        }` 中site为null时，后面调用getHttpUriRequest会报NullPointerException，是否应当增加记录日志等，异常处理

**Comment by code4craft** [comment]
看到你的PR #493 了，已合并。
其实之前代码对于site可否为空定位并不清晰，虽然公开的所有API都不允许site为空，但是代码实现是有一些site!=null的判断的。
这种情况确实应该视为可为空，先做兼容性升级吧。
