### ISSUE TITLE
通过Spider的addUrl方法添加了12个url，只执行了其中的一部分就停止了

### ISSUE THREAD

**Issue by ning180** [code4craft/webmagic#278]

**Comment by buaanie** [comment]
建议使用调试工具查看问题缘由。

**Comment by PetterW0ng** [comment]
0.5.3 版本存在任务丢失严重

**Comment by code4craft** [comment]
我这边没有发现类似问题，能否详细描述一下？最好给个demo。

**Comment by PetterW0ng** [comment]
你好，我这边是初始 addURL 有1000+，中间使用了代理，发现很快就停止了，只执行了部分。我用的版本是（0.5.3）

顺便问一下，如果我的代理池里面的代理地址用完了，我能在任务执行的过程中，进行批量添加代理么？
我在process 方法里面添加了下面判断，
@Override public void process(Page page) {

   if(needProxy) {
      ProxyPool proxyPool = site.getHttpProxyPool();
      SpiderHelper.refreshHttpProxy(proxyPool);
   }
    ......}
// 下面的方法是refreshHttpProxy的过程，先判断可用的代理数是否大于50，如果否就发请求获取新的代理数据，然后添加到ProxyPool public static void refreshHttpProxy(ProxyPool proxyPool){
   synchronized (proxyPool) {
      int size = proxyPool.getIdleNum();

      if (size < 50) {
         HttpGet httpGet = new HttpGet(GET_PROXY_URL);
         CloseableHttpClient httpClient = HttpClientBuilder.create().build();
         try {

            CloseableHttpResponse closeableHttpResponse = httpClient.execute(httpGet);
            org.apache.http.HttpEntity httpEntity = closeableHttpResponse.getEntity();
            StatusLine statusLine = closeableHttpResponse.getStatusLine();
            if (statusLine.getStatusCode() == 200) {
               String entityStr = EntityUtils.toString(httpEntity, "utf-8");
               String[] hpl = entityStr.split("_");
               if (hpl.length > 1) {
                  for (String httpProxyList : hpl) {
                     String[] httpProxy = httpProxyList.split(":");
                     proxyPool.addProxy(httpProxy);
                  }
                  LOGGER.info("proxyPool -->" + proxyPool.getIdleNum() + ", 新增代理数：" + hpl.length);
               }
            } else {
               LOGGER.error("获取代理列表失败了，快代理服务返回错误");
            }

         } catch (ClientProtocolException e) {
            LOGGER.error("获取代理列表失败了，" + e.getMessage());
         } catch (IOException e) {
            LOGGER.error("获取代理列表失败了，" + e.getMessage());
         } finally {
            try {
               httpClient.close();
            } catch (IOException e) {
               LOGGER.error("获取代理列表失败了，" + e.getMessage());
            }
         }
      }
   }
}不知道上面的做法是否正确，如果不正确我应该怎么及时补充可用的代理，期待您的指点，谢谢！


wangqin_1@163.com
 
发件人： Yihua Huang
发送时间： 2016-05-24 13:13
收件人： code4craft/webmagic
抄送： PetterW0ng; Comment
主题： Re: [code4craft/webmagic] 通过Spider的addUrl方法添加了12个url，只执行了其中的一部分就停止了 (#278)
我这边没有发现类似问题，能否详细描述一下？最好给个demo。
