### ISSUE TITLE
还是有很多依赖包不可用。。。

### ISSUE THREAD

**Issue by zhang-hang** [code4craft/webmagic#283]
能否做到开箱即用呢？lib里的包也添加到路径里了，但还是无法全部顺利编译通过。

**Comment by zhang-hang** [comment]
能麻烦给我一个完整的可编译的源码包吗？ 6296777@qq.com 非常感谢~

**Comment by herrygoon** [comment]
是maven的工程，用maven命令或者导入到Eclipse会自动下载相关的依赖包吧

**Comment by zhang-hang** [comment]
就是用MAVEN很多提示错误

**Comment by zhang-hang** [comment]
![default](https://cloud.githubusercontent.com/assets/3712824/14130201/e7e547cc-f663-11e5-8489-41e6c62a3674.PNG)

**Comment by herrygoon** [comment]
看日志出现错误的都是几个扩展的工程，这些扩展工程只是一些额外的附加的工程，对于webmagic中的core、extension等核心功能没什么影响。可以直接使用子工程webmagic-core中的maven试试
