### ISSUE TITLE
xpath 升级

### ISSUE THREAD

**Issue by mingj** [code4craft/webmagic#284]
作者你好，非常感谢你贡献如此好用的爬虫框架，但是目前在使用xpath的时候还是有些问题，比如
/html/body/div[5]/script[1]/text() 这种好用且简单的匹配 还是不能够使用，所以建议升级下xpath.

**Comment by Salon-sai** [comment]
我也遇到这样的问题 请问你的版本是0.5的吗

**Comment by code4craft** [comment]
`/html/body/div[5]/script[1]/text()`这个语法是支持的，是不是写错了？
序号是从1开始的哦。

**Comment by mingj** [comment]
我有时间了再验证一下，谢谢。
