### ISSUE TITLE
XPath和Jsoup抓取Table的问题。

### ISSUE THREAD

**Issue by cnx2016** [code4craft/webmagic#285]
XPath遍历一个Table的tr，得到的tr为：
`<tr><td>2016-03-31</td>
<td>上海翘楚网络科技有限公司</td>
<td>预审通过</td>
</tr>`

这时候用XPath去选择td元素的话会有问题，因为BaseElementSelector.java的
第18行代码是：Jsoup.parse(text)
text就是上面的tr内容
Jsoup的parse方法会把tr、td元素都删除，加上html等节点。

网上搜了下，tr外面加个table包裹下就好了，这得修改Jsoup源码么？

请问有没有好的解决方法？？？

**Comment by cnx2016** [comment]
想实现的效果是抓取Table的每一行tr，生成一个model，最后返回一个list。

**Comment by code4craft** [comment]
因为Jsoup会将这个文本当做html，按照语法来说是需要<table>的。建议方案是加上<table>。
