### ISSUE TITLE
HTTP Proxy

### ISSUE THREAD

**Issue by robin-obrien** [code4craft/webmagic#286]
Hi,

I cannot find an example that uses an HTTP Proxy, how can that be achieved?

Thanks

**Comment by robin-obrien** [comment]
And is there a way to set the HTTP Proxy username and password

**Comment by robin-obrien** [comment]
@code4craft

**Comment by robin-obrien** [comment]
@code4craft Is this project maintained ?

**Comment by hepan** [comment]
you can see https://github.com/code4craft/webmagic/pull/290

**Comment by jsbd** [comment]
该ISSUE可以关闭了
