### ISSUE TITLE
运行mvn package时出现以下问题，请问该如何解决！

### ISSUE THREAD

**Issue by woshihoujinxin** [code4craft/webmagic#287]
[ERROR] /Users/houjinxin/Documents/wswebmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/configurable/ExtractRule.java:10: 错误: 未知标记: date
[ERROR] \* @date 14-4-5
[ERROR] ^
[ERROR] /Users/houjinxin/Documents/wswebmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/handler/CompositePageProcessor.java:12: 错误: 未知标记: date
[ERROR] \* @date 14-4-5
[ERROR] ^
[ERROR] /Users/houjinxin/Documents/wswebmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/handler/SubPageProcessor.java:7: 错误: 未知标记: date
[ERROR] \* @date 14-4-5
[ERROR] ^

**Comment by code4craft** [comment]
你的JDK版本是不是比较老了？

**Comment by code4craft** [comment]
javadoc的问题，最新版本应该已解决。
