### ISSUE TITLE
JsonPathSelectorTest在不同JDK下会测试失败

### ISSUE THREAD

**Issue by suemi994** [code4craft/webmagic#289]
本人测试环境 JDK:1.8,MAC OSX
出现以下错误

Expected :'{"author":"Nigel Rees","title":"Sayings of the Century","category":"reference","price":8.95}'
Actual   :'{"author":"Nigel Rees","price":8.95,"category":"reference","title":"Sayings of the Century"}'

是由于JsonPath read后生成的Hash key的顺序不能保证与字段出现顺序一致，建议改为：

```java
JSONObject object1=JSON.parseObject(select);
    JSONObject object2=JSON.parseObject("{\"author\":\"Nigel Rees\",\"title\":\"Sayings of the Century\",\"category\":\"reference\",\"price\":8.95}");
    assertEquals(object1,object2);
```

**Comment by code4craft** [comment]
感谢指正，今天我也发现了这个问题，已经修改。
