### ISSUE TITLE
Xpath 抓取<Title>包含某些字的頁面

### ISSUE THREAD

**Issue by a6091731** [code4craft/webmagic#292]
**您好 

我是新手 想請教您一些爬蟲條件如何撰寫

如果我要抓取一個頁面 條件是 頁面 title 要包含某些字

網路上有人是這樣寫 [contains(title,包含的字)]

我自己改寫成這樣 : 
page.putField("title", page.getHtml().xpath("//[contains(title,'賈伯斯、坎貝爾、葛洛夫三位大師教我的事')]/allText()").toString());

但實作出來 就算Title沒有包含 "賈伯斯、坎貝爾、葛洛夫三位大師教我的事" 的頁面也會抓取出來

請問我應該如何撰寫呢

感謝您

**Comment by a6091731** [comment]
this is my code : 
page.putField("title", page.getHtml().xpath("//[contains(title,'賈伯斯、坎貝爾、葛洛夫三位大師教我的事')]/allText()").toString());

**Comment by lzjohnny** [comment]
有可能是你的XPath表达式写错了，试试`xpath("//title[contains(text(),'你需要匹配的文本')]")`。可以在chrome的控制台中输入`$x("//title[contains(text(),'你需要匹配的文本')]")`来测试XPath表达式是否正确。
