### ISSUE TITLE
抓取table的问题 很头疼

### ISSUE THREAD

**Issue by wjk1982** [code4craft/webmagic#298]
<table class="specificationBox" cellspacing="1" cellpadding="3" width="100%">
<tbody>
    <tr><th colspan="2" class="titleName">第三方和水电费过</th></tr>
    <tr><th colspan="2" class="titleP">对是否会的用</th</tr> 
    <tr><th>名称 ： </th><td>大锅饭</td></tr><tr class="colorWhite"><th>东方红 ： </th><td>是地方好</td></tr>
    <tr><th>商品 ： </th><td>999牌</td></tr><tr class="colorWhite"><th>成份 ： </th><td>岗梅、阿萨德发撒发达</td></tr>
</tbody>
</table>

public class DetailInfo{

```
   @ExtractBy("//table[@class='specificationBox']/tbody/tr/th/text()")
   private List<String> keys ;
   .......
```

}

不管怎么弄,完全不起作用,请问如何处理

**Comment by wjk1982** [comment]
请速度帮我解决这个问题 怀疑解析table有大的bug

**Comment by wjk1982** [comment]
问题可能已经找到了 但是不知道如何解决 
是因为拿出来table数据 变为 /&gt;&lt;/p&gt;&lt;br /&gt;&lt;h2 class='imgClass'&gt;&lt;img bord类似与这样的字符串

**Comment by wjk1982** [comment]
>变为gt  <变为lt

**Comment by wjk1982** [comment]
可能是因为textarea 中的table数据会自动转义 这个应该如何处理呢

**Comment by wjk1982** [comment]
//table[@class='specificationBox']//tr/th/text()
如果要从第三个tr后才取数据 如何实现呢 
//table[@class='specificationBox']//tr:gt(3)/th/text() 报错了

**Comment by wjk1982** [comment]
请问你的注解如何从第三个tr开始抓取呢
@ExtractBy("//table[@class='specificationBox']//tr[position()>3]/th/text()")都会报错

**Comment by code4craft** [comment]
目前你说的语法都无法支持，Xpath的语法实现已经排过日程了。
[https://github.com/code4craft/xsoup/issues/11](https://github.com/code4craft/xsoup/issues/11)
