### ISSUE TITLE
获取链接出现乱码

### ISSUE THREAD

**Issue by zhang-hang** [code4craft/webmagic#303]
使用 page.getHtml().links() 时，发现乱码，每个字符都会用","分隔开，非常奇怪？

page.addTargetRequests(page.getHtml().links().regex(urlPost).all());
System.out.println("内容页 rege url:==>"+page.getHtml().links().all());

输出：
内容页 rege url:==> [h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, s, e, e, g, i, s, t, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, s, e, f, g, e, t, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, i, n, e, ., h, t, m, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, I, n, e, ., h, t, m, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, i, p, h, s, e, ., h, t, m, l, h, t, t, p, :, /, /, a, t, ., m, a, i, t, i, a, n, ., c, n, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, s, e, e, g, i, s, t, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, s, e, l, g, i, n, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, w, a, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, m, a, p, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, S, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, S, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, S, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, S, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, S, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, S, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, A, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, A, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, A, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, A, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, A, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, A, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, H, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, H, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, H, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, H, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, H, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, T, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, /, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, a, l, l, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, m, a, p, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n, /, e, s, f, /, I, F, h, t, t, p, :, /, /, m, a, i, t, i, a, n, ., c, n,

**Comment by code4craft** [comment]
我觉得可能是你正则写的有问题，试试看看page.getHtml().links().all()的结果？

**Comment by zhang-hang** [comment]
上面的输出结果就是  page.getHtml().links().all() 的结果；

奇怪的是，在IDEA中调试都没问题，直接在shell里执行程序包时就会出现这个问题？

**Comment by zhang-hang** [comment]
另外，折腾半天，又出新问题了： 
爬虫业务任务开始 ::==>
GeneralPageProcessor
class com.zhugefang.spider.GeneralPageProcessor
com.jayway.jsonpath.InvalidPathException: invalid path
        at com.jayway.jsonpath.internal.filter.FieldFilter.filter(FieldFilter.java:59)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:191)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:211)
        at us.codecraft.webmagic.selector.JsonPathSelector.selectList(JsonPathSelector.java:44)
        at us.codecraft.webmagic.selector.AbstractSelectable.selectList(AbstractSelectable.java:40)
        at us.codecraft.webmagic.selector.Json.jsonPath(Json.java:55)
        at com.zhugefang.spider.SpiderJobRunner.doTask(SpiderJobRunner.java:56)
        at com.zhugefang.spider.SpiderJobRunner.run(SpiderJobRunner.java:204)
        at com.github.ltsopensource.tasktracker.runner.JobRunnerDelegate.run(JobRunnerDelegate.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
com.jayway.jsonpath.InvalidPathException: invalid path

**Comment by zhang-hang** [comment]
也是在IDEA调试没问题，打包执行就这样。

**Comment by code4craft** [comment]
这个是jsonpath写的不对
