### ISSUE TITLE
使用注解方式，在效率上有差别吗？

### ISSUE THREAD

**Issue by medmin** [code4craft/webmagic#304]
我感觉有差别，不仅是爬得慢了， 而且似乎也爬的不好。
不知道有人和我同感吗？

此外，怎样来确认一个网站有没有全部爬到呢？

**Comment by code4craft** [comment]
效率上会稍微低一点，不过因为两者抓取机制完全不同，感觉到慢的话，更可能是抓到了无关的页面，可以看一下HttpClientDownloader的log。
