### ISSUE TITLE
xsoup依赖的版本是0.2.4，否则编译错误。

### ISSUE THREAD

**Issue by wzjin** [code4craft/webmagic#309]
xsoup依赖的版本是0.2.4，否则编译错误。

webmagic-0.5.3\pom.xml
这里修改。

**Comment by code4craft** [comment]
maven中央库是0.3.1版本，你看看是不是你依赖的私服不对？
[http://search.maven.org/#artifactdetails%7Cus.codecraft%7Cxsoup%7C0.3.1%7Cjar](http://search.maven.org/#artifactdetails%7Cus.codecraft%7Cxsoup%7C0.3.1%7Cjar)

**Comment by wzjin** [comment]
换成了0.3.1可以。编译过程还是有点波折，test中有些没有通过的就注释了，依赖关系做了些整理才通过。

**Comment by wzjin** [comment]
webmagic-0.5.3生成的jar和配置的pom.xml文件可以在下面位置下载。
http://download.csdn.net/detail/wzjin/9517112
调试修改好久才生成，包括修改代码和修改pom.xml文件，共享出来大家少走弯路。
