### ISSUE TITLE
如何实现更新网页呢？

### ISSUE THREAD

**Issue by FireInTheWall** [code4craft/webmagic#311]
目前的业务场景中，有两种情况：
1. 普通的爬虫 Request；
2. 某些网站中的一些特殊页面，需要实时的去多次爬取更新内容。

对于 1 来说进行去重是有必要的，对于 2 来说，没有必要去进行去重。

爬虫的种子均从 Redis 队列中提取，而所有的需要更新的页面均存放于 Redis 某个特定的队列中。

目前的解决方案是：在 Request 中添加了 isUpdate 字段用于标志本次 Request 是否用于更新，isUpdate 字段默认为 false，这样可以保证在种子中爬取到的页面不会一直重复的被爬虫爬取。
同时，对于从 Redis 中提取的那些特定需要更新的页面，设置 isUpdate 为 true。
在通过 isDuplicate 去重之前，先判断 isUpdate 是否 true，如果为 true，则不进行去重。

请问您有更好的解决方案么？

**Comment by code4craft** [comment]
我一般都是重新爬之前清掉的。

**Comment by kazuyaYX** [comment]
请问要如何清掉？ @code4craft

**Comment by Salon-sai** [comment]
@kazuyaYX resetDuplicateCheck方法

**Comment by pengkw** [comment]
resetDuplicateCheck将之前某个site下的所有的已抓取的key全部清除掉，不能满足有些需要重新抓取，有些抓取过了就不需要在抓取
