### ISSUE TITLE
发现这个有问题：com.alibaba.fastjson.JSON

### ISSUE THREAD

**Issue by zhang-hang** [code4craft/webmagic#313]
us.codecraft.webmagic.selector.Json;
com.alibaba.fastjson.JSON;

这两个有问题

[INFO ] [21:39:48] com.github.ltsopensource.core.support.RetryScheduler -  [LTS] JobPushProcessor RetryScheduler, local files save success, identity=[TT_192.168.174.1_10436_21-28-13.663], {"action":"EXECUTE_EXCEPTION","jobMeta":{"internalExtParams":{"__LTS_Repeat_Job_First_Fire_Time":"null"},"job":{"cron":false,"extParams":{"referer":"http://maitian.cn","tasktype":"General","url_start":"[\"http://maitian.cn/esfall/PG1\"]","url_list":"[\"http://maitian.cn/esfall/.*\",\"http://maitian.cn/esfall/PG.*\"]","taskname":"???????????","retry_time":"3","thread":"10","sleep_time":"3000","put_fields":"[{\"regex\":[\"/html/body/section[2]/div[1]/h1/samp/text()\"],\"select\":\"xpath\",\"field\":\"house_title\",\"type\":\"string\",\"required\":\"true\"},{\"regex\":[\"/html/body/section[2]/div[1]/table/tbody/tr[1]/td/text()\"],\"select\":\"xpath\",\"field\":\"house_price\",\"type\":\"string\",\"required\":\"false\"},{\"regex\":[\"/html/body/section[2]/div[2]/dl/dd[1]/span/a/text()\"],\"select\":\"xpath\",\"field\":\"owner_name\",\"type\":\"string\",\"required\":\"true\"},{\"regex\":[\"/html/body/section[2]/div[2]/ul/text()\"],\"select\":\"xpath\",\"field\":\"owner_phone\",\"type\":\"string\",\"required\":\"true\"},{\"regex\":[\"/html/body/section[3]/table/tbody/tr/td[1]/a/label/span/text()\"],\"select\":\"xpath\",\"field\":\"borough_name\",\"type\":\"string\",\"required\":\"false\"}]","cycle_retry_time":"3","url_page":"[{\"from\":\"1\",\"to\":\"10\",\"url\":\"http://maitian.cn/esfall/PG{page}\"},{\"from\":\"1\",\"to\":\"10\",\"url\":\"http://maitian.cn/esfway/PG{page}\"}]","domain":"maitian.cn","url_post":"[\"http://maitian.cn/esfxq/.*\"]","downloader":"httpclient"},"maxRetryTimes":3,"needFeedback":true,"priority":100,"relyOnPrevCycle":true,"repeatCount":-1,"repeatInterval":60000,"repeatable":true,"replaceOnExist":false,"submitNodeGroup":"JOB_CLIENT","taskId":"esfall_bj_maitan","taskTrackerNodeGroup":"Spider_TaskTracker","triggerTime":1463133965000},"jobId":"ACD9973D649D48398370B8C35B6AE11F","jobType":"REPEAT","realTaskId":"esfall_bj_maitan","repeatedCount":0,"retryTimes":0},"msg":"com.alibaba.fastjson.JSONException: exepct '[', but string, type : class com.zhugefang.spider.model.SpiderTaskInfo\r\n\tat com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFieldDeserializer.java:104)\r\n\tat com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFieldDeserializer.java:53)\r\n\tat com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:74)\r\n\tat com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer$InnerJavaBeanDeserializer.parseField(ASMJavaBeanDeserializer.java:86)\r\n\tat com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:330)\r\n\tat com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)\r\n\tat Fastjson_ASM_SpiderTaskInfo_24.deserialze(Unknown Source)\r\n\tat com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)\r\n\tat com.alibaba.fastjson.JSON.parseObject(JSON.java:251)\r\n\tat com.alibaba.fastjson.JSON.parseObject(JSON.java:227)\r\n\tat com.alibaba.fastjson.JSON.parseObject(JSON.java:186)\r\n\tat com.alibaba.fastjson.JSON.parseObject(JSON.java:304)\r\n\tat com.zhugefang.spider.SpiderJobRunner.doTask(SpiderJobRunner.java:52)\r\n\tat com.zhugefang.spider.SpiderJobRunner.run(SpiderJobRunner.java:210)\r\n\tat com.github.ltsopensource.tasktracker.runner.JobRunnerDelegate.run(JobRunnerDelegate.java:85)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n","time":1463233188073}, lts version: 1.6.8, current host: 192.168.174.1

**Comment by zhang-hang** [comment]
问题是这样的，在IDEA编辑器里面调试运行一切都正常，打包单独运行时，就报错了。很多问题来源于这个，据说是 fastjson 有问题。

**Comment by zhang-hang** [comment]
能解决吗?

**Comment by code4craft** [comment]
感觉是jar包版本的问题，预计给WebMagic无关，先关闭了。
