### ISSUE TITLE
webmagic-core工程中依赖org.apache.commons.lang3不可用，求指导！

### ISSUE THREAD

**Issue by 404013092GitHub** [code4craft/webmagic#314]
工具：idea
搭建方式：Maven
随意搭建一个项目后，通过pom文件依赖webmagic-core与webmagic-extension；在运行官网的demo时：
提示java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils。
PS:工程中已经引入org.apache.commons.lang3这个jar包了，但是webmagic-core始终报错，郁闷。
![26](https://cloud.githubusercontent.com/assets/11717630/15275298/46df2756-1afa-11e6-989b-2077d194d03c.png)

**Comment by 404013092GitHub** [comment]
在执行之前，我先跑一下了StringUtils这个方法(没有问题)，但是downloader调用的时候就挂了！无解啊，折腾半天都搞不明白，求大神指导指导。

**Comment by code4craft** [comment]
见#296

**Comment by 404013092GitHub** [comment]
感谢您的热心解答，但是问题依旧没有解决。
我先说一下发现的问题：
1)通过idea创建一个简单的springboot项目[参考官网的demo]
2)在springboot的微框架pom中添加webmagic的依赖[version-0.5.3]
3)复制webmagic.io上的demo[@see 2.3 第一个项目]到任意java文件中->run
以上操作后程序会莫名的出现一些错误，比如java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils等。
但是当把工程中其他的pom依赖去掉后[pom只依赖了]，再次执行java文件，此时程序正常了！
会不会是包依赖导致的冲突呢？
PS:本人小白，因看到了webmagic，感兴趣，但是好多知识都不懂，描述不妥的地方请见谅。
![qq 20160517003952](https://cloud.githubusercontent.com/assets/11717630/15296503/37472752-1bc8-11e6-807d-8608cf95960e.png)

**Comment by tomalloc** [comment]
还要引入commons-lang:commons-lang:2.x 这个包,由于webmagic依赖jsonpath,jsonpath用到了commons-lang2,所以....

**Comment by 178220709** [comment]
其实是这样的. webmagic-core引用了低版本的json-path,
低版本的json-path又引用了commons-lang:commons-lang:2.x,
出问题的地方在于:webmagic-core事实上依赖于commons-lang:commons-lang:2.x
但在它的pom里面并没有声明.
结果maven认为json-path可以直接替换成高级依赖(commons-lang:3.x),但是webmagic-core偷偷依赖的commons-lang:2.x就没了.

解决办法同楼上.

其实这应该算是一个bug.

**Comment by banner1024** [comment]
assertj-core-1.5.0.jar
c3p0-0.9.5.2.jar
commons-codec-1.9.jar
commons-collections-3.2.1.jar
commons-exec-1.3.jar
commons-io-1.3.2.jar
commons-lang-2.6.jar
commons-lang3-3.1.jar
commons-logging-1.2.jar
commons-pool-1.5.5.jar
fastjson-1.1.37.jar
fluent-hc-4.5.2.jar
gson-2.3.1.jar
guava-15.0.jar
hamcrest-core-1.3.jar
htmlunit-2.21.jar
htmlunit-core-js-2.17.jar
httpclient-4.5.2.jar
httpclient-cache-4.5.2.jar
httpclient-win-4.5.2.jar
httpcore-4.4.4.jar
httpmime-4.5.2.jar
jedis-2.0.0.jar
jetty-io-9.2.15.v20160210.jar
jetty-util-9.2.15.v20160210.jar
jna-4.1.0.jar
jna-platform-4.1.0.jar
json-path-0.8.1.jar
json-smart-1.1.1.jar
jsoup-1.7.2.jar
junit-4.11.jar
log4j-1.2.17.jar
mchange-commons-java-0.2.11.jar
mysql-connector-java-5.1.38-bin.jar
neko-htmlunit-2.21.jar
phantomjsdriver-1.2.1.jar
sac-1.3.jar
selenium-java-2.53.0.jar
serializer-2.7.2.jar
slf4j-api-1.7.6.jar
slf4j-log4j12-1.7.6.jar
webmagic-core-0.5.2.jar
webmagic-extension-0.5.2.jar
websocket-api-9.2.15.v20160210.jar
websocket-client-9.2.15.v20160210.jar
websocket-common-9.2.15.v20160210.jar
xalan-2.7.2.jar
xercesImpl-2.11.0.jar
xml-apis-1.4.01.jar
xsoup-0.2.4.jar
一网打尽可好？

**Comment by code4craft** [comment]
在HttpClientDownloader中做了点修改，不再依赖2.x的StringUtils了

**Comment by 404013092GitHub** [comment]
谢谢，各位的热心帮助，之前出差不方便上网，很抱歉，现在该问题已经关闭了。
