### ISSUE TITLE
发现一个关于路径的bug

### ISSUE THREAD

**Issue by laoma036912** [code4craft/webmagic#315]
FilePersistentBase类中setPath方法代码如下：
public void setPath(String path) {
        if (!path.endsWith(PATH_SEPERATOR)) {
            path += PATH_SEPERATOR;
        }
        this.path = path;
    }
说明：这里path内容的结尾是以“/”或"\"结尾的，如：“D://”

它的子类中如JsonFilePipeline类的process方法实现有如下代码：
String path = this.path + PATH_SEPERATOR + task.getUUID() + PATH_SEPERATOR;
说明：这里我在使用此子类的构造方法中，调用了setPath(path);
因此this.path的值如："D://"， 然后后面又append了一个PATH_SEPERATOR ，造成了重复。。
其它子类也是如此。

解决方法：最好是将子类中多追加的PATH_SEPERATOR 全都去除掉。

**Comment by SkyFire-Lee** [comment]
在`File`类中的`normalize`函数里会将路径中重复的斜杠直接过滤掉，并将路径格式化，感觉不需要太特意的在类中出多余的斜杠
