### ISSUE TITLE
关于RedisScheduler去重的问题

### ISSUE THREAD

**Issue by Salon-sai** [code4craft/webmagic#316]
我看了一下RedisScheduler的代码，觉得这样做不能完全取重。
#### 分析如下：
1. 在redis当中，定义三个键，分别是：
   - 待爬取队列(前序为queue_ ),
   - 待爬取url的相关参数(前序为item_ ),
   - 已爬取url(前序为set_ )
2. 看代码 **isDuplicate方法** 

``` java
    public boolean isDuplicate(Request request, Task task) {
        Jedis jedis = pool.getResource();
        try {
            boolean isDuplicate = jedis.sismember(getSetKey(task), request.getUrl());
            if (!isDuplicate) {
                jedis.sadd(getSetKey(task), request.getUrl());
            }
            return isDuplicate;
        } finally {
            pool.returnResource(jedis);
        }

    }
```

显然是通过判断是否存在已爬取的url来去重url，但对于待爬取队列并没有判断。所以redis去重并不全（特别是在待爬取队列很多时）。
#### 建议：

我建议作者创建两个set在redis中，一个是已爬取的set_finish，另一个是待爬取的set_ready。这样就能够去重完整。例外可以使用sorted set 可以做到优先级redis队列。我就是在自己项目这样做到基于redis进行去重url和优先级爬取

**Comment by code4craft** [comment]
按照我的理解，getSetKey(task)就是待抓取和已抓取的URL的集合。

**Comment by Salon-sai** [comment]
重现看回代码发现是我理解出了在 **DuplicateRemovedScheduler** 类中的 **push** 方法已经判断该url是否存在与redis中或者该request是否应该重新爬取。
```java
    public void push(Request request, Task task) {
        logger.trace("get a candidate url {}", request.getUrl());
        if (!duplicatedRemover.isDuplicate(request, task) || shouldReserved(request)) {
            logger.debug("push to queue {}", request.getUrl());
            pushWhenNoDuplicate(request, task);
        }
    }
```

导致我出现url不能去重的原因可能是因为我定时再次爬取时使用 **resetDuplicateCheck** 方法清除set的内容，而这时queue里面还有内容（这是我程序里面的bug）。感谢作者 若无什么作者可以先把这个issue 先close。不知作者是否需要把这个redis+优先级处理的Scheduler做出来呢？又或者把PriorityScheduler写得更灵活呢？毕竟对于优先级是常用的并且经常与其他Scheduler相结合

**Comment by code4craft** [comment]
Redis加优先级我也不知道该如何实现，可能用sorted-set这样的可以，有兴趣的话不妨研究一下，给我提个patch？
