### ISSUE TITLE
获取不到@Formatter,fieldExtractor得到formatter错误

### ISSUE THREAD

**Issue by dcx013** [code4craft/webmagic#317]
获取不到@Formatter,fieldExtractor得到formatter错误

**Comment by code4craft** [comment]
你的属性类型是什么？最好提供一下字段。

**Comment by dcx013** [comment]
java.util.date,调试的时候无论formmater的value填什么格式,都是formatter默认的,代码没有正确的获取,可能用错了方法.

**Comment by yangsaipp** [comment]
@dcx013 我刚刚也遇到这个问题，跟踪代码发现其实是需要在注解里指定formatter才行。参考以下代码。
`
@Formatter(value = "yyyy.MM.dd",formatter = DateFormatter)
@ExtractBy('//div....')
Date dealDate`
@code4craft 这里应该可以优化下，DateFormatter是较特殊的base formatter，它需要传入格式化参数。

**Comment by yangsaipp** [comment]
我使用的webmagic版本是0.5.3。

**Comment by code4craft** [comment]
在PR#570 中已修复。
