### ISSUE TITLE
HttpProxyPool这块的逻辑能稍微讲下么，从代理池中取得一个代理，放到request中后，request请求失败后，没有找到再次设置个代理再请求啊

### ISSUE THREAD

**Issue by lwjydhcg** [code4craft/webmagic#318]
从代理池中取得一个代理，放到request中后，request请求失败后，没有找到再次设置个代理再请求啊

**Comment by code4craft** [comment]
代理这块是@yxssfxwzy 提供的patch，具体流程图可以看这里。
 
        +----------+     +-----+
        | last use |     | new |
        +-----+----+     +---+-+
              |  +------+   |
              +->| init |<--+
                 +--+---+
                    |
                    v
                +--------+
           +--->| borrow |
           |    +---+----+
           |        |+------------------+
           |        v
           |    +--------+
           |    | in use |  Respone Time
           |    +---+----+
           |        |+------------------+
           |        v
           |    +--------+
           |    | return |
           |    +---+----+
           |        |+-------------------+
           |        v
           |    +-------+   reuse interval
           |    | delay |   (delay time)
           |    +---+---+
           |        |+-------------------+
           |        v
           |    +------+
           |    | idle |    idle time
           |    +---+--+
           |        |+-------------------+
           +--------+
