### ISSUE TITLE
mvn install时，报错，未知标记: Deprecated

### ISSUE THREAD

**Issue by xjianster** [code4craft/webmagic#319]
请问是什么原因，下载然后执行mvn install -Dmaven.test.skip=true时报以上错误

另外，发现us.codecraft.webmagic.site的474行，参数列表写错了，这个mvn竟然也报错

**Comment by code4craft** [comment]
嗯，参数没有更新，会在下个版本前修复。

**Comment by code4craft** [comment]
已修复。
