### ISSUE TITLE
关于在 UrlUtils 中添加一个获取顶级域名的方法

### ISSUE THREAD

**Issue by FireInTheWall** [code4craft/webmagic#323]
目前在 UrlUtils 中的 getDomain 方法获取的是二级域名，例如：http://github.com 和 https://help.github.com/categories/github-pages-basics/ 返回的就不一样。

通过 Guava 包的 InternetDomainName 方法可以直接获取顶级域名：

```
    public static String getTopLevelDomain(String url)  {
        String domain = getDomain(url);

        return InternetDomainName.from(domain).topPrivateDomain().toString();
    }
```

**Comment by code4craft** [comment]
WebMagic主要还是使用完整的域名，所以没有计划加入此方法。
