### ISSUE TITLE
求解答: 为什么要把 Site 的配置放在 PageProcessor 中?

### ISSUE THREAD

**Issue by qijiqiguai** [code4craft/webmagic#329]
是不是可以这样理解, Downloader 基本可以做到通用, 大略也就几种情况, 但是 Processor 是不能通用的, 所以所有的 Site 设置都放在了 Processor 中. 这样就可以默认不配置 Downloader 了, 直接用标准的HttpClientDownloader就可以.

但是, 如果这样的话, Site 本身放在 Spider 中是更加合理么, 为什么要在 Processor 中保持一份呢?

**Comment by tomalloc** [comment]
从爬虫的设计角度来说,每个网站的cookie是不一样的,这样每个网站的Processor都应该有自己对应的Site,这是合理的.但是从Spider的设置及其他源码不难看出,只能设置一个Processor,也没有按域名来调用对应的Proccessor.另外,如果没有设置Site,情况就遭了,`NullPoninterException`等着你. 以上就导致了题主的疑问.

**Comment by code4craft** [comment]
设计的初衷很简单：写一个`PageProcessor `就完成了一个爬虫。
现在看来这种配置和代码放在一起的方式，对于比较复杂的抓取需求还是不太友好的，不过可以通过扩展来实现。目前没有重构的计划。
