### ISSUE TITLE
Database persistence

### ISSUE THREAD

**Issue by pascalheraud** [code4craft/webmagic#331]
Hello,

Does webmagic has a database persistence features ?
I mean persistence of the state of the spider into database to be able to interrupt the spider and not keep the state into memory.
I dont see any reference from documentation.

I'd be interested in such a feature. I could add it to webmagic or make an extension if you'd like.

**Comment by qijiqiguai** [comment]
I can see from the code that there is a RedisScheduler & FileCacheQueueScheduler in webmagic-extension. 

If you trust Redis service, you can use it so isolate your spider and scheduler. 
FileCacheQueueScheduler can be another choice for you to try, But not for me, simply don't like this way.

But if you mean, only trust RDBMS like MySQL, I can't see it in the code, you may add it by your own :)

**Comment by pascalheraud** [comment]
Ok, I worked on it and made a DatabaseScheduler that stores all requests into a Database.
Where do you want me to inlcude this ?

**Comment by pascalheraud** [comment]
Hello,
I added a PR with the code for storing requests in a database.
#391

**Comment by code4craft** [comment]
Thanks!
But there is no plan to add a build-in DatabaseScheduler because I think the users may prefer their own way to store urls (if they choose a RDBMS).
