### ISSUE TITLE
Robots.txt compliance

### ISSUE THREAD

**Issue by pascalheraud** [code4craft/webmagic#332]
Hello,

Is there any plan for making webmagic compliant to robots.txt ?
I'd need this feature and would be interested in making it if you'd like to add it to webmagic.

By compliance to robots.txt, I mean that it could automatically parse robots.txt and avoid crawling websites refusing it. In a long term running spider (for instance, to keep an index up to date), it could be interesting to test for some urls if the robots.txt doesn't deny them since it has been crawled the first time.

**Comment by pascalheraud** [comment]
Along with robots.txt may come parsing sitemap.xml.
Is it a feature we could add to this library ?

**Comment by pascalheraud** [comment]
Hello, 
I added a PR with the code for managing robots.txt and sitemaps.
#391

**Comment by code4craft** [comment]
A good idea. But I prefer to add a filter in Scheduler for this.
I see the MultiSiteSpider in your PR. WebMagic is not prefer  to build an open web spider so I think it is a bit complicated.

**Comment by pascalheraud** [comment]
How works Filter ? I dont see any feature like this.
