### ISSUE TITLE
用了pipeline内容没有保存下来。

### ISSUE THREAD

**Issue by wbz5087** [code4craft/webmagic#335]
用了.addPipeline(new JsonFilePipeline("D:\webmagic\"))之后，webmagic中没有内容。

**Comment by SkyFire-Lee** [comment]
**路径问题：**应该是`E:\\webmagic`而并非一个斜杠
**页面过滤：**将大部分页面都设置了_skip_，导致会出现很久都没下载成功
```
        if (!page.getResultItems().isSkip()) {
            for (Pipeline pipeline : pipelines) {
                pipeline.process(page.getResultItems(), this);
            }
        }
```
估计是你对某些页面

**Comment by zhangyc** [comment]
路径写成“E:\\webmagic”依然没有结果

**Comment by sutra** [comment]
> 路径写成“E:\webmagic”依然没有结果

`E:\webmagic` -> `E:\\webmagic` 注意反斜线的个数。
