### ISSUE TITLE
Add more than 100 000 url in spider

### ISSUE THREAD

**Issue by timactive** [code4craft/webmagic#336]
Hi, 
I want to know what is the good approach to add specific url to the spider.
In fact i have a list of 100 000 url specific for a same domain.(I just want collect data)
I view i can add this directly in spider.addUrl?

Let me know

**Comment by Salon-sai** [comment]
You can add the specific URL with **Page** class.
The process method in the Processor class which extends the PageProcessor can add target request with page.
```java
String url = ....;
Request request = new Request(url);
page.addTargetRequest(request);
```

**Comment by code4craft** [comment]
see #222
syntax `http://angularjs.cn/api/article/latest?p=[1-100]&s=20` will be added in future.
