### ISSUE TITLE
对于动态网页只能支持get方式的，不能支持post方式的

### ISSUE THREAD

**Issue by scott929** [code4craft/webmagic#338]
你的动态网页抓取时采用的找到url，但是post是不能找到url的，必须模拟一个heard和form，该框架能够实现这个功能呢？

**Comment by Salon-sai** [comment]
发出post请求方法要定义个Request对象 通过setMethod()设置为POST方法。
然后在request设置form的参数的话，在Request对象中设置键为nameValuePair，值类型为NameValuePair对象的数组就可以了

```java
Request request = new Request(URL);
NameValuePair[] nameValuePairs = {
   new BasicNameValuePair("key1", "value1"),
   new BasicNameValuePair("key2", "value2"),
   new BasicNameValuePair("key3", "value3"),
};

request.setMethod(HttpConstant.Method.POST);
request.putExtra('nameValuePair', nameValuePairs);
```

**Comment by Talefairy** [comment]
我试了一下，这种方式不行吧？

**Comment by code4craft** [comment]
[https://github.com/webmagic-io/docs/issues/18](https://github.com/webmagic-io/docs/issues/18)
可以的，但是这块没有文档，增加了一个补充文档的任务。

**Comment by wangtengchina** [comment]
post请求的时候，如果url相同，nameValuePair的数据不同，加入多个request，就会被去重了，作者能不能修复下这个问题

**Comment by code4craft** [comment]
#484 0.6.2版本后POST默认不去重。
