### ISSUE TITLE
Add more http info to page

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#35]
Add more http such as Http Status Code, cookies to page.

**Comment by xchz** [comment]
HttpResponse.getEntity().getContent()转成string，存在Page的RawText里，为啥输出只能看到html，不能看到response headers？没理解这里，求指导

**Comment by xchz** [comment]
如何获取response headers？大神求解答啊。

**Comment by code4craft** [comment]
还没有header，我新建了一个issue #406

**Comment by xchz** [comment]
谢谢答复。
是不是HttpResponse.getEntity().getContent() 里只有response body？我查了httpclient文档，貌似entity里只有response body？那么RawText里也只存了response body？当前issue(Add more http info to page #35)是完成了添加cookie到 Page对象，这里提到的cookie是response headers里Set-Cookie 这个header指定的cookie吗？如果是，我如何在Page对象中取得这个cookie（因为我要把这个cookie，放到下次的request里）？如果不是，那么是不是就拿不到response headers里Set-Cookie？要等到#406完成。。。目前有什么推荐的替代的方案吗？

**Comment by code4craft** [comment]
你可以扩展Downloader，在Page里面加上header。

**Comment by xchz** [comment]
ok，我继承HttpClientDownloader，重写handleResponse
