### ISSUE TITLE
GithubRepoPageProcessor中正则表达式缺少+号

### ISSUE THREAD

**Issue by chwshuang** [code4craft/webmagic#353]
us.codecraft.webmagic.processor.example.GithubRepoPageProcessor第18、19行
page.addTargetRequests(page.getHtml().links().regex("(https://github\.com/[\w\-]+/[\w\-])").all());
page.addTargetRequests(page.getHtml().links().regex("(https://github\.com/[\w\-])").all());
应该为：
page.addTargetRequests(page.getHtml().links().regex("(https://github\.com/[\w\-]+/[\w\-]+)").all());
        page.addTargetRequests(page.getHtml().links().regex("(https://github\.com/[\w\-]+)").all());

**Comment by code4craft** [comment]
已修复。
