### ISSUE TITLE
xpath解析器 不支持 last() 语法

### ISSUE THREAD

**Issue by imchuan** [code4craft/webmagic#357]
page.getHtml().xpath("//*[@id=\"divcontent\"]/div/div/div[1]/div[1]/div[1]/div[3]/div/span[last()-1]/text()")

**Comment by caychan** [comment]
什么意思？现在支持了？

**Comment by peony07** [comment]
同问，啥时候能支持啊。

**Comment by code4craft** [comment]
记录到xsoup里了。
[https://github.com/code4craft/xsoup/issues/21](https://github.com/code4craft/xsoup/issues/21)

**Comment by zhangzhiguang2** [comment]
String() 函数也不可以用？

**Comment by itliuxing** [comment]
同问，还有没有在更新：last() 等待支持
