### ISSUE TITLE
HttpClientDownloader.getContent自动编码转换错误

### ISSUE THREAD

**Issue by HaKuY** [code4craft/webmagic#367]
网页中编码设置错误，例如charset=gbk2312"时候。us.codecraft.webmagic.downloader.HttpClientDownloader.getContent(HttpClientDownloader.java:196)进行自动编码转换时候报错，因为根本就没有gbk2312编码。

**Comment by code4craft** [comment]
…
给我个页面去瞻仰一下。另外我觉得你可以手动设置一下编码。
