### ISSUE TITLE
分布式环境下RedisSchedular判断是否重复URL应该要加个分布式锁控制吧？

### ISSUE THREAD

**Issue by caokaifang** [code4craft/webmagic#368]
在分布式环境下RedisSchedular判断是否重复URL这段代码：
boolean isDuplicate = jedis.sismember(getSetKey(task), request.getUrl());
if (!isDuplicate) {
    jedis.sadd(getSetKey(task), request.getUrl());
}
应该要加个分布式锁控制吧？

**Comment by code4craft** [comment]
是的，这里处理不严格，分布式锁太复杂了，改成了直接用sadd保证原子性：
```java
return jedis.sadd(getSetKey(task), request.getUrl()) > 0;
```
