### ISSUE TITLE
在爬取的时候，如果遇到网页需要加载IFRAME怎么办

### ISSUE THREAD

**Issue by lionest** [code4craft/webmagic#373]
打印爬取的结果里，显示页面需要加载完所有IFRAME后，再进行redirect到其他网页，但是用getRawText() 获取的源码里显示，当前浏览器不支持IFRAME，这个怎么处理？如果要加user_agent 应该在什么地方什么时候添加？谢谢

目标网页源码部分：
   `<iframe src="//acw.sciencedirect.com/SSOCore/update?utt=bdf26285073075179b7acd1406bfd29b51aaabf-dw9q">Your browser doesn't support iFrames!</iframe>`

**Comment by lionest** [comment]
擦，怎么自动转义了，用了代码的标签了啊

**Comment by wangshijun101** [comment]
可以将 iframe中src的部分add到Requests中，这样就可以了。

**Comment by itliuxing** [comment]
一楼回答有道理，不过你的iframe里面的内容肯定不一样，爬取数据后的处理稍微变化一下就OK了

**Comment by code4craft** [comment]
同意 @wangshijun101 ，iframe适合当做一个新页面去抓。
