### ISSUE TITLE
页面包含 “啰” 字时，出现乱码

### ISSUE THREAD

**Issue by flamw** [code4craft/webmagic#382]
爬http://dealer.autohome.com.cn/15772/news_76675248.html （<meta charset="gb2312">
）页面包含 “啰” 字 出现乱码（��），请问有什么解决方法呢？

**Comment by itliuxing** [comment]
不会吧，爬取的代码，发一份出来，看看

**Comment by flamw** [comment]
package com.dndc.api.crawler;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.springframework.web.servlet.tags.ThemeTag;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.dndc.api.domain.CrawlerInstance;

import us.codecraft.webmagic.Page;
import us.codecraft.webmagic.Site;
import us.codecraft.webmagic.Spider;
import us.codecraft.webmagic.processor.PageProcessor;
import us.codecraft.xsoup.Xsoup;

/**
 * @author huangfl <br>
 */
public class DealerCmsArticleCrawler implements PageProcessor {

	private Site site = Site.me().setSleepTime(3000).setTimeOut(60000).setDomain("dealer.autohome.com.cn/")
			.setUserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.65 Safari/537.31");;
	private static final  String URL_LIST = "http://dealer.autohome.com.cn/%s/informationList_c0_s0_p[1-5]{1}.html";
	private String dealerCode;
	private String mediaDealerId;
	private CrawlerInstance crawlerInstance;
	public DealerCmsArticleCrawler(){};
	public DealerCmsArticleCrawler(CrawlerInstance crawlerInstance, String dealerCode, String mediaDealerId) {

		this.crawlerInstance = crawlerInstance;
		this.dealerCode = dealerCode;
		this.mediaDealerId = mediaDealerId;
	}

	@Override
	public void process(Page page) {

		String real_url_list = String.format(URL_LIST, this.getMediaDealerId());
		Document document = Jsoup.parse(page.getHtml().toString());
		// 列表页
		if (page.getUrl().regex(real_url_list).match()) {
			List<String> list = Xsoup.compile("//div[@class='dealeron']//dl[@class='promot-dl new-dl']//a[1]/@href")
					.evaluate(document).list();
			page.addTargetRequests(list);

			page.addTargetRequests(page.getHtml().links().regex(real_url_list).all());

			// 文章页
		} else {

			String title = page.getHtml().xpath("//p[@class='title-text']/text()").get();
			String activityDate = Xsoup.compile("//p//span[@class='fn-right']/html()").evaluate(document).get();
			String activityType = Xsoup.compile("//p[@class='title-explain']//span[@class='explain-info'][2]/a/html()")
					.evaluate(document).get();
//			String content = Xsoup.compile("//div[@class='dealermain']//html()").evaluate(document).get();
			String content = Xsoup.select(document, "//div[@class='dealermain']|div[@class='inforcont-cont']//p[1]|div[@class='inforcont-cont']//p[2] ").get();
			System.out.println(content);
			try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			Map<String, Object> data = new HashMap<String, Object>();

			data.put("title", title);
			data.put("activityDate", activityDate);
			data.put("activityType", activityType);
			data.put("dealerCode", this.dealerCode);
			data.put("mediaDealerId", this.mediaDealerId);
			data.put("content", content);
			
			List<Map<String, Object>> datas = new ArrayList<Map<String, Object>>();

			datas.add(data);
			CrawlerVO vo = new CrawlerVO();
			vo.setCrawlerInstance(this.crawlerInstance);
			vo.setCrawlerPkData(this.dealerCode);
			vo.setCrawlerDatas((JSONArray) JSON.toJSON(datas));
			vo.setUrl(page.getUrl().toString());
			page.putField("data", vo);

		}
	}

	@Override
	public Site getSite() {
		return site;
	}

	public static void main(String[] args) throws IOException {
		/*String[] urls = { "http://dealer.autohome.com.cn/1732/informationList_c0_s0_p1.html" };
		String str = "<p>【信赖东风日产，选择东风南方】";
		System.out.println(str.length());
		String[] ids = { "13178", "1732" };*/
		Spider.create(new DealerCmsArticleCrawler(new CrawlerInstance(),"","15772")).addUrl("http://dealer.autohome.com.cn/15772/informationList_c0_s0_p1.html" ).run();
		/*for (String id : ids) {
		  String	url = MessageFormat.format("http://dealer.autohome.com.cn/{0}/informationList_c0_s0_p1.html", id);
			Spider.create(new DealerCmsArticleCrawler()).addUrl(url).run();
			System.out.println("******************+" + id);

		}*/

	}


	public String getDealerCode() {
		return dealerCode;
	}

	public void setDealerCode(String dealerCode) {
		this.dealerCode = dealerCode;
	}

	public String getMediaDealerId() {
		return mediaDealerId;
	}

	public void setMediaDealerId(String mediaDealerId) {
		this.mediaDealerId = mediaDealerId;
	}

	public CrawlerInstance getCrawlerInstance() {
		return crawlerInstance;
	}

	public void setCrawlerInstance(CrawlerInstance crawlerInstance) {
		this.crawlerInstance = crawlerInstance;
	}

}

**Comment by itliuxing** [comment]
这个网页  下载到得源码里面的时候，这个字符就是个乱码，但是浏览器加载的时候能够给适配好了
我用gb2312 和UTF-8  取到得页面那个字符均是乱码了，估计是页面使用了防爬虫的东西或者是有js在里面修改相应的数据，建议想想其他办法

**Comment by dyhack** [comment]
不是吧，我在线查看源代码不是乱码，浏览器编码是gbk。首先建议设置site的addsetcharset为gbk。然后在数据库连接中设置连接方式为gbk。
