### ISSUE TITLE
SeleniumDownloader对代理不支持的情况下设置代理服务会造成爬虫空指针错误

### ISSUE THREAD

**Issue by RishonLi** [code4craft/webmagic#386]
初步判断为代理配置的结构性问题
0.5.3代码中, 释放代理服务是在 Spider里做的, 而设置代理是在 HttpClientDownloader里.
这造成了Downloader如果不用代理,爬虫一定会出错.

SeleniumDownloader 在 0.5.2版本中没有对代理做配置项,所以使用中出现此BUG.

建议代理统一配置在 Spider中全局处理, Downloader中通过其它方式
比如request.getExtra(Request.PROXY)获取代理.

**Comment by code4craft** [comment]
0.7.0代理部分已经重构，现在proxy跟其他Downloader无关了，可以自己配置实现，故此bug实际上已修复。

**Comment by kiwi-field** [comment]
请问最新的0.7.4版本如何在SeleniumDownloader中指定代理
