### ISSUE TITLE
建议黄大大出个增量更新

### ISSUE THREAD

**Issue by dyhack** [code4craft/webmagic#390]
做项目的时候爬取数据，我解决增量更新的方式很简单粗暴，直接在url中插入主键。然后在数据库中，更新的时候，如果主键存在就直接不用更新了，目前水平有限。希望能够实现增量更新。

**Comment by code4craft** [comment]
增量更新跟场景还有关，可能不会做成内置功能，不过文档中的增量更新部分计划更新一下。
