### ISSUE TITLE
webmagic如果高效的抓取AJAX渲染后的页面数据

### ISSUE THREAD

**Issue by licaibo** [code4craft/webmagic#393]
看了官网的webmagic抓取AJAX渲染后的页面数据，有2中方法。
1、浏览器查看请求地址，然后找到json利用jsonPath进行获取
2、利用webmagic-Selenium方法，但是关于这方面的文档和介绍并不多。
除此之外还能有更好的支持嘛？

**Comment by Eliccc** [comment]
好想帮黄大答: 没有

**Comment by lcbbcl** [comment]
黄大好久没上线啊

**Comment by jsbd** [comment]
可以利用扩展项目中的phantomjs downloader [PhantomJSDownloader.java](https://raw.githubusercontent.com/code4craft/webmagic/master/webmagic-extension/src/main/java/us/codecraft/webmagic/downloader/PhantomJSDownloader.java)
@licaibo

**Comment by code4craft** [comment]
推荐方法1。
