### ISSUE TITLE
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by renhai** [code4craft/webmagic#396]
每次程序运行一段时间后总是抛出如下异常：
`org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:286)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:92)
        at us.codecraft.webmagic.Spider.processRequest(Spider.java:409)
        at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
        at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by code4craft** [comment]
连接池用满了，你开了多少线程？

**Comment by renhai** [comment]
5个线程

**Comment by code4craft** [comment]
按理说不会，HttpClient的连接数跟线程数是一致的，能不能贴个完整的demo？

**Comment by renhai** [comment]
多谢了
`package me.renhai.taurus.spider.task;

import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;

import com.jayway.jsonpath.Configuration;
import com.jayway.jsonpath.JsonPath;
import com.jayway.jsonpath.Option;
import com.jayway.jsonpath.ReadContext;

import us.codecraft.webmagic.Page;
import us.codecraft.webmagic.Site;
import us.codecraft.webmagic.Spider;
import us.codecraft.webmagic.pipeline.JsonFilePipeline;
import us.codecraft.webmagic.processor.PageProcessor;

public class RottenTomatoesProcessor implements PageProcessor {
	private static final Logger LOG = LoggerFactory.getLogger(RottenTomatoesProcessor.class);
	private Configuration conf = Configuration.defaultConfiguration().addOptions(Option.DEFAULT_PATH_LEAF_TO_NULL)
			.addOptions(Option.SUPPRESS_EXCEPTIONS);

	private Site site = Site.me().setDomain("rottentomatoes.com").setRetryTimes(5).setTimeOut(10000).setSleepTime(2000)
			.setUserAgent(
					"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.65 Safari/537.31");;

	@Override
	public void process(Page page) {
		if (page.getUrl().get().matches(".*/m/[^/]+/?$")) {
			String json = page.getHtml().xpath("//script[@id='jsonLdSchema']/html()").get();
			ReadContext ctx = JsonPath.parse(json, conf);
			page.putField("movieId", page.getHtml().$("meta[name=movieID]", "content").get());
			page.putField("title", ctx.read("$.name"));
			page.putField("director", joinString(ctx, "$.director[*]name"));
			page.putField("genre", joinString(ctx, "$.genre"));
			page.putField("author", joinString(ctx, "$.author[*].name"));
			page.putField("studio", ctx.read("$.productionCompany.name"));
			page.putField("year", ctx.read("$.datePublished"));
			page.putField("mpaaRating", ctx.read("$.contentRating"));
			page.putField("image", ctx.read("$.image"));

			page.putField("link", page.getUrl().toString());
			page.putField("criticConsensus",
					page.getHtml()
							.xpath("//div[@id='all-critics-numbers']//p[@class='critic_consensus superPageFontColor']/allText()")
							.get());
			page.putField("movieSynopsis", page.getHtml().xpath("//div[@id='movieSynopsis']/text()").get());
			page.putField("inTheaters", page.getHtml().xpath("//div[@class='info']")
					.$("div:containsOwn(In Theaters) + div > time", "datetime").get());
			page.putField("onDvd", page.getHtml().xpath("//div[@class='info']")
					.$("div:containsOwn(On DVD) + div > time", "datetime").get());
			page.putField("runTime", page.getHtml().xpath("//div[@class='info']")
					.$("div:containsOwn(Runtime) + div > time", "datetime").get());
			page.putField("timestamp", System.currentTimeMillis());
		} else {
			page.setSkip(true);
		}
		if (page.getStatusCode() == HttpStatus.OK.value()) {
			List<String> links = page.getHtml().links().all();
			for (String link : links) {
				if (!StringUtils.contains(link, "www.rottentomatoes.com/")) {
					continue;
				}
				if (StringUtils.contains(link, "www.rottentomatoes.com/tv/")) {
					continue;
				}
				int index = StringUtils.indexOf(link, "#");
				if (index != -1) {
					link = StringUtils.substring(link, 0, index);
				}
				link = StringUtils.removeEnd(link, "/");
				page.addTargetRequest(link);
			}
		}
	}

	private String joinString(ReadContext ctx, String path) {
		List<String> names = ctx.read(path);
		return StringUtils.join(names, ",");
	}




	@Override
	public Site getSite() {
		return site;
	}

	public static void main(String[] args) {
		Spider.create(new RottenTomatoesProcessor()).addPipeline(new JsonFilePipeline("/Users/andy/Downloads"))
				.addUrl("https://www.rottentomatoes.com/").thread(5).run();
	}

}
`

**Comment by code4craft** [comment]
我怀疑是没有及时归还连接，因为finally快之前是先returnProxy再归还连接。
先将`EntityUtils.consumeQuietly(httpResponse.getEntity());`放到finally块第一个位置看看。

**Comment by quandeng** [comment]
@code4craft  你好，我现在用的是webmagic 0.7.2的版本，但是让crawler跑几个小时后还是会碰到同样的异常
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
@renhai 你最后是怎么解决的?
