### ISSUE TITLE
第一步使用demo无法抓取 求解决

### ISSUE THREAD

**Issue by EdronCai** [code4craft/webmagic#398]
![image](https://cloud.githubusercontent.com/assets/18094334/20585407/f49e05b0-b235-11e6-9a45-bd86fc01ff0e.png)

![image](https://cloud.githubusercontent.com/assets/18094334/20585416/fcbaecf4-b235-11e6-9af3-037a708a22a8.png)

![image](https://cloud.githubusercontent.com/assets/18094334/20585524/c65c025a-b236-11e6-8789-0aa1167df0da.png)

以上是3个关键图片

**Comment by EdronCai** [comment]
结果保存不下来 求解答

**Comment by code4craft** [comment]
你没有配置log4j文件，建议配置一下之后看看日志。
另外你的Pipeline是JsonFile，最好是去看看有没有JsonFile。

**Comment by EdronCai** [comment]
@code4craft  谢谢 我已经处理好了

**Comment by EdronCai** [comment]
@code4craft  配置好日志之后 日志提示我 找不到一个目录下面的json文件 我手动创建文件后 就都正常下载数据了

**Comment by code4craft** [comment]
好的。
