### ISSUE TITLE
访问“https://www.beijing-hyundai.om.cn”网站，解析网页时报出java.io.EOFException

### ISSUE THREAD

**Issue by damaouxiang123** [code4craft/webmagic#409]
如下代码：
    protected String getContent(String charset, HttpResponse httpResponse) throws IOException {
        if (charset == null) {
            byte[] contentBytes = IOUtils.toByteArray(httpResponse.getEntity().getContent());
            String htmlCharset = getHtmlCharset(httpResponse, contentBytes);
            if (htmlCharset != null) {
                return new String(contentBytes, htmlCharset);
            } else {
                logger.warn("Charset autodetect failed, use {} as charset. Please specify charset in Site.setCharset()", Charset.defaultCharset());
                return new String(contentBytes);
            }
        } else {
            return IOUtils.toString(httpResponse.getEntity().getContent(), charset);
        }
    }
在IOUtils.toByteArray执行时，报出java.io.EOFException，求解决方案。多谢

**Comment by code4craft** [comment]
是每次都这样吗？看起来可能是网络比较慢没抓全。

**Comment by ningpp** [comment]
CloseableHttpClient httpClient = HttpClients.custom()
			.disableContentCompression()	
			.build();
禁用压缩就不报错了

**Comment by code4craft** [comment]
看起来是这个网站Gzip支持不当导致的？

**Comment by code4craft** [comment]
测试了一下，
```java
System.out.println(new SimpleHttpClient(Site.me()).get("https://www.beijing-hyundai.com.cn").getHtml());
```
可以获取到内容，是不是网站太慢？我关闭此issue了。
