### ISSUE TITLE
为什么QueueScheduler的pushWhenNoDuplicate()没有加synchronized呢

### ISSUE THREAD

**Issue by zhongshan365** [code4craft/webmagic#410]
本人刚开始研究没多久，希望不吝赐教。

QueueScheduler组合了BlockingQueue阻塞队列，但是并没有用到阻塞队列的功能，而只是用来简单的add（）和poll（）方法。
调用poll方法加了synchronized，为什么调用add方法却没有使用同步呢？请求队列多个线程都会往里添加，为什么不需要同步？

`public class QueueScheduler extends DuplicateRemovedScheduler implements MonitorableScheduler {

    private BlockingQueue<Request> queue = new LinkedBlockingQueue<Request>();
    @Override
    public void pushWhenNoDuplicate(Request request, Task task) {
        queue.add(request);//为什么没有加同步synchronized？
    }

    @Override
    public synchronized Request poll(Task task) {//这里加了synchronized
        return queue.poll();
    }

    @Override
    public int getLeftRequestsCount(Task task) {
        return queue.size();
    }

    @Override
    public int getTotalRequestsCount(Task task) {
        return getDuplicateRemover().getTotalRequestsCount(task);
    }
}`

**Comment by code4craft** [comment]
好问题，看代码这里的push应该是漏了。因为DuplicateRemover其实是不保证线程安全的，所以push应该是必须同步的。而poll的时候，其实BlockingQueue本身是线程安全的，反而就无所谓了。

**Comment by zhongshan365** [comment]
谢谢您的解答。
