### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by dmrzh** [code4craft/webmagic#417]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project webmagic-extension: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /webmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/monitor/SpiderMonitor.java:49: warning: no @throws for javax.management.JMException
[ERROR] public synchronized SpiderMonitor register(Spider... spiders) throws JMException {
[ERROR] ^
[ERROR] /webmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/utils/DoubleKeyMap.java:105: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR]  /webmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/handler/CompositePageProcessor.java:12: error: unknown tag: date
[ERROR] * @date 14-4-5
[ERROR] ^
[ERROR] /webmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/handler/SubPageProcessor.java:7: error: unknown tag: date
[ERROR] * @date 14-4-5
[ERROR] ^
[ERROR] /webmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/downloader/PhantomJSDownloader.java:40: warning: no description for @param
[ERROR] * @param phantomJsCommand
[ERROR] ^
[ERROR] /webmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/configurable/ExpressionType.java:5: error: unknown tag: date
[ERROR] * @date 14-4-5
[ERROR] ^
[ERROR] /webmagic/webmagic-extension/src/main/java/us/codecraft/webmagic/configurable/ExtractRule.java:10: error: unknown tag: date
[ERROR] * @date 14-4-5
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-8-openjdk/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/dmitry/projects/tmp/webmagic/webmagic-extension/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :webmagic-extension

**Comment by code4craft** [comment]
javadoc的问题，应该已经修复了。

**Comment by dmrzh** [comment]
javadoc -понятно, остальное нет
