### ISSUE TITLE
抓取https链接线程无法结束导致进程一直运行

### ISSUE THREAD

**Issue by cpaladin** [code4craft/webmagic#419]
发现在使用代理ip爬取https链接时，出现爬取线程无法结束一直处于runnable状态，导致最后整个程序无法结束的情况。通过jConsole查看runnable 线程的调用栈信息，类似这篇文章[http://zhoujinhuang.iteye.com/blog/2109067](http://zhoujinhuang.iteye.com/blog/2109067)
描述的，阻塞在SocketInputStream.socketRead0方法中。最后下载源码，临时在HttpClientGenerator.generateClient(...)中做了如下修改，不在出现问题。麻烦作者关注一下这个问题，谢谢
![_ 4fg w 91bnww 5i4 kj](https://cloud.githubusercontent.com/assets/6845769/21130350/c09d3922-c142-11e6-9db3-3a88c0817d90.png)

**Comment by code4craft** [comment]
赞！可以提个pull request吗？
