### ISSUE TITLE
xpath获取其他属性失败

### ISSUE THREAD

**Issue by kenti-lan** [code4craft/webmagic#425]
`<span property="v:genre">测试</span>`

使用xpath表达式 
`//span/[@property='v:genre']/allText() `
返回内容为空.

**Comment by code4craft** [comment]
改成`//span[@property='v:genre']/allText()`试试？

**Comment by kenti-lan** [comment]
对,粗心 加多了个斜杠

**Comment by code4craft** [comment]
1.
