### ISSUE TITLE
请教一下ZhihuPageProcessor

### ISSUE THREAD

**Issue by le0zh0u** [code4craft/webmagic#427]
在ZhihuPageProcessor的示例文件中，在执行之后是不是输出的是page中的**最后一个赞成数大于1000**的答案？

**Comment by code4craft** [comment]
是知乎精选里的内容，URL类似[https://www.zhihu.com/question/20592041/answer/135855960](https://www.zhihu.com/question/20592041/answer/135855960)，当然我们是讨论爬虫技术的，不用在意这些~

**Comment by le0zh0u** [comment]
恩恩。之前以为会将所有赞的数量大于1000的答案都存下来的😂，所以就想问一下，确认下。话说那知乎搜索页面的`更多`的部分该怎么爬取到呢

**Comment by jsbd** [comment]
@le0zh0u 更多那部分可能需要借助浏览器辅助了，用phantomjs，写脚本去解决，模拟人工点击
