### ISSUE TITLE
WebMagic-Avalon项目计划

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#43]
WebMagic-Avalon项目的目标是打造一个可配置、可管理的爬虫，以及一个可分享配置/脚本的平台，从而减少熟悉的开发者的开发量，并且让**不熟悉Java技术的人**也能简单的使用一个爬虫。
## ~~Part1:webmagic-scripts~~

目标：使得可以用简单脚本的方式编写爬虫，从而为一些常用场景提供可流通的脚本。
例如：我需要抓github的仓库数据，可以这样写一个脚本(javascript)：

[https://github.com/code4craft/webmagic/tree/master/webmagic-scripts](https://github.com/code4craft/webmagic/tree/master/webmagic-scripts)

这个功能目前实现了一部分，但最终结果仍在实验阶段。欢迎大家积极参与并提出意见。~~因为编写一个稳定的语言需要很多领域积累，后来决定先做后台。~~
## Part2:webmagic-pannel

一个集成了加载脚本、管理爬虫的后台。目前在开发中。
## ~~Part3:webmagic-market~~

一个可以分享、搜索和下载脚本的站点。计划中。
## 如何参与

webmagic目前由作者业余维护，仅仅为了分享和个人提高，没有任何盈利，也没有商业化打算。

欢迎以下几种形式的贡献：
1. 为webmagic项目本身提出改进意见，可以通过邮件组、qq、oschina或者在github提交issue(推荐)的方式。
2. 参与WebMagic-Avalon计划的建设讨论，包括产品设计、技术选型等，可以直接回复这个issue。
3. 参与webmagic代码开发，请fork一份代码，修改后提交pull request给我。请使用尽量新的版本，并说明修改内容。pull request接受后，我会将你加为committer，共同参与开发。

**Comment by warterWu** [comment]
没有看到针对多个任务同时运行的压力控制和集群调度的功能啊

**Comment by Medusar** [comment]
请教一下，您文中那样子的图是怎么画出来的呢

**Comment by gujiahong** [comment]
请教一下，您文中那样子的图是怎么画出来的呢

**Comment by zhouhao** [comment]
@gujiahong @Medusar 应该是这个工具吧：https://balsamiq.com/products/mockups/

**Comment by longfengfirst** [comment]
我是新手，正好跟进

**Comment by jeff-dong** [comment]
我可以提供JOB调度部分 :) 
https://github.com/jeff-dong/marble

**Comment by gsh199449** [comment]
我使用Webmagic内核写了一个爬虫的网页配置和爬虫管理界面,还包括数据存储与搜索 
[https://github.com/gsh199449/spider](https://github.com/gsh199449/spider)

**Comment by code4craft** [comment]
@gsh199449 必须赞！

**Comment by nvidhub** [comment]
和您一起学习

**Comment by john1533** [comment]
很不错的项目，希望能加入！

**Comment by casolxia** [comment]
不错不错

**Comment by garry1861** [comment]
我可以一起做，我正在使用这个项目，也在考虑做一个基于这个项目的管理。希望能一起。

**Comment by GaoPengTIM** [comment]
今天老板就让我一个人做一个这样的东西，我正在路上

**Comment by system777** [comment]
大牛，还在维护吗？我来自一家大型互联网电商公司，公司有这方面的投入，希望能跟您联系上。
不缺资源，希望能合作。QQ：77720370

**Comment by kinhn** [comment]
前来观望，祝作者成功

**Comment by windmap** [comment]
不错的，顶你一下，贡献无穷

**Comment by nununull** [comment]
前来膜拜大神

**Comment by uiaoo** [comment]
学习

**Comment by xiaorendetian** [comment]
进展如何了？

**Comment by iamlk** [comment]
太遗憾了，这个项目还是夭折了

**Comment by sutra** [comment]
> 太遗憾了，这个项目还是夭折了

关闭这个 issue 的原因应该是因为已经有第三方的实现了，没有必要再做重复的：
https://github.com/code4craft/webmagic/issues/43#issuecomment-262860518

**Comment by carl-don-it** [comment]
> 今天老板就让我一个人做一个这样的东西，我正在路上

做得怎么样了，我也有此需求

**Comment by banana-boy484** [comment]
毕业设计准备做一个分布式爬虫+web端管理+小程序展示,前来取经

**Comment by eagleli1990** [comment]
呵呵``  您的邮件已收到 ！！
