### ISSUE TITLE
代理需求征集和API改进

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#432]
之前的API设计并不是好用，想重新设计一套。

**Comment by virjar** [comment]
增加上线下线功能，IP一直失败到达一定程度就从IP池移除。IP数据少于一定程度自动引入IP。
IP切换方式似乎可以灵敏一点，失败越多罚时越重。

之前的IP池的确不好用，所以我又尝试设计IP池，部分代码也从webMagic那边抄过来的。目前我个人设计的IP池似乎已经达到了比较好的效果，http://git.oschina.net/virjar/proxyipcenter/blob/master/doc/client/design/README.md
链接是我个人的IP池的实现，主要是实现更好的根据优先级切换的效果。个人使用不错，所以分享出来，希望对webMagic新的代理API设计有些帮助

**Comment by jsbd** [comment]
＋1 @code4craft

**Comment by code4craft** [comment]
文档已修复。

**Comment by chenshao0594** [comment]
不是随机的选择一个代理  然后再加上这个时间的处理？

**Comment by kkkaaa2010** [comment]
SimpleProxyPool这个代理池例子每次都随机download页面都随机调取一个代理ip。那如果这个代理ip失效还会调用吗？而且代理池里的ip是固定的，不能动态添加代理吧。

**Comment by vicre** [comment]
http://webmagic.io/docs/zh/posts/ch4-basic-page-processor/proxy.html
poolHosts.add(new String[]{"102.102.102.102","8888"});
--> 0.6.1里面应该是 {"username","password","102.102.102.102","8888"}

**Comment by vicre** [comment]
@code4craft   there is an implementation on proxy pool-->
https://github.com/Stratehm/stratum-proxy

**Comment by code4craft** [comment]
@vicre 多谢，很强大的样子，API也写的很好，正是想要的。

**Comment by holy-silent** [comment]
webmagic当前的SimpleProxyPool中，传入的httpProxyList中，每个代理要求四个参数后两个参数是IP和PORT，前两个参数是干啥的呢？

**Comment by Sherler** [comment]
代理ip为域名时，报null错误，同一ip，账号不同时，无法作为不同代理进行使用

**Comment by code4craft** [comment]
@Sherler 有道理，不过同一IP不同账号，应该对外IP也是一样的吧？是不是意义不是很大呢？

**Comment by Sherler** [comment]
@code4craft 但是事实并非如此，我花钱买的代理，通过域名+用户名+密码登录，登陆后，允许每秒五次请求，每次请求对外的ip都不一样，多账户下可以允许每秒请求更多次。所以希望能解决一下仅通过ip标识的问题，说不定其它人也会遇到。

**Comment by code4craft** [comment]
@Sherler 挺有道理的，后面重构之后不会使用ip或者域名做去重了。

**Comment by code4craft** [comment]
最终API已经加入版本0.7.0。

## 代理支持

* 新的代理API`ProxyProvider`，支持自由扩展
* 默认实现SimpleProxyProvider是一个简单的round-robin实现，可以添加任意个数的代理。

```java
HttpClientDownloader httpClientDownloader = new HttpClientDownloader();
SimpleProxyProvider proxyProvider = SimpleProxyProvider.from(new Proxy("127.0.0.1", 1087), new Proxy("127.0.0.1", 1088));
httpClientDownloader.setProxyProvider(proxyProvider);
```

* 移除了Site上关于代理配置的setProxy等，代理设置统一到HttpClientDownloader里。
