### ISSUE TITLE
0.6.0 cookie空指针问题

### ISSUE THREAD

**Issue by dyq2013** [code4craft/webmagic#438]
当使用startUrls方法未设置setDomain的时候，携带cookie信息download方法会报空指针
![qq 20170113162019](https://cloud.githubusercontent.com/assets/13568375/21922901/13dd40f6-d9ac-11e6-9288-e71f5949291e.png)

**Comment by code4craft** [comment]
已解决，估计是0.6.0升级HttpClient导致的不兼容问题。

**Comment by dyq2013** [comment]
还有个bug可顺便解决 就是当响应体内容为空时，未设置setCharset时，download方法也会报空指针

**Comment by dyq2013** [comment]
![image](https://cloud.githubusercontent.com/assets/13568375/22180664/e668e87a-e0b1-11e6-8a4c-48cb4385fb7f.png)
像这种 响应头中不一定有conten-Type属性
