### ISSUE TITLE
Selectable.match()返回结果不对

### ISSUE THREAD

**Issue by Firedamp** [code4craft/webmagic#439]
page.getUrl.regex("xxxxx")返回的结果为一个有一个null元素的list
但是page.getUrl.regex("xxxxx").match()返回true

**Comment by code4craft** [comment]
能否提供一个例子？我这边没有复现。

**Comment by Firedamp** [comment]
PlainText pl = PlainText.create("https://www.douban.com/group/topic/12345/");

1   pl.regex("https://www\\.douban\\.com/group/\\w+/(a)?").get()   返回null

2   pl.regex("https://www\\.douban\\.com/group/\\w+/(a)?").match()   返回true

3   pl.regex("https://www\\.douban\\.com/group/\\w+/a?").get()   返回https://www.douban.com/group/topic/

**Comment by code4craft** [comment]
WebMagic默认返回group 1，所以1是没有结果的。
