### ISSUE TITLE
SubPageProcesser的具体例子

### ISSUE THREAD

**Issue by zhangmianhongni** [code4craft/webmagic#448]
列表-详细页面的捉取据闻能使用SubPageProcesser了，有没有具体的使用例子？

**Comment by shotdog** [comment]
@zhangmianhongni  这个 组合 processor 

> CompositePageProcessor

**Comment by buaanie** [comment]
我也比较感兴趣这个，看 @shotdog 提到的例子知道是怎么使用了，但是subpageprocessor的具体实现还是不知道该如何编写

**Comment by buaanie** [comment]
@zhangmianhongni 可以参考这个，具体其实具体实现上与if-else没有本质区别，只是耦合度更低了

**Comment by buaanie** [comment]
https://github.com/JiangWenqi/JD_Simple/blob/fa247dc65416d3d0005b6ac997a864099dbe0476/src/main/java/cn/edu/bistu/cs/crawler/JDSpider.java

**Comment by sutra** [comment]
可以参考 `us.codecraft.webmagic.example.PatternProcessorExample`
