### ISSUE TITLE
求助：关于需要切换UA才能继续访问目标网站接口数据

### ISSUE THREAD

**Issue by dyq2013** [code4craft/webmagic#449]
现发现目标网站有个接口不能一直用一个UA访问，故重写了HttpClientDownloader类getHttpClient方法（一个Request线程生成一个HttpClient对象）和HttpClientGenerator辅助类的generateClient方法（ua从传递进来的List<UA>参数中随机取），可又觉得这样改动也不是个最终方案，故想问下大师，除此之外还有没有别的什么办法，比如通过在Site中指定UA列表，传递某种UA使用策略

**Comment by xbynet** [comment]
个人觉得，可以通过在Request中增加UA配置选项来支持针对每个请求自定义UA。

**Comment by code4craft** [comment]
建议定期换一下UA，其实类似代理池一样搞个UA池也是挺好的思路。Request设置之前想过，能用是能用的，但是Request毕竟主要处理爬虫的数据信息，放这些感觉不是特别好。

**Comment by code4craft** [comment]
0.7.0开始可以设置Request级别Header了。
