### ISSUE TITLE
webmagic问题，内存越来越大，jmap显示为char[] 4G

### ISSUE THREAD

**Issue by zengfr** [code4craft/webmagic#450]
webmagic问题，内存越来越大，jmap显示为char[] 4G

测试例子:
package us.codecraft.webmagic.samples;

import java.util.ArrayList;
import java.util.List;

import us.codecraft.webmagic.Page;
import us.codecraft.webmagic.Site;
import us.codecraft.webmagic.Spider;
import us.codecraft.webmagic.pipeline.ConsolePipeline;
import us.codecraft.webmagic.processor.PageProcessor;
import us.codecraft.webmagic.scheduler.BloomFilterDuplicateRemover;
import us.codecraft.webmagic.scheduler.QueueScheduler;
import us.codecraft.webmagic.selector.Html;
import us.codecraft.webmagic.utils.UrlUtils;

public class SpilderPageProcessor implements PageProcessor {

	private Site site = Site.me().setCycleRetryTimes(2).setRetryTimes(2).setSleepTime(10).setTimeOut(3 * 60 * 1000)
			.setUserAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0")
			.addHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
			.addHeader("Accept-Language", "zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3").setCharset("UTF-8");

	@Override
	public void process(Page page) {
		List<String> relativeUrls = page.getHtml().xpath("//a/@href").all();
		List<String> relativeUrls2 = new ArrayList<String>();
		for (String url : relativeUrls) {
			String url2 = UrlUtils.canonicalizeUrl(url, page.getUrl().toString());
			url2 = addUrlValue(url2, "qq", "362505707");
			relativeUrls2.add(url2);
			url2 = null;
		}
		page.addTargetRequests(relativeUrls2);
		relativeUrls = null;
		relativeUrls2 = null;
		 
	}

	@Override
	public Site getSite() {
		return site;
	}

	/**
	 * 对url添加或追加某一属性，可处理编码化url
	 * 
	 * @param url
	 * @param value
	 *            属性值
	 * @param name
	 *            属性名
	 * @return
	 */
	public static String addUrlValue(String url, String name, String value) {
		if (url == null || url.isEmpty()) {
			return url;
		}

		String a = "";
		if (!url.contains("/")) {// 编码后的URL不可能存在/
			// 编码化url处理 %3F->? %3D->=
			if (url.contains("%3F") && !url.contains("%3D")) {
				a = "";
			} else if (url.contains("%3F") && url.contains("%3D")) {
				a = "%26";
			} else {
				a = "%3F";
			}
		} else {
			// 非编码化url处理
			if (url.contains("?") && !url.contains("=")) {// http://zjw.cn?
				a = "";
			} else if (url.contains("?") && url.contains("=")) {// http://zjw.cn?a=b
				a = "&";
			} else {
				a = "?";
			}
		}
		String newUrl=url += (a + name + "=" + value);
		a=null;name=null;value=null;
		return newUrl;
	}

	public static void main(String[] args) {
		Spider spider = Spider.create(new SpilderPageProcessor()).addUrl("http://www.oschina.net/")
				.addPipeline(new ConsolePipeline()).thread(33);

		spider.setScheduler(new QueueScheduler().setDuplicateRemover(new BloomFilterDuplicateRemover(10000000)) // 10000000是估计的页面数量
		);

		spider.run();

	}

}

**Comment by code4craft** [comment]
跑了多久了？char[]应该是字符串的底层存储，最可能的是url队列，但是也不排除html泄露了。
既然用了jmap，不妨看看到底是哪些地方引用了。

**Comment by zengfr** [comment]
建议改进队列  这种加url队列方式 内存太大了。  有其他方式吗？ 没看到示例。
page.addTargetRequests(relativeUrls2);

**Comment by code4craft** [comment]
队列是可以配置的，你可以用外部存储来做。spider.setScheduler()

**Comment by zengfr** [comment]
OK 已用redis  谢谢啦
