### ISSUE TITLE
对于html先用正则匹配，然后用xpath匹配抛出异常

### ISSUE THREAD

**Issue by 9527y** [code4craft/webmagic#453]
代码：
> page.getHtml().regex("<span class=\"v\"> 全部章节 </span>(.*?)").xpath("//span/a/@href")

异常：
`XPath can not apply to plain text. Please check whether you use a previous xpath with attribute select (/@href etc).`

目前看到PlainText 不支持xpath那么怎么才能使用呢？

**Comment by code4craft** [comment]
使用过正则匹配后就不能使用XPath抽取了，因为正则取出来的没有办法保证是Html，当做是是纯文本处理了。

**Comment by 9527y** [comment]
多谢指导

**Comment by dcriori** [comment]
那怎样解决呢?比如我想拿<a>中间的文本,使用"/a/text()"现在只能拿到 "领域驱动设计(Domain Driven Design)（转）" 这部分, 如:
<a href='xxx.xxxxx'>
          <em>DDD</em>领域驱动设计(Domain Driven Design)（转）
</a>
我是想先replace掉"<em>"和"</em>" 然后再取,但replace掉再用xpath,就报错了,情况应该和regax是一样的.
```
Selectable tmp = item.replace("<em>","").replace("</em>","");
return tmp.xpath("//div[@class='limit_width']/a/text()").get();
```
