### ISSUE TITLE
项目依赖Commons-Collections3.2.1存在反序列化漏洞隐患

### ISSUE THREAD

**Issue by longliantian** [code4craft/webmagic#456]
目前webmagic项目中依赖使用的Commons-Collections3.2.1存在严重的反序列化漏洞隐患，建议提高一个小版本到Commons-Collections3.2.2即可

**Comment by code4craft** [comment]
附上官方jira：
[https://issues.apache.org/jira/browse/COLLECTIONS-580](https://issues.apache.org/jira/browse/COLLECTIONS-580)
WebMagic本身没有使用反序列化API，不过考虑到适用方，还是升级了。
