### ISSUE TITLE
Site设置了userAgent,抓包发现userAgent参数扔为空

### ISSUE THREAD

**Issue by bygonetime** [code4craft/webmagic#466]
打扰大神了，最近使用webmagic做个爬虫小项目,发现Site设置了userAgent,抓包发现userAgent参数扔为空;
换一种方式设置:

`addHeader("User-Agent", "Mozilla/5.0 (X11; U; Linux x86_64; zh-CN; rv:1.9.2.10) Gecko/20100922 Ubuntu/10.10 (maverick) Firefox/3.6.10")`

这样就是可以的.
通过查看webmagic源码发现,在Site类中的setUserAgent方法之后,后续调用Site时,对该参数都未做处理,也未使用,导致请求头中userAgent仍为空;
是不是应该把userAgent添加到headers Map中?

另外:

`HttpUriRequest httpUriRequest = getHttpUriRequest(request, site, headers, proxyHost);//���������˴���

httpResponse = getHttpClient(site, proxy).execute(httpUriRequest);//getHttpClient�������˴�����`

我很好奇这两句注释是啥.......^_^

**Comment by bygonetime** [comment]
发现是自己代码的问题,设置参数的位置不对,我是在PageProcessor的process()方法中设置的参数,想要动态换useragent,抓包发现没有值;在getSite()方法中设置就没有问题了.
丢人现眼了....大神莫怪,框架很好用,框架很好用,框架很好用!!!

**Comment by code4craft** [comment]
注释的问题，你的开发环境是用的什么编码？

**Comment by bygonetime** [comment]
UTF8...
[https://github.com/code4craft/webmagic/blob/master/webmagic-core/src/main/java/us/codecraft/webmagic/downloader/HttpClientDownloader.java](url)
github上的也是乱的

**Comment by jsbd** [comment]
嗯，是的哦 @bygonetime 果然乱码的

**Comment by code4craft** [comment]
看了一下，我这里也是一样…16年的PR了，我先把这个注释删掉了。
