### ISSUE TITLE
添加代理池有bug？

### ISSUE THREAD

**Issue by feesx** [code4craft/webmagic#468]
["111.122.149.58","9999"]
SimpleProxyPool种的
 public void addProxy(String[]... httpProxyList) {
        isEnable = true;
        for (String[] s : httpProxyList) {
            try {
                if (allProxy.containsKey(s[2])) {
                    continue;
                }

这个s[2]拿不到数据报 Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2

**Comment by feesx** [comment]
List<String[]> poolHosts = new ArrayList<String[]>();
    poolHosts.add(new String[]{"101.101.101.101","8888"});
    poolHosts.add(new String[]{"102.102.102.102","8888"});
例子給的有问题，第三个参数是ip，第四个port

**Comment by feesx** [comment]
poolHosts.add(new String[]{"","","114.99.24.80","808"});
	    poolHosts.add(new String[]{"","","117.90.7.182","9000" });  这么设置拿不到东西

**Comment by code4craft** [comment]
是有问题，文档已修复，与重复，关闭了。#354
