### ISSUE TITLE
如果抓取需要登录的网站

### ISSUE THREAD

**Issue by woshihoujinxin** [code4craft/webmagic#469]
如果某个网站需要登录后抓取信息，或者抓取过程中需要输入验证码，并且还要返回抓取进度，这时候webmagic能解决么

**Comment by code4craft** [comment]
没有自动登录功能，但是你可以自己设置cookie，site.addCookie()就可以。

**Comment by hiliushuo** [comment]
您好，addCookie 与 SeleniumDownloader 同时使用的时候cookie无效是什么问题呢？
使用场景：要爬的目标页面是由js产生的，所以使用了SeleniumDownloader，然后要爬的页面还必须是登录的状态才能得到。。。

**Comment by code4craft** [comment]
SeleniumDownloader做的比较简单，不支持addCookie…建议自己扩展一下。

**Comment by hiliushuo** [comment]
好的，今天第一天学大神的框架，，，然后自己作死写了一个很复杂的demo
