### ISSUE TITLE
QueuedScheduler push时的竞争态条件

### ISSUE THREAD

**Issue by neverusedname** [code4craft/webmagic#470]
我大概看了一下QueuedScheduler，发现逻辑是如果不重或shouldReserve就放进一个LinkedQueue。如果多个线程同时放一个url，同时发现不重。将会放入一个url同时放入多次。这个是不是一个bug，我是渣渣，也不是很确定有没有这个问题。

**Comment by code4craft** [comment]
你好，这块很久不改忘记了，是这样的：`DuplicatedRemover.isDuplicate()`设计期望是一个“确认元素是否存在，不存在则添加”的原子操作，当然命名确实不是特别明显，看起来可能只是一个判断操作，所以造成了误会，包括可能后面的实现也未必考虑了这一点，不过`QueuedScheduler `这里这么处理是没问题的。
