### ISSUE TITLE
发放两个Intellij Open Source License

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#473]
参加JetBrains的OpenSource支持项目，申请了2个一年有效期的License，有用Intellij开发的朋友可以在下面留言，并留下你的邮箱，要求：为WebMagic提过issue或者commit过代码。

谢谢大家支持！

**Comment by jsbd** [comment]
撸主发福利了，顶一下 ＋1 @code4craft

**Comment by perfecking** [comment]
虽然对webmagic做过微不足道的commit，但是基本符合要求，哈哈

GitHub：perfecking
mail：pqing112358@hotmail.com<mailto:pqing112358@hotmail.com>



发自我的小米手机
在 Yihua Huang <notifications@github.com>，2017年3月2日 13:14写道：

参加JetBrains的OpenSource支持项目，申请了2个一年有效期的License，有用Intellij开发的朋友可以在下面留言，并留下你的邮箱，要求：为WebMagic提过issue或者commit过代码。

谢谢大家支持！
