### ISSUE TITLE
Request的方式为POST时，默认不再去重

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#484]
首先，POST不是幂等操作，所以理论上每次请求的结果都未必一样，所以原则上是没有办法做“去重”操作的。

其次，除了GET请求，其他Method都没有办法自动发现，一般都是手工构建出来的，使用者更应该自己去控制是否重复。

鉴于这些因素，考虑不再对POST和PATCH请求做去重。

| HTTP Method	| Idempotent	| Safe|
| :-------- | --------:| :--: |
| OPTIONS	| yes | yes
| GET	| yes | yes
| HEAD	| yes | yes
| PUT	| yes | no
| POST	| no	| no
| DELETE | yes | no
| PATCH	| no	| no

**Comment by xbynet** [comment]
问题存在很久了，这个必须点赞啊。

**Comment by lockbur** [comment]
其实POST抓取去重，我觉得没必要那么麻烦，你在url的后面添加一个UUID的参数即可。如：
`Request request = new Request("http://evs.worldunion.cn/Evaluation/GetConstructionList?" + UUID.randomUUID());`

**Comment by wangye8899** [comment]
到我觉得这样不行，你加了全局标识符，链接不就被改了吗？

**Comment by wangye8899** [comment]
那么请问如何重写push方法啊，没有头绪

**Comment by xiekongye** [comment]
感觉可以参考WebCollector的一种实现：自定义一个url的key，允许使用方去决定post请求的唯一标识
