### ISSUE TITLE
fastjson 远程代码执行漏洞

### ISSUE THREAD

**Issue by thinkermao** [code4craft/webmagic#489]
[[重要通知] 【安全预警】关于fastjson远程代码执行漏洞预警 ](http://bbs.qcloud.com/thread-27624-1-1.html)

> fastjson近日曝出代码执行漏洞，当用户提交一个精心构造的恶意的序列化数据到服务器端时，fastjson在反序列化时存在漏洞，可导致远程任意代码执行漏洞。影响版本： 1.2.24及之前版本

**Comment by code4craft** [comment]
已升级，会随0.6.2发布。
