### ISSUE TITLE
爬取新浪首页新闻的时候会出现Cookie rejected

### ISSUE THREAD

**Issue by xuedygaga** [code4craft/webmagic#499]
以下为部分日志：
 [INFO][pool-1-thread-2][2017-03-22 11:39:24][us.codecraft.webmagic.downloader.HttpClientDownloader] - downloading page http://db.auto.sina.com.cn/list-3-2-0-0-0-0-0-0-9-0-1.html
  [INFO][pool-1-thread-5][2017-03-22 11:39:24][us.codecraft.webmagic.downloader.HttpClientDownloader] - downloading page http://db.auto.sina.com.cn/list-0-5-0-0-0-0-0-0-9-0-1.html
  [WARN][pool-1-thread-2][2017-03-22 11:39:25][org.apache.http.client.protocol.ResponseProcessCookies] - Cookie rejected [JSESSIONID="476FC21780F71051902EEAFA2B6D094E", version:0, domain:db.auto.sina.com.cn, path:/car, expiry:null] Illegal 'path' attribute "/car". Path of origin: "/list-3-2-0-0-0-0-0-0-9-0-1.html"
  [WARN][pool-1-thread-5][2017-03-22 11:39:25][org.apache.http.client.protocol.ResponseProcessCookies] - Cookie rejected [JSESSIONID="210365C666C710319F1A26324E511B69", version:0, domain:db.auto.sina.com.cn, path:/car, expiry:null] Illegal 'path' attribute "/car". Path of origin: "/list-0-5-0-0-0-0-0-0-9-0-1.html"

**Comment by code4craft** [comment]
这个报错提示看起来是其他/car开始的页面设置了cookie，应该不影响结果。
HttpClient会存储response cookie，所以这里请求报错了。
