### ISSUE TITLE
ProxyPool类无法继承扩展

### ISSUE THREAD

**Issue by wjmzmmd** [code4craft/webmagic#503]
Proxy的构造方法是包可见的，扩展ProxyPool涉及到new Proxy()初始化会编译不通过。这hin尴尬😅

**Comment by code4craft** [comment]
最新master代码已经修改了，可以用源码编译。
不过代理这部分在下一个版本(0.7.0)会做比较大的改动，有什么好的扩展方式可以回复一下~

**Comment by code4craft** [comment]
0.7.0已发布，关闭此issue。
