### ISSUE TITLE
SimpleProxyPool的proxy失败次数20会不会太大啦

### ISSUE THREAD

**Issue by wjmzmmd** [code4craft/webmagic#504]
SimpleProxyPool.returnProxyPool方法中对failureTimes做的判断是<20不移除，而且这个知是写死硬编码的。感觉当代理大部分是免费当时候，可靠性不高会大量重试，造成资源浪费，最主要是爬取时间太长。

**Comment by code4craft** [comment]
有道理，正在重构代理部分，应该可配置失败间隔。
