### ISSUE TITLE
爬取结果后保存到数据库并返回给前台，这该怎么处理？

### ISSUE THREAD

**Issue by vosonwang** [code4craft/webmagic#506]
webmagic爬取结果要返回给前台一份，是只能在pipline保存到mysql后，再去mysql中取出来给到前台吗？有没有pipline保存一个结果集，然后分别返回前台，并保存后台的方法？

不吝赐教，🙏

**Comment by code4craft** [comment]
建议自己保存到mysql，再在前台读取，WebMagic支持有做过单个阻塞调用的尝试，不过因为之前所有的设计都是后台多线程的模式，所以阻塞会有些效率问题。
后面的版本可能会优化这个功能。
