### ISSUE TITLE
0.6.1版本 日志信息出现WARN信息

### ISSUE THREAD

**Issue by goupan1996** [code4craft/webmagic#507]
@code4craft 
黄大大 我更新为0.6.1版本后程序可以跑，但是出现下面的WARN
在网上查了下，说的是要加一行代码什么的？不知道是我一个人遇到这种情况了吗？
17-03-26 19:40:46,765 WARN  org.apache.http.client.protocol.ResponseProcessCookies(ResponseProcessCookies.java:129) ## Invalid cookie header: "Set-Cookie: ncbi_sid=CE8E2FB38D7A8A31_0040SID; domain=.nih.gov; path=/; expires=Mon, 26 Mar 2018 11:40:19 GMT". Invalid 'expires' attribute: Mon, 26 Mar 2018 11:40:19 GMT
17-03-26 19:40:46,766 WARN  org.apache.http.client.protocol.ResponseProcessCookies(ResponseProcessCookies.java:129) ## Invalid cookie header: "Set-Cookie: WebEnv=16U1kqV3qNpHL3GrD46xGkUKFCwvbwkTLAnWhxuHyILITP4RqZI4tAXqe8zdnoarQ0Rgv_nbmY-6y1O6NKDyCybuRGOVrCDCuHmQu%40CE8E2FB38D7A8A31_0040SID; domain=.nlm.nih.gov; path=/; expires=Sun, 26 Mar 2017 19:40:19 GMT". Invalid 'expires' attribute: Sun, 26 Mar 2017 19:40:19 GMT

**Comment by somedaygoupan** [comment]
我看了下http报错的代码  在org.apache.http.client.protocol包下面的ResponseProcessCookies类的129行
但看不太懂，也不知道到底是哪儿出错了。程序也没做cookies相关处理。

**Comment by code4craft** [comment]
看了一下，参考链接[http://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api](http://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api)。
将`.setCookieSpec(CookieSpecs.BEST_MATCH);`改成了`.setCookieSpec(CookieSpecs.STANDARD)`。

**Comment by gemmax** [comment]
+1

**Comment by somedaygoupan** [comment]
恩 这样确实可以解决  谢谢黄大了 @code4craft
