### ISSUE TITLE
为什么href中的内容变成空了

### ISSUE THREAD

**Issue by xwlcn** [code4craft/webmagic#509]
比如html中有个
``
<a href="magnet:?xt=urn:btih:a779a79a2b76dd4fe50c19db4a119f7611ba5fce&dn=Blood.Ties.2013.BDRemux.1080p-MediaClub.mkv&tr=http%3A%2F%2Fhot-torrent.org%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=http%3A%2F%2Fretracker.local%2Fannounce" class="btn  btn-primary btn-sm">
``
无论用正则还是xpath获取出它的href都是空，获取outerHtml发现变成了
``
<a href="" class="btn  btn-primary btn-sm">
``
程序内部到底做了什么处理？

**Comment by code4craft** [comment]
做了链接绝对地址的处理，后面应该兼容一下其他协议。
