### ISSUE TITLE
请教一下，有什么方法可以获取到像谷歌开发者工具那样JS动态加载后的网页源码内容

### ISSUE THREAD

**Issue by closertb** [code4craft/webmagic#510]
最近才接触爬虫，这两天没事，在家里试用了一下大神写的超级蜘蛛，但是发现获取到的网页是服务器直接发过来，没有经过JS动态加载过的的原始网页，鉴于现在这种前端越来越组件化的开发方式，怎样去修改爬虫的方式获取像谷歌开发者工具获取到的那种JS动态加载后的完整网页内容

**Comment by code4craft** [comment]
可以看看webmagic-selenium项目，用模拟浏览器渲染的方式来做。

**Comment by closertb** [comment]
嗯，自己百度了，有模拟浏览器的方法，也有研究网页请求的，寻找AJAX请求的网址，然后直接获取
