### ISSUE TITLE
httpclient编码识别BUG

### ISSUE THREAD

**Issue by zfoxzero** [code4craft/webmagic#516]
> 
       charset = UrlUtils.getCharset(contentType);
        if (StringUtils.isNotBlank(contentType)) {
            logger.debug("Auto get charset: {}", charset);
            return charset;
        }

webmagic\webmagic-core\src\main\java\us\codecraft\webmagic\utils\CharsetUtils.java
判断语句不对，导致编码识别失效

**Comment by xbynet** [comment]
咋俩在群里讨论的问题：这里提了PR： https://github.com/code4craft/webmagic/pull/513/commits/c93a8a27227defa82788783ca012e60dbd2a5014  
希望能够合并 @code4craft
