### ISSUE TITLE
us.codecraft.webmagic.Page 的 getHtml() 方法问题

### ISSUE THREAD

**Issue by GZhY** [code4craft/webmagic#517]
@code4craft 作者您好, 最近使用webmagic时发现一个小问题, 问题如下: 
对于us.codecraft.webmagic.Page 的 getHtml() 方法, 项目中实现是这样的
``` java
    public Html getHtml() {
        if (html == null) {
            html = new Html(UrlUtils.fixAllRelativeHrefs(rawText, request.getUrl()));
        }
        return html;
    }
```
这样的实现将`<a>`标签的的`相对href`改成了`绝对href`但是对于`<img>`标签并未修改, 获取`<img>`中`src`的`绝对href`时就会出现bug.  
为什么不直接使用Jsoup.parse(String html, String baseUri)方法 生成document传给new Html()呢?
而且我看到Html类是含有这个Html(Document document)构造函数的.

**Comment by code4craft** [comment]
好主意！主要是UrlUtils.fixAllRelativeHrefs这个方法实现在引入Jsoup之前，可以测试一下Jsoup自带的替换功能。

**Comment by GZhY** [comment]
@code4craft 谢谢黄大的回复, 晚上我来测试一下, 没问题的话我再提PR

**Comment by GZhY** [comment]
已经PR了，实现前考虑过两种修复的方法：  
1.  PR这种方式，将document的href和src属性都改成了绝对路径
2. 同Jsoup的采取的方式，保留原始的document，仅设置baseUri。我觉得这样方式优点是类似懒汉模式，用到绝对路径的时候才计算绝对路径；缺点是使用XPath语法好像不能获得绝对路径(对XPath语法了解的不多，所以只能是好像)。如果XPath不能获得绝对路径的话，我们倒是可以给XPath补充相应的语法，如@abs:href表示获得绝对路径，并修改XSoup让其支持该语法，但这样修改显然要复杂的多。

所以我想向黄大请教一下，您认为哪种方式好一点，或者有没有更好的解决方式？

**Comment by code4craft** [comment]
review了你的PR，其实我的想法是：
Html对象本身也是封装了Jsoup的Document，如果Jsoup本身就提供了这个功能，那么提前转换为绝对路径就没有必要了。毕竟parse Html是有消耗的（可以做个测试，我认为比纯正则替换要慢很多），按照PR的方式一个页面会需要parse两次。

**Comment by GZhY** [comment]
刚看完了黄大的回复和PR， 既然Xpath是支持`@abs:href 获得绝对路径`， 那无论是因为效率问题还是原始信息的保留，我也认为这样都是更好的方式。 但是我上次更改代码的时发现调用UrlUtils.fixAllRelativeHrefs的地方不止一处，PR523没有全部修改，这个issue先关了， 洗漱后我在新版本的基础上再稍作修复一下。

**Comment by code4craft** [comment]
HttpClient部分我做了一些重构，可能你没看到。最新修改我刚刚合并[PR 524](https://github.com/code4craft/webmagic/pull/524)。

**Comment by GZhY** [comment]
赞！ 这就更新下来看看
