### ISSUE TITLE
JS渲染的内容webmagic能爬虫到吗？

### ISSUE THREAD

**Issue by xmt1139057136** [code4craft/webmagic#532]
大家有没有发现之前我们写的爬虫都有一个共性，就是只能爬取单纯的html代码，如果页面是JS渲染的该怎么办呢？
例如访问百度页面的控制台下的内容：

> 一张网页，要经历怎样的过程，才能抵达用户面前？
一位新人，要经历怎样的成长，才能站在技术之巅？
探寻这里的秘密；
体验这里的挑战；
成为这里的主人；
加入百度，加入网页搜索，你，可以影响世界。
请将简历发送至 %c ps_recruiter@baidu.com（ 邮件标题请以“姓名-应聘XX职位-来自console”命名） color:red
职位介绍：http://www.xttblog.com
百度一下，你就知道

像这些JS渲染的内容webmagic能爬虫到吗？

**Comment by kknono** [comment]
selenium 模块，但感觉代码不能用了

**Comment by xyhxiayuhang** [comment]
我也感觉代码有问题

**Comment by code4craft** [comment]
selenium有升级，导致新版本不能用了，0.7.1会集中修复。

**Comment by code4craft** [comment]
看了一下，之前有个类似问题 #475 ，在0.7.0中已经解决，但是没有相关文档说明，回头补充一下文档。
