### ISSUE TITLE
提供ProxyProvider的一些内置实现

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#535]
因为将之前的ProxyPool重构了，所以需要提供一些默认的ProxyProvider实现。

1. 单个或多个代理的，用轮询形式提供。
2. 能够能够响应下载失败的情况，并增加重试时间的。
3. 加入代理心跳机制。

**Comment by code4craft** [comment]
新开了一个issue #579 ，此issue关闭。

**Comment by lidada** [comment]
哈喽，请教个问题。我在用新的代理APIProxyProvider设置代理时遇到了个问题。
我倒入的是 `<artifactId>webmagic-core</artifactId>
		    <version>0.7.1</version>`，导入jar包后，我检查了一下jar里的HttpClientDownloader中是有setProxyProvider方法的。但是在我的爬虫类中用setProxyProvider时，eclipse就会报错，需让我在HttpClientDownloader创建个setProxyProvider（），我用ctrl+鼠标追了一下HttpClientDownloader，发现HttpClientDownloader中确实没有setProxyProvider（），请问这是什么原因导致的，有点懵啊！

**Comment by lidada** [comment]
教主，搞定了，谢谢！

**Comment by KeozenEric** [comment]
楼上的问题怎么解决的呀

**Comment by wangtengke** [comment]
@lidada @KeozenEric  我也出现了这个问题 请问你们是怎么解决的
