### ISSUE TITLE
自定义的一些pipeline 都不生效是为什么呢？

### ISSUE THREAD

**Issue by wuxiongliu1** [code4craft/webmagic#538]
您好，自己定义的一些pipeline，实现了Pipeline接口，然后也add到Pipeline中了，但是没有生效是为什么呢？

**Comment by code4craft** [comment]
可能是数据不全？提问最好附加代码以便排查。

**Comment by wuxiongliu1** [comment]
现在编写的pipeline生效了。谢谢了

**Comment by noseparte** [comment]
`public static void main(String[] args) {
        Spider.create(new NationalGeographyPageProcessor())
                .addUrl("http://www.dili360.com/travel/sight/")
                .addPipeline(new NationalGeographyPipeline())
//                .addPipeline(new JsonFilePipeline("D:\\data\\webmagic\\"))
                .thread(5)
                .run();
    }`

SpringBoot集成webmagic 0.6.1 抓取不到数据  JsonFilePipeline为官方提供，NationalGeographyPipeline为自定义的
