### ISSUE TITLE
建议升级一下JsonPath版本

### ISSUE THREAD

**Issue by xbynet** [code4craft/webmagic#540]
webmagic使用的[json-path](https://github.com/json-path/JsonPath)版本为0.8,而其最新版本已经为2.2.0了，昨天试了下，有些特性webmagic无法使用，比如$..book.length()（虽然有替代方案$..book[*].title获取全部，然后再取返回list的size。）

**Comment by code4craft** [comment]
之前调研过新版xpath，跟旧版有部分行为不一致，所以没有升级。
长远来看还是要升级的，加入到todo里了。

**Comment by code4craft** [comment]
升级计划已计入 #606
