### ISSUE TITLE
将页面的url放到队列中，支持默认去重复么？

### ISSUE THREAD

**Issue by wuxiongliu1** [code4craft/webmagic#541]
您好，现在遇到这样一个问题，比如说访问到一个页面，然后将该页面的url全部放入到待处理队列中；那访问两一个页面的时候，里面的url和前面的有重复，那在调用addTargetRequest的时候，支持自动去重复吗？我在日志中看到，有重复对一个url页面的执行日志输出，这个是什么问题呢?

**Comment by linbihangithub** [comment]
您好，我在阅读源码的过程中发现了DuplicateRemovedScheduler这个类，在启动爬虫的时候通过setScheduler(new DuplicateRemovedScheduler())应该就可以去重（使用DuplicateRemovedScheduler及其子类都应该是可以的）。

**Comment by code4craft** [comment]
@linbihangithub 正解，会自动去重。
