### ISSUE TITLE
优酷预告片ajax拼接问题

### ISSUE THREAD

**Issue by lingzgit** [code4craft/webmagic#542]
遇到一个棘手的问题 这是优酷预告片评论的ajax请求
http://p.comments.youku.com/ycp/comment/pc/commentList?jsoncallback=n_commentList&app=100-DDwODVkv&objectId=456858085&objectType=1&listType=0&currentPage=2&pageSize=30&sign=3cc0e1581e643e5f1573c9f99bd57f18&time=1492643950
其他字段容易分析和获取 其中有一个sign字段是经过加密的 
请问这种情况要如何处理？
谢谢

**Comment by lingzgit** [comment]
selenium方式加载太慢 基本放弃 是否有其他的方式？

**Comment by code4craft** [comment]
自己写加密方式，可以考虑嵌一段js代码…

**Comment by lingzgit** [comment]
谢谢～我去研究下js。
