### ISSUE TITLE
求个指导：与spring结合的项目中，通过接口访问触发在线爬虫，在线返回爬虫数据。如何实现？

### ISSUE THREAD

**Issue by Dorllen** [code4craft/webmagic#543]
我想是否最好是写一个pipeline，用来接收数据并返回到控制器...但是我对pipeline如何返回数据，没有好的头绪思路。能否有人指点一二。谢谢！

**Comment by eoekun** [comment]
如果是获取所有的结果,可以在自定义的pipeline构造中初始化一个List,有新的process的时候add进去,run完成返回list到前台即可.
若是想有一条process就返回到前台,建议使用websocket,在pipeline中向前台推送

**Comment by Dorllen** [comment]
谢谢你的帮助。对我很有帮助！ 我想在外部开个java.utils.current.Exectors线程池，将请求做成多线程的怎么样？ 线程是提高爬取速度吗？我对这个有困惑！ 我现在设置了线程访问也是3s一个解析，最慢7秒返回数据，感觉没差别，有好的建议吗？

**Comment by code4craft** [comment]
如果对方页面特别慢的话，提高线程数会有比较大的提升。
