### ISSUE TITLE
redis 中获取 post 类型的 request 报错

### ISSUE THREAD

**Issue by i37oC** [code4craft/webmagic#544]
Request{url='https://www.facebook.com/ajax/growth/friend_browser/checkbox.php?dpr=1134867026559159', method='POST', extras={nameValuePair=[{"name":"__a","value":"1"},{"name":"network_context","value":"1"},{"name":"__user","value":"100015592750268"},{"name":"fb_dtsg","value":"AQHudIngKalc:AQFujVWTcZL-"},{"name":"big_pics","value":"1"},{"name":"work_ids[0]","value":"134867026559159"}], statusCode=0}, priority=0} error
java.lang.ClassCastException: com.alibaba.fastjson.JSONArray cannot be cast to [Lorg.apache.http.NameValuePair;
	at us.codecraft.webmagic.downloader.HttpClientDownloader.selectRequestMethod(HttpClientDownloader.java:173)

我的测试代码如下
Object o = request.getExtra("nameValuePair");
NameValuePair[] nameValuePair = (NameValuePair[]) o;
如果从redis中获取到的request 其中nameValuePair的值为 JSONARRAY 不能转为 NameValuePair。
在 0.6.2-SNAPSHOT 可以使用 Request 的param 设值，就没有这个问题了。
谢谢！

**Comment by code4craft** [comment]
是的，NameValuePair无法json化，是已知问题，在最新版会修复。
