### ISSUE TITLE
jsonpath获取不到的时候返回的是plainText类型的“null”，而不是纯null

### ISSUE THREAD

**Issue by xuedygaga** [code4craft/webmagic#546]
`{
data: [ ]
}`

如果如上方的返回json的jsonpath($.data[*])的结果是plainText类型的“null”，我觉得应该返回纯null。

protected Selectable selectList(Selector selector, List<String> strings) {
        List<String> results = new ArrayList<String>();
        for (String string : strings) {
            List<String> result = selector.selectList(string);
            results.addAll(result);
        }
        return new PlainText(results);//我觉得这里是不是要先判断一下
    }

**Comment by code4craft** [comment]
嗯，有道理，应该修一下。

**Comment by xuedygaga** [comment]
用regex要是匹配不到也是这样，都用到了上方的代码。

**Comment by code4craft** [comment]
之前看成是JsonPath的bug了。

仔细看了一下问题，这里应该是返回Selectable，内容是空，没错的。`Selectable.get()`出来也是null。
因为Selectable的内容为空和本身为空是两种概念，为了API能够顺利使用所以不会将Selectable设置成空。如果要判断内容是否存在可以使用Selectable.isMatch()判断。
