### ISSUE TITLE
PageProcessor里面怎么有效的更加自己的条件比如新闻Id 判断停止任务呢？

### ISSUE THREAD

**Issue by lidaoyang** [code4craft/webmagic#549]
PageProcessor里面怎么有效的更加自己的条件比如新闻Id 判断停止任务呢？
在下面方法里面怎么停止任务呢？
 public void process(Page page) {
        //列表页
        if (page.getUrl().regex(URL_LIST).match()) {
        	if (isFlag) {
        		spider.stop();
			}else{
				page.addTargetRequests(page.getHtml().xpath("//div[@class=\"list-con\"]").links().regex(URL_GET).all());
	            page.addTargetRequests(page.getHtml().links().regex(URL_LIST).all());
			}
        }
}

**Comment by code4craft** [comment]
WebMagic的设计是爬完所有加入的request即停止，没有在PageProcessor直接停止的方法。

**Comment by lidaoyang** [comment]
那个stop方法是干嘛用的？

发自我的 iPad

**Comment by code4craft** [comment]
spider.stop之前是用于在外部需要停止爬虫时使用，所以PageProcessor里面是不持有这个对象的。

**Comment by lidaoyang** [comment]
外部没有什么场景要用到stop的

发自我的 iPad

**Comment by code4craft** [comment]
比如实例shutdown的时候…当初的设计跟Spring的context destroy是一样的。
我认为在PageProcessor中停止爬虫是一个不好的做法，PageProcessor应该是一个单纯的处理逻辑，它跟爬虫的调度、执行顺序应该是无关的。

**Comment by lidaoyang** [comment]
对了，我发现tomcat服务器停止后，那个爬虫任务会一直执行，怎么能让它它停止呢？

发自我的 iPad

**Comment by lidaoyang** [comment]
你好！
你上次说在PageProcessor不支持直接停止，把url抓玩后就会自动停止，然后我把processor里的stop都去掉了，但是在抓取一段时间后就不会抓了，日志里面打印了Connection manager is shutting down ，是不是不会自己停止啊？
下面时我的方法
MySpider.create(new ZqTimeNewsPageProcessor(news_id, stockMap))
				.addUrl("http://company.stcn.com/gsxw/1.shtml")
				.addPipeline(newsDBPipeline).setExitWhenComplete(true)
				.thread(2).run();

**Comment by lidaoyang** [comment]
我这边要同时抓好多网站的新闻，可以说一下怎么使用webmagic好吗？
万分感谢！！

**Comment by perfecking** [comment]
RTFM.



发自我的小米手机
在 lidaoyang <notifications@github.com>，2017年5月8日 22:45写道：

我这边要同时抓好多网站的新闻，可以说一下怎么使用webmagic好吗？
万分感谢！！
