### ISSUE TITLE
如何判断一次爬虫已经结束了？

### ISSUE THREAD

**Issue by wuxiongliu1** [code4craft/webmagic#552]
运行中的爬虫，如何判断其已经结束了爬取呢？

**Comment by woocoder** [comment]
不知你说的是程序如何判断爬虫状态，还是工程师如何判断爬取结束呢？

**Comment by wuxiongliu1** [comment]
我还是根据作者说的jmx方法，去判断该spider的状态是停止还是运行中的。

**Comment by woocoder** [comment]
我也是这么方式，目前我是爬虫状态、通过线程数、成功页面数量、总页面数判断是否结束的。如果还有其他的需求，可以通过扩展SpiderStatusMXBean来实现更多监控功能。

**Comment by wuxiongliu1** [comment]
有没有一种方法，在爬虫自己结束的时候，记录一条结束日志？

**Comment by code4craft** [comment]
@wuxiongliu1 可以，已加。

**Comment by Mr-LiuDC** [comment]
请问有判断爬虫结束的例子吗？`SpiderStatusMXBean` 依赖于 JConsole查看爬虫状态，在代码中怎样判断爬虫结束了呢？
