### ISSUE TITLE
6.1.3 将结果保存到MySQL中用java模式入库相关问题

### ISSUE THREAD

**Issue by oscloudtop** [code4craft/webmagic#554]
6.1.3 将结果保存到MySQL中，老师你是用的注解模式，这个在用ssm框架保存到数据库是没问题的，但是如果不用注解模式，用纯java代码，则在自定义Pipeline类中无法实现依赖注入，这个问题困惑了2天了，今天在oschina上看到的解决办法，是个可行的办法，但是感觉不好，解决办法网址：https://www.oschina.net/question/2545583_2180511

请老师改进改进

**Comment by code4craft** [comment]
终于看明白了，我自己的做法是将Pipeline配置成Spring的Bean。WebMagic中所有组件都是可以以单例的形式，作为Spring的Bean存在的。
