### ISSUE TITLE
关于xpath抽取一些没有标签的文本内容的问题

### ISSUE THREAD

**Issue by zjutkz** [code4craft/webmagic#555]
下面是一段简单的代码:
```
<body>
 <p>First First First</p>
 Second Second Second
 <p>Third Third Third</p>
 Fourth Fourth Fourth
</body>
```
我想抽取Second Second Second和Fourth Fourth Fourth，也就是返回一个List<String>。
直接用了xpath匹配.xpath("//body/text()").all()，但是返回的结果是一个String: "Second Second Second  Fourth Fourth Fourth"，请问这是为什么呢？

**Comment by code4craft** [comment]
`/text()`的定义是获取该元素的所有text，会做累加，所以不会返回list。这个情况你可能需要用Jsoup的visitor来写。
