### ISSUE TITLE
us.codecraft.webmagic.downloader.selenium.SeleniumDownloader包如何导入

### ISSUE THREAD

**Issue by Danawill** [code4craft/webmagic#558]
![image](https://cloud.githubusercontent.com/assets/7477906/25731750/b8f5b0c4-317b-11e7-97a4-049b97c96221.png)

为什么上面的类都可以导入，selenium.SeleniumDownloader为什么无法导入

**Comment by code4craft** [comment]
SeleniumDownloader在webmagic-selenium包里。
