### ISSUE TITLE
[BUG] 默认取捕获组1引出的问题

### ISSUE THREAD

**Issue by zhuyuesut** [code4craft/webmagic#559]
几天前改项目Bug，发现RegexSelector的某处默认选择了捕获组1，随之发现判断捕获组数量的方案有问题，从开始的只处理非捕获组的情况，渐渐改善成可以处理零宽度断言，到最后可以处理模式修饰符、注释等，本来尝试了通过反射去做的，最后选择了使用groupCount方法去取得捕获组数量。
这种方案虽然解决了捕获组数量的正确计算问题，但是此处还是存在bug，由于添加捕获组的方式是在正则表达式两端添加小括弧，这样使得在某种情况下（例如：注释模式下，后边的小括号可能被吃掉）有bug，其他情况还没有考虑。
最后提出一个问题，当没有捕获组1的时候，将默认捕获组改为0，这样可否？有没有违背最开始的设计？
@code4craft 
Pull request 参见 #556

**Comment by code4craft** [comment]
赞正则高手。
这里加小括号的行为是个设计失误，本来考虑是一般爬虫用的匹配都要使用上下文信息，所以默认取第一个捕获组，造成的问题就是使用非常不直观。

**最后提出一个问题，当没有捕获组1的时候，将默认捕获组改为0，这样可否？有没有违背最开始的设计？**

我觉得是个很好的做法。`RegexSelector`有两个构造函数：
```java
public RegexSelector(String regexStr, int group);
public RegexSelector(String regexStr);
```
第一个我会完全按照调用方设置的group来配置，第二个会按照你的做法来改，这样从接口功能上来说跟之前是一致的。

不过我觉得最好的方式还是不要帮使用者做判断，这样的API是不可预知的，下个大版本计划还是改成默认全捕获并且不再添加括号。

**Comment by code4craft** [comment]
新建了 #585 ,此issue关闭了
