### ISSUE TITLE
WebMagic 与spring集成报错

### ISSUE THREAD

**Issue by githubzaibao** [code4craft/webmagic#560]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.alibaba.fastjson.support.spring.FastJsonpResponseBodyAdvice]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/mvc/method/annotation/ResponseBodyAdvice.class] cannot be opened because it does not exist

Caused by: java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/mvc/method/annotation/ResponseBodyAdvice.class] cannot be opened because it does not exist

求解

**Comment by code4craft** [comment]
`Caused by: java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/mvc/method/annotation/ResponseBodyAdvice.class] ` 看起来是fastjson和Spring依赖的问题。
