### ISSUE TITLE
[建议]Page新增byte数组的属性

### ISSUE THREAD

**Issue by lvguangzeng** [code4craft/webmagic#571]
有时候需要下载pdf或者图片等内容，现在我只能通过下载源码修改Page类新增byte数组属性，并将HttpClientDownloader复制重新实现getResponseContent方法

**Comment by code4craft** [comment]
可是这样的对象应该没法解析吧？只是想添加到队列里然后下载吗？

**Comment by lvguangzeng** [comment]
是的，只是想下载一些文件类型的内容

**Comment by code4craft** [comment]
增加了Page.getBytes()获取二进制内容。
另外，建议设置`request.setBinarayContent(true);`，这样对于二进制内容不会尝试转换为String，减小开销。
