### ISSUE TITLE
xpath测试工具

### ISSUE THREAD

**Issue by hhuimie** [code4craft/webmagic#572]
初接触webmagic, 前端也不太懂, 用了几个chrome的xpath测试扩展都和实际运行结果不一样.
我想问问有没有什么独家的工具或者扩展.
谢谢

**Comment by code4craft** [comment]
XPath解析器是我自己实现的：[xsoup](https://github.com/code4craft/xsoup)
有一些语法可能不完全支持，具体可以参考文档。
