### ISSUE TITLE
对于post的请求，参数是直接放在body中的该如何处理呢？

### ISSUE THREAD

**Issue by wuxiongliu1** [code4craft/webmagic#573]
在post请求中，参考了文档中的请求方式，请求参数是以键值对的方式带入的，那如果请求参数是一串json字符串，直接放在body中，这种情况该如何处理呢？

**Comment by perfecking** [comment]
可以把相关URL贴出来，我们抓包一下

**Comment by wuxiongliu1** [comment]
重写了HttpClientDownloader 中的selectRequestMethod方法，加了个StringEntity 的相关方法，就可以处理该类型的post请求了；

**Comment by code4craft** [comment]
最新版0.7.0已经有支持了。
