### ISSUE TITLE
请问：post请求，参数是json格式，如何实现

### ISSUE THREAD

**Issue by yukyh** [code4craft/webmagic#581]
在用webmagic写爬虫的时候，遇到post请求，且参数为json格式，accept为application/json, text/javascript, /; q=0.01。请问，这种请求，如果实现？

**Comment by yukyh** [comment]
在用webmagic写爬虫的时候，遇到post请求，且参数为json格式，accept为application/json, text/javascript, */*; q=0.01。请问，这种请求，如果实现？

**Comment by code4craft** [comment]
可以使用0.7.0的新API:
[http://webmagic.io/docs/zh/posts/ch4-basic-page-processor/post.html](http://webmagic.io/docs/zh/posts/ch4-basic-page-processor/post.html)
