### ISSUE TITLE
默认的调度器QueueScheduler不支持重试

### ISSUE THREAD

**Issue by lomoye** [code4craft/webmagic#582]
因为其继承的DuplicateRemovedScheduler内的HashSetDuplicateRemover会将曾经访问过的链接去重。这将导致Spider设置循环重试次数无效。去重的逻辑影响到了重试的逻辑，好像不是很合理。

**Comment by code4craft** [comment]
请问是实测过的吗？
`DuplicateRemovedScheduler`这里是这样写的：
```java
public void push(Request request, Task task) {
        logger.trace("get a candidate url {}", request.getUrl());
        if (shouldReserved(request) || noNeedToRemoveDuplicate(request) || !duplicatedRemover.isDuplicate(request, task)) {
            logger.debug("push to queue {}", request.getUrl());
            pushWhenNoDuplicate(request, task);
        }
    }

   protected boolean shouldReserved(Request request) {
        return request.getExtra(Request.CYCLE_TRIED_TIMES) != null;
    }
```
如果`request.getExtra(Request.CYCLE_TRIED_TIMES)`中有值，是不会被去重的。

**Comment by lomoye** [comment]
(⊙o⊙)…没看到这个逻辑，刚刚调试了一下是可以重试加入队列的。但是我昨天设置了循环重试10000次，爬豆瓣电影的top250.但是每次都只能爬到160条左右爬虫就结束了，程序也没有抛异常。我设置了代理ip池，连接肯定还是正常的。不知道这是为什么了，我再看一下是哪里出了问题。

**Comment by lomoye** [comment]
找到原因了。在Spider这个类里：
`private void onDownloadSuccess(Request request, Page page) {
        onSuccess(request);
        if (site.getAcceptStatCode().contains(page.getStatusCode())){
            pageProcessor.process(page);
            extractAndAddRequests(page, spawnUrl);
            if (!page.getResultItems().isSkip()) {
                for (Pipeline pipeline : pipelines) {
                    pipeline.process(page.getResultItems(), this);
                }
            }
        }
        sleep(site.getSleepTime());
        return;
    }
`
如果我访问的页面返回的状态码是404，403也是算下载成功的，从而不会加入到重试的队列里。所以每次爬数据会漏掉部分数据。

而实际上403的页面还是有办法拿到数据的，只是暂时被网站封了。

**Comment by lomoye** [comment]
找到原因了。在Spider这个类里：
```
private void onDownloadSuccess(Request request, Page page) {
        onSuccess(request);
        if (site.getAcceptStatCode().contains(page.getStatusCode())){
            pageProcessor.process(page);
            extractAndAddRequests(page, spawnUrl);
            if (!page.getResultItems().isSkip()) {
                for (Pipeline pipeline : pipelines) {
                    pipeline.process(page.getResultItems(), this);
                }
            }
        }
        sleep(site.getSleepTime());
        return;
    }
```
如果我访问的页面返回的状态码是404，403也是算下载成功的，从而不会加入到重试的队列里。所以每次爬数据会漏掉部分数据。

而实际上403的页面还是有办法拿到数据的，只是暂时被网站封了。

**Comment by lomoye** [comment]
找到原因了。在Spider这个类里：

```java
private void onDownloadSuccess(Request request, Page page) {
        onSuccess(request);
        if (site.getAcceptStatCode().contains(page.getStatusCode())){
            pageProcessor.process(page);
            extractAndAddRequests(page, spawnUrl);
            if (!page.getResultItems().isSkip()) {
                for (Pipeline pipeline : pipelines) {
                    pipeline.process(page.getResultItems(), this);
                }
            }
        }
        sleep(site.getSleepTime());
        return;
}
```

如果我访问的页面返回的状态码是404，403也是算下载成功的，从而不会加入到重试的队列里。所以每次爬数据会漏掉部分数据。

而实际上403的页面还是有办法拿到数据的，只是暂时被网站封了。

**Comment by code4craft** [comment]
是的，有明确状态码的错误不会进行retry，因为已经请求成功了。
特别是4xx开头的响应一般都是客户端错误，重试也不会有结果。
