### ISSUE TITLE
注解模式使用@ExtractBy(type=JsonPath)时，默认选择source为RawText

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#589]
因为`@ExtractBy`默认的source是`SelectedHtml`，这种情况下会预先把内容用Jsoup解析一遍，这样会自动加上`<html>`标签。如果使用JsonPath时，会导致解析失败。虽然可以通过手动指定`source`为`RawText`解决，但是一般很容易忘记这么做，而且这样的API也不够友好。

之前有类似的问题 #250 ，所以决定做一个默认选择的处理。新版中会使用`@ExtractByJson`这样的API，可以有更灵活的处理方式。

**Comment by cookier** [comment]
请问新版本发布了吗？我使用`0.7.1`还是有这样的问题。
跟[#462](https://github.com/code4craft/webmagic/issues/462)里的情况一样，报`java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.compile`错误。
你有提到是依赖问题，请问如何解决呢？我更改了`json-path`的版本也没用。

**Comment by cookier** [comment]
检查发现webmagic里使用`json-path`版本是`0.8.1`，而我maven导入后，引用的`json-path`实际版本却是`2.2.0`。手动指定版本为`0.8.1`后就正常了。

**Comment by code4craft** [comment]
是不是其他库依赖了json-path？能否帮忙看下依赖情况？

**Comment by cookier** [comment]
其它库没有依赖。可能是我本地的maven抽风了吧。。。
