### ISSUE TITLE
希望POST请求JSON的时候HttpRequestBody里的关键词可以不用再parse出来

### ISSUE THREAD

**Issue by luchatex** [code4craft/webmagic#597]
{"limit":"10","page":"0",dicval":"asc","reqtoken":"11111",key":"/Item/@级别","condition":"/Item/@级别=*大于200*"}
发送这样的请求后,希望继续分页,目前的做法是parse这个json拿到Page,继续增加页码,
但"大于200"这个参数就不好取出了
发送Json的时候是拼装的,可否在request里增加一个map来方便解析回来的页面提取一些请求关键词.
感谢.

**Comment by code4craft** [comment]
JSON除了Map还有List结构。
不太想在HttpRequestBody里嵌入比较复杂的数据结构，建议直接在Request里附加自己需要的参数。

**Comment by luchatex** [comment]
Request里附加到哪里?我尝试放在cookie或者header里返回的时候拿回,但是请求的时候就出问题了...
因为需要继续分页请求,如何在不解析HttpRequestBody的情况下,获取 "大于200" 这个关键词.

**Comment by code4craft** [comment]
request.putExtra
