### ISSUE TITLE
爬虫需要翻页，怎么处理？

### ISSUE THREAD

**Issue by tobecrazy** [code4craft/webmagic#600]
html 如下：
https://www.lagou.com/jobs/list_%E6%B5%8B%E8%AF%95
如果每一页都需要爬虫，该怎么处理？

**Comment by tobecrazy** [comment]
`<a id="PageNavigator1_LnkBtnNext" href="javascript:__doPostBack('PageNavigator1$LnkBtnNext','')" style="color:Black;">下一页</a>`

**Comment by tobecrazy** [comment]
> <a id="PageNavigator1_LnkBtnNext" href="javascript:__doPostBack('PageNavigator1$LnkBtnNext','')" style="color:Black;">下一页</a>

**Comment by luchatex** [comment]
https://www.lagou.com/jobs/positionAjax.json?needAddtionalResult=false
这个是有接口api的,不要去访问它的页面,要访问他的api来实现翻页和数据获取

请求头:pn2就是页码2,post请求哦~~
first:false
pn:2
kd:测试

**Comment by tobecrazy** [comment]
那请问这个呢？http://www.lhfdc.gov.cn/templets/lh/aspx/hpms/ProjectList.aspx

**Comment by tobecrazy** [comment]
已解决，采用htmlunit 获取每页的内容。
