### ISSUE TITLE
参考指南: 配置代理是否有过更改

### ISSUE THREAD

**Issue by wangli0** [code4craft/webmagic#607]
请问作者http://webmagic.io/中  **配置代理** 一节是否有过更改，之前看过似乎用的是开源中国某个类库且有过瑕疵，现在是弃用那个库了？能否再发下地址

**Comment by code4craft** [comment]
有，0.7.x版本后代理部分重构了，之前的代理文档可以看文档：0.6.1版文档: [http://webmagic.io/archive/docs/0.6.1](http://webmagic.io/archive/docs/0.6.1)
不过0.6.x版本代理比较繁琐也不太稳定，建议用0.7以后的版本。

**Comment by wangli0** [comment]
多谢！
