### ISSUE TITLE
Upgrade to jsoup 1.10.3

### ISSUE THREAD

**Issue by ningpp** [code4craft/webmagic#608]
![image](https://user-images.githubusercontent.com/2511498/27265847-c4e31a32-54cd-11e7-8d85-136de2af6ee3.png)

**Comment by code4craft** [comment]
这段代码当时是为了修复Jsoup中Html实体会被转义的问题，自从升级jsoup到1.8.x之后就失效了。
先删除了，后面看有没有办法实现。
