### ISSUE TITLE
可以实现这样的功能吗？爬列表->解析内容->解析第二页内容，第三页。。。

### ISSUE THREAD

**Issue by lidaoyang** [code4craft/webmagic#612]
首先抓取列表页，然后是内容页，在解析内容页时发现有好几页内容，这个时候可不可以一起解析掉其他几页的内容啊？
如果是把这几页的内容链接添加到抓取的链接列表里的话就很难和当前的这条新闻内容对上了。
有更好的解决办法吗？

**Comment by luchatex** [comment]
webmagic完全可以实现啊. 
在processor的 process方法里
首先解析URL
List<String> urls = page.getHtml().xpath("//*[@id=\"Pages\"]/a").links().regex("(http://www.xxx.com/map\\d.*\\.html)").all();
循环该地址集合
Request request = page.getRequest().setUrl(添加发现的URL);
Map<String,Object> map = new HashMap<>();
这个集合里你可以存任意类型
request.setExtras(map);

-----------------------------
再解析回来的时候可以通过request.getExtras or request.getExtra(String key)来提取这个map
-----------------------------

以上来自黄大对我之前疑问的帮助,经验分享给其他用webmaic的同道吧.

**Comment by lidaoyang** [comment]
是的，我现在用的就是这种方法，我其实就是想知道有没有其他更好的方法了！
