### ISSUE TITLE
如何获取爬取到网页的原始编码？

### ISSUE THREAD

**Issue by zhoumiaonuaa** [code4craft/webmagic#613]
各位，麻烦请教一下如何获取抓取到的网页的原始编码？没发现有现成的接口

**Comment by zhoumiaonuaa** [comment]
呃，没人遇到过这个问题？

**Comment by code4craft** [comment]
没有现成接口，你要拿编码做什么用？

**Comment by zhoumiaonuaa** [comment]
@code4craft 之前使用boilerpipe抽取网页正文发现效果不错，想和webmagic整合起来的。
