### ISSUE TITLE
列表页和内容页的编码不一致，而且内容页的编码是错的，怎么把列表页和内容页编码分开设置

### ISSUE THREAD

**Issue by lidaoyang** [code4craft/webmagic#627]
内容页了的编码是错误的报异常UnsupportedEncodingException: x-cp20936   at java.lang.StringCoding.decode(Unknown Source)
内容页的网站地址http://www.chinaisa.org.cn/gxportal/html/1499900778950.html 怎么设置分开设置Site的Charset？

**Comment by lidaoyang** [comment]
看了你的download 的实现，发现charset是site里获取的，你的site是全局的，如果一个网站有两个编码，就会出现乱码的情况，虽然可以自动识别，但是这个设置还是很有必要，我认为可以放到request里面，因为在添加目标url时可以一起把字符编码设置进去，这样就可以针对每个网站设置不同的字符编码？

`public Page download(Request request, Task task) {
        if (task == null || task.getSite() == null) {
            throw new NullPointerException("task or site can not be null");
        }
        CloseableHttpResponse httpResponse = null;
        CloseableHttpClient httpClient = getHttpClient(task.getSite());
        Proxy proxy = proxyProvider != null ? proxyProvider.getProxy(task) : null;
        HttpClientRequestContext requestContext = httpUriRequestConverter.convert(request, task.getSite(), proxy);
        Page page = Page.fail();
        try {
            httpResponse = httpClient.execute(requestContext.getHttpUriRequest(), requestContext.getHttpClientContext());
            page = handleResponse(request, **task.getSite().getCharset()//这里可以从request里获取**, httpResponse, task);
            onSuccess(request);
            logger.info("downloading page success {}", request.getUrl());
            return page;
        } catch (IOException e) {
            logger.warn("download page {} error", request.getUrl(), e);
            onError(request);
            return page;
        } finally {
            if (httpResponse != null) {
                //ensure the connection is released back to pool
                EntityUtils.consumeQuietly(httpResponse.getEntity());
            }
            if (proxyProvider != null && proxy != null) {
                proxyProvider.returnProxy(proxy, page, task);
            }
        }
    }`

**Comment by buaanie** [comment]
遇到了同样的问题，新浪微博的爬虫

**Comment by lidaoyang** [comment]
没有

**Comment by code4craft** [comment]
这种情况比较少见，目前的办法只能是在PageProcessor里面自己去强转回来，new String(raw.getBytes('gbk'),'utf-8')这样子。

request中指定编码也是一个好办法。
