### ISSUE TITLE
为什么源代码注释都是英文的

### ISSUE THREAD

**Issue by zsw12013** [code4craft/webmagic#632]
国产嘛 ，为什么源代码非要写英文注释，，，，，希望不要有人打我。。。
![image](https://user-images.githubusercontent.com/4253279/28488134-0fe2310e-6ed6-11e7-8093-d2f12cd08170.png)

**Comment by code4craft** [comment]
国产也可以是国际化项目嘛，虽然目前没做到。
代码注释是英文
