### ISSUE TITLE
整合 spring boot schedule 做定时爬虫

### ISSUE THREAD

**Issue by Shaun-Yao** [code4craft/webmagic#634]
整合webmagic  spring boot schedule 做定时爬虫，请问有没有相关的例子？谢谢！

**Comment by orlandotian** [comment]
@Scheduled(cron = "0 0 0/2 * * ?")
    public void sync() {
        logger.info("Start to dowload proxy!");
        if (spider != null && spider.getStatus() == Spider.Status.Running) return;

        spider = Spider.create(proxyProcessor).setExitWhenComplete(true).setDownloader(DownloaderFactory.create()).thread(3);

两种方式，第一种，设置爬虫爬完这轮就退出，每次新建爬虫。
第二种，设置爬虫为sync状态，定期调用scheduler向此爬虫填充url。

设置springboot起一个服务就好了，但是一定要设置一个controller，使这个服务运转起来。
