### ISSUE TITLE
实现PageProcessor接口类里面spring 注入不生效

### ISSUE THREAD

**Issue by Shaun-Yao** [code4craft/webmagic#637]
@Component
public class UserProcessor implements PageProcessor {

	private Site site = Site.me().setRetryTimes(3).setSleepTime(1000);
	
	@Autowired
	private UserService userService;

	
	@Override
	public void process(Page page) {
		Html html = page.getHtml();
        String table = html.css("table.tb").get();
        Document document = Jsoup.parse(table);
        Elements rows = document.select("tr");
		Element row = rows.get(1);
		Elements cols = row.select("td");
		
		String name = cols.get(0).text();
		
		//此处NPE异常，userService为null
		if (!userService.existsByName(name)) {//数据库不存在则添加
		
			
		}
			
	@Override
	public Site getSite() {
		return site;
	}

}

userService为null值，请问如何解决？？？

**Comment by zhuyuesut** [comment]
userService 没注入进来，你使用UserProcessor的时候，UserProcessor是一个Bean么

**Comment by zhuyuesut** [comment]
new UserProcessor() 的话，userService就一定是空的

**Comment by zhuyuesut** [comment]
而且这跟webmagic框架无关

**Comment by code4craft** [comment]
对的，同@zhuyuesut 。

**Comment by Shaun-Yao** [comment]
@zhuyuesut  谢谢，已经解决
