### ISSUE TITLE
数据抓取过程中，targetRequests 里的 url 未抓取完爬虫就已经退出,未发生任何异常

### ISSUE THREAD

**Issue by zgm4z** [code4craft/webmagic#653]
# 问题

 在抓取数据过程中已经明确有很多条 url 但是只抓取到一部分爬虫就已经退出后续部分不抓。

## pom.xml

```xml
        <dependency>
            <groupId>us.codecraft</groupId>
            <artifactId>webmagic-core</artifactId>
            <version>0.7.2</version>
        </dependency>
        <dependency>
            <groupId>us.codecraft</groupId>
            <artifactId>webmagic-extension</artifactId>
            <version>0.7.2</version>
        </dependency>

```

## 场景

假设有 1000 条url 每次我只抓取一条 url 待抓取完之后用我的业务逻辑来决定是否把下一条 url 加入到 page.addTarGetRequests()　中，但是我尚未把所有的url添加进去爬虫就已经自动退出了。

**爬虫启动的代码:**

```java
        String crurrUrl =small.getUrl().replace("$(one)","1");
        prePublishOriginPageUrlPageProcessor.setSmall(small);
        Spider.create( prePublishOriginPageUrlPageProcessor)
                .addUrl(crurrUrl)
                .thread(1)
                .run();

```

**PageProcessor的业务逻辑部分代码:** 

```java
        if (currNumber<=totalPageNumber) { //如果当前页数小于总页数
            String baseUrl = small.getUrl().replace("$(one)",Integer.toString(currNumber));
            List l = new ArrayList();//只存一条
            l.add(baseUrl);//baseUrl 为动态生成用作后续的抓取目标
            if (DateUtil.after(tblDate,pageMinDate) || DateUtil.equals(tblDate,pageMinDate)){
                page.addTargetRequests(l);//时间对比结果为 true 时，每次放一条 url 作为后续的抓取目标
            }else {//否则更新表里的时间
                small.setFinalCatchDate(pageMaxDate);
                tblCatcherSmallBiz.modifyFun(small);
            }
        }

```

​	在这样的场景下就会发生爬虫未抓取完就已经退出，经过测试发现也已经添加 targetRequests 但是爬虫未去抓取，

​	如：当前第 40 条url 经过判断后确定可以继续就执行 page.addTargetRequests( urls ) 到第40条之后应该会去抓第 41 条url的数据，但是此时在第 40 条 url 时爬虫已经停止了。

**Comment by jibaro** [comment]
你好，我也碰到这个问题了，请问你解决了吗？

**Comment by jibaro** [comment]
你好，我也碰到这个问题了，请问你解决了吗？

**Comment by luchatex** [comment]
你好,爬取过程中是否使用了代理?
爬取的超时设置是否足够?
是否服务器相应了错误的代码?
我遇到过类似的情况就是在一个没有反爬的网站通过每次获取下一页来继续爬取,一旦某个线程由于该网站响应失败(超时等因素),会造成下一页无法获取无法添加到任务列表.
建议改进:
根据业务实现自己的Scheduler,可一次添加该页面所有的需要下一次爬取的urls进Scheduler,Scheduler是去重的,无需担心重复添加问题,让爬虫从中poll任务即可.

**Comment by wmjdmin** [comment]
@jibaro 你好，我猜测是下载调度的时候出问题，但应该不是代码上的问题，我没有看过源码，我的猜测：因为前一条线程把第一条 url 拿走后下一条线程马上进来取下一条 url。但是，此时还没有执行 page.addTargetRequests() 操作所以它就认为任务列表爬完了即使后面在增加url也不去执行抓取的了，我改了另一种做法，把所有 url 都 addTargetRequests( allUrls ) 之后在抓取过程中遇到不需要再爬的url就中断爬虫

**Comment by luchatex** [comment]
试试 spider.setExitWhenComplete(false); 抓取结束后不退出,sleep后继续抓取.
配合
spider.setEmptySleepTime(SLEEPTIME);

**Comment by liangAhh** [comment]
我也是这个问题，url需要一条一条的加进去，抓取任务执行一段时间后，就意外停止了。

**Comment by luchatex** [comment]
默认是内存的QueueScheduler,你可以断点看看队列是否为空了.在检查下downloader下,返回的状态码是多少.自己是否定义了状态码

**Comment by liangAhh** [comment]
public class CustomQueueScheduler extends QueueScheduler {
	
	private BlockingQueue<Request> queue = new LinkedBlockingQueue<Request>();

    @Override
    public void pushWhenNoDuplicate(Request request, Task task) {
    	System.out.println("添加待抓取url：" + request.getUrl());
        this.queue.add(request);
    }

    @Override
    public Request poll(Task task) {
    	System.out.println("执行抓取url：" + (queue.peek() == null ? "" : queue.peek().getUrl()));
        return this.queue.poll();
    }
}

发现一次任务过程poll会执行两次，第二次获取的链接就为null了

**Comment by luchatex** [comment]
可以设置 spider.setExitWhenComplete(**false**); queue里无任务时 通过spider的sleepTime
来休息,然后继续爬取.应该是你的起始任务就1个,但是webmagic启动时候会有2个线程,多线程获取时候任务池为空了.

**Comment by liangAhh** [comment]
好的，我试试
