### ISSUE TITLE
请问webmagic可以得到上一级page的相关信息吗

### ISSUE THREAD

**Issue by chenSJ519** [code4craft/webmagic#663]

**Comment by ALEXFUNGZH** [comment]
建议把page.addTargetRequests中的参数List<String>改成List<Map<String,Object>>,比较灵活一些。目前我这边抓取的发布时间只有在列表页才能获取。

**Comment by caoenergy** [comment]
可以使用page.addTargetRequest(Request request) 方法，request#putExtra(String key, Object value)实现
