### ISSUE TITLE
在Downloader中如何禁用Cookies？

### ISSUE THREAD

**Issue by CrowHawk** [code4craft/webmagic#676]
爬取某个论坛时，每次爬到第11页时就显示Cookie Rejected，然后就抓不到网页内容了，推断是网站的反爬虫策略，禁用Cookies应该能解决这个问题，但是Webmagic好像没有提供相关API，Scrapy是可以的

**Comment by chenSJ519** [comment]
request.addCookie("","");或site.setDisableCookieManagement(false);也许可以

**Comment by chenSJ519** [comment]
request.addCookie("","");或site.setDisableCookieManagement(true);也许可以

**Comment by CrowHawk** [comment]
谢谢，发现是我版本的问题，用的0.5.3，没有这个API

**Comment by litong1** [comment]
这个Cookie Rejected最后怎么解决的啊，大哥
