### ISSUE TITLE
Spider中的日志无法输出

### ISSUE THREAD

**Issue by qianwj** [code4craft/webmagic#682]
我配置了log4j的依赖和log4j2.xml, 但是spider.run()执行之后没有任何日志输出
`<dependency>
  		<groupId>log4j</groupId>
  		<artifactId>log4j</artifactId>
  		<version>1.2.12</version>
  	</dependency>
  	<dependency>
  		<groupId>org.apache.logging.log4j</groupId>
  		<artifactId>log4j-api</artifactId>
  		<version>2.6.2</version>
  	</dependency>
        <dependency>
  		<groupId>org.apache.logging.log4j</groupId>
  		<artifactId>log4j-core</artifactId>
  		<version>2.6.2</version>
  	</dependency>
        <dependency>
  		<groupId>org.jsoup</groupId>
  		<artifactId>jsoup</artifactId>
  		<version>1.10.3</version>
  	</dependency>
`

log4j2.xml
`<?xml version="1.0" encoding="UTF-8"?>
<configuration status="DEBUG">
    <appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern=" %-d{HH:mm:ss}[%p %c] %m%n"/>
        </Console>
        <RollingFile name="RollingFile" fileName="log/app.log"
                     filePattern="log/app-%d{yyyy-MM-dd}-%i.log"
                     immediateFlush="false" append="true">
            <PatternLayout>
                <Pattern>%-d{HH:mm:ss}[%p %c] %m%n</Pattern>
            </PatternLayout>
            <Policies>
                <TimeBasedTriggeringPolicy interval="3" modulate="true"/>
                <SizeBasedTriggeringPolicy size="5 MB"/>
            </Policies>
        </RollingFile>
    </appenders>
    <loggers>
        <root level="info">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </root>
        <logger name="org.apache.commons" level="error" additivity="false">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
        <logger name="io.netty" level="error" additivity="false">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
        <logger name="httpclient" level="error" additivity="false">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
        <logger name="org.springframework" level="info" additivity="false">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
        <logger name="org.elasticsearch" level="error" additivity="true">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
        <logger name="org.apache.http" level="error" additivity="true">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
        <logger name="us.codecraft.webmagic" level="error" additivity="true">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
        <logger name="TASK_LOG" level="error" additivity="false">
            <appender-ref ref="Console"/>
            <appender-ref ref="RollingFile"/>
        </logger>
    </loggers>
</configuration>`

**Comment by mysterin** [comment]
默认是用 slf4j+log4j, 把 log4j 依赖去掉, 然后配置 log4j.properties 试试

**Comment by sutra** [comment]
请参考 log4j2 的文档： https://logging.apache.org/log4j/2.x/log4j-slf4j-impl/index.html
