### ISSUE TITLE
1万多条数据的抓取量，抓取了超过30多小时还没抓取完

### ISSUE THREAD

**Issue by provswin** [code4craft/webmagic#699]
感觉有点问题，但是不知道咋描述，大家帮我分析看看：
几个关键现象
1、setRetryTimes  ： 设置了3次
2、setTimeOut  ：  设置了20秒
3、刚开始抓取的时候非常快，能够达到1小时抓取3300条左右的数据。
4、越到后面越慢，而且出现java.net.SocketTimeoutException: Read timed out和对方服务器报status code 502的概率高了很多。【在经过了20小时抓取后，之后的8个小时只抓取到了200条数据左右。】
5、相同网络情况下，直接通过浏览器访问目标网站感觉非常流畅。
6、在挂机抓取的时候，第二天来看日志，发现抓取的过程中偶尔会出现间隔1小时以上没有任何抓取日志输出。

目前总量大概是12000条数据的抓取，抓了30多小时还没有抓取完。
![default](https://user-images.githubusercontent.com/4549726/33319787-db6657b0-d47a-11e7-9085-9cc8bebb6d65.png)

**Comment by zhuyuesut** [comment]
因为浏览器和你的抓取不是一个客户端，所以会有很多处不同，任何一点不同都可能是这种情况的原因之一，并且这种情况的所有原因必然都来自于这些不同之中。这些不同，比如Cookies、Headers、访问积累次数、访问的时间点等等。好多，需要分别做测试。

**Comment by provswin** [comment]
@zhuyuesut 是否有一种简单的方式可以实现我这个抓取需求？大概1万多条数据的抓取。比如使用代理IP的方式，避免出现大量的read time out 和 502类似的错误。

或者按照你提的这些因素，我该怎么取测试验证呢？

**Comment by zhuyuesut** [comment]
比如倒着爬，看爬取的先后是否影响效率；比如换着网怕，看网络是否有影响，比如随机爬取间隔时间，看是不是被抓了行为特性，比如换着UA爬，看是否被记录了访问频率，比如换个时间爬，看是不是某一个时候服务器负载有问题，比如检查代码是不是URL不容易解析，比如查看代码是不是给服务器产生了不该有的临时数据，影响了服务器的垃圾回收机制，类似这样的测试有很多，什么时候能找到问题，看经验，看运气，看灵性。

**Comment by provswin** [comment]
@zhuyuesut 谢谢，收获很多，提供了很多思路。我试试。
