### ISSUE TITLE
[Bug] CountableThreadPool 类中 exec() 中是否存在线程安全问题

### ISSUE THREAD

**Issue by INotWant** [code4craft/webmagic#715]
if (threadAlive.get() >= threadNum) { // 1 感觉此处有线程安全问题
            try {
                reentrantLock.lock();
                while (threadAlive.get() >= threadNum) {
                    try {
                        condition.await();
                    } catch (InterruptedException e) {
                    }
                }
            } finally {
                reentrantLock.unlock();
            }
        }
        threadAlive.incrementAndGet();  // 2
        executorService.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    runnable.run();
                } finally {
                    try {
                        reentrantLock.lock();
                        threadAlive.decrementAndGet();
                        condition.signal();
                    } finally {
                        reentrantLock.unlock();
                    }
                }
            }
        });

比如，有两个线程，执行此任务。先假设 `threadNum = 10`，`threadAlive.get() = 9`。线程1执行注释1处的判断得到 `false`，将会执行注释2的语句。但还没执行，就发生调度了，现线程2执行注释1处了。此时由于线程1没有执行 `threadAlive.incrementAndGet();` 所以依旧判断为 `false` 。但是，这样的逻辑是不该的。

我不知道我这样理解对不对，请大家解答。谢谢~

我的一个修改

        // My modify
        try {
            reentrantLock.lock();
            if (threadAlive.get() >= threadNum)
                while (threadAlive.get() >= threadNum) {
                    try {
                        condition.await();
                    } catch (InterruptedException e) {
                    }
                }
            else
                threadAlive.incrementAndGet();
        } finally {
            reentrantLock.unlock();
        }
        executorService.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    runnable.run();
                } finally {
                    try {
                        reentrantLock.lock();
                        threadAlive.decrementAndGet();
                        condition.signal();
                    } finally {
                        reentrantLock.unlock();
                    }
                }
            }
        });

**Comment by mysterin** [comment]
看了源码, 我个人也感觉这里同步有问题, 提供的修改应该是能解决的. 另外我也有个疑问, 为什么不用 Java 的线程池呢, 而是自己写了一个, 区别在哪里?

**Comment by INotWant** [comment]
应该是为了计算 `thread alive`（活着的线程数），不知道原生的线程池可以计算不？

**Comment by mysterin** [comment]
又仔细看了代码, 发现实际是用 `Executors.newFixedThreadPool(threadNum)` 来获得 `ThreadPoolExecutor` 线程池对象, 这个是可以计算活跃线程数的. 这样的话, 在外面又封装一层 `CountableThreadPool` 感觉意义不大呀

**Comment by luchatex** [comment]
使用RedisScheduler,设置thread(1),它每次会启动2个线程.就是这里的问题

**Comment by INotWant** [comment]
@luchatex 请试试用我修改的代码替换原来的，看看还会出现问题吗？

**Comment by INotWant** [comment]
@mysterin `((ThreadPoolExecutor)executorService).getActiveCount();` 是这样吗？现在我也感觉意义不大~

**Comment by eblank** [comment]
@INotWant 
你的改动还有问题

``` java
	try {
            reentrantLock.lock();
            if (threadAlive.get() >= threadNum)
                while (threadAlive.get() >= threadNum) {
                    try {
                        // 阻塞在这里的线程不会执行threadAlive.incrementAndGet()
                        condition.await();
                    } catch (InterruptedException e) {
                    }
                }
            else
                threadAlive.incrementAndGet();
        } finally {
            reentrantLock.unlock();
        }
        executorService.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    runnable.run();
                } finally {
                    try {
                        reentrantLock.lock();
                        threadAlive.decrementAndGet();
                        condition.signal();
                    } finally {
                        reentrantLock.unlock();
                    }
                }
            }
        });
```

**Comment by eblank** [comment]
@INotWant @mysterin 我觉得CountableThreadPool的目的是限制加入线程池的任务数量.

**Comment by mysterin** [comment]
@eblank 但是 ThreadPoolExecutor 本身就可以设置线程池数量啊, 而且直接设置就不会出现阻塞现象了, 感觉更简单

**Comment by INotWant** [comment]
@eblank 谢谢。确实，我那里有点问题。而且，你这个更简洁了。谢谢~

**Comment by eblank** [comment]
@mysterin 
Thread是线程, Runnable是任务, 我是这么理解的.

ThreadPoolExecutor能限制的是线程数量, 线程数达到上限, 任务还是可以加入任务队列直到队列饱和,  然后执行拒绝策略.

所以任务可能在队列中无限堆积, 或者被拒绝.

下面是ThreadPoolExecutor执行任务的代码, 可以看看

```
public void execute(Runnable command) {
    if (command == null)
        throw new NullPointerException();
    /*
     * Proceed in 3 steps:
     *
     * 1. If fewer than corePoolSize threads are running, try to
     * start a new thread with the given command as its first
     * task.  The call to addWorker atomically checks runState and
     * workerCount, and so prevents false alarms that would add
     * threads when it shouldn't, by returning false.
     *
     * 2. If a task can be successfully queued, then we still need
     * to double-check whether we should have added a thread
     * (because existing ones died since last checking) or that
     * the pool shut down since entry into this method. So we
     * recheck state and if necessary roll back the enqueuing if
     * stopped, or start a new thread if there are none.
     *
     * 3. If we cannot queue task, then we try to add a new
     * thread.  If it fails, we know we are shut down or saturated
     * and so reject the task.
     */
    int c = ctl.get();
    if (workerCountOf(c) < corePoolSize) {
        if (addWorker(command, true))
            return;
        c = ctl.get();
    }
    if (isRunning(c) && workQueue.offer(command)) {
        int recheck = ctl.get();
        if (! isRunning(recheck) && remove(command))
            reject(command);
        else if (workerCountOf(recheck) == 0)
            addWorker(null, false);
    }
    else if (!addWorker(command, false))
        reject(command);
}
```

**Comment by INotWant** [comment]
@eblank 最近看了 *java concurrency in practice* ，赞同你的说法！
