### ISSUE TITLE
OOSpider多线程爬取数据后，保存数据库的数据量为 总数/线程数，怎么破？

### ISSUE THREAD

**Issue by KfcRun** [code4craft/webmagic#723]
//整个页面有20条数据，但是开启多线程后，入库的个数为4条(计算公式=20/5)
 //貌似只有一个线程能成功保存数据到数据库！怎么解决???
        OOSpider.create(site, a, b.class)
                .addUrl("http://xxxx/xxx")
                .thread(5)
                .setDownloader(httpClientDownloader)
                .run();
还有一个问题：当启用IP代理(.setDownloader(httpClientDownloader))后,如果当前的ip访问失败后，怎么自动切换IP地址？

**Comment by code4craft** [comment]
可以看看这个代理池的实现，支持WebMagic接入
[https://github.com/virjar/dungproxy](https://github.com/virjar/dungproxy)
