### ISSUE TITLE
启动一个Spider线程适合采集多个站点吗

### ISSUE THREAD

**Issue by smartning** [code4craft/webmagic#724]
我的需求是： 需要做一个通用采集的平台，之前的做法是每一个任务（包括列表任务和详情任务）都创建一个Spider线程，现在 做了一些改进，只启动一个 Spider线程，但是问题出现很多
1： 在addtargetUrl的时候，会去重，对于列表来说，不应当去重的，导致出来的任务很少
2：对于使用Ajax的请求，和需要执行js脚本的请求，如何在同一个下载器实现

**Comment by code4craft** [comment]
建议是启动多个Spider,Spider之间可以共用线程池。
