### ISSUE TITLE
百度搜索抓取资源，百度有跳转怎么抓取

### ISSUE THREAD

**Issue by jujunchen** [code4craft/webmagic#730]
通过关键词搜索，webmagic得到的页面是这样，后面的其他地址就都抓不到了
`
\<html>
\<head> 
 \<script>
		location.replace(location.href.replace("https://","http://"));
	</script> 
 \</head> 
 \<body> 
  \<noscript>
   \<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
  \</noscript>  
 \</body>
</html>
`

**Comment by Inphoo** [comment]
判断如果需要再跳转的话，提取出目标url，addTargetRequest(url)再跳一次就可以了
