### ISSUE TITLE
请将Commons-lang3的版本升级下

### ISSUE THREAD

**Issue by luchatex** [code4craft/webmagic#733]
虽说不是大问题吧,使用自带的3.1没有UnescapeJson方法.
3.3以上版本支持了.请黄大更新下依赖吧.

<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.7</version>
</dependency>

**Comment by sutra** [comment]
在你自己的项目中的 pom.xml 里重新定义 commons-lang 的版本就行了吧。
