### ISSUE TITLE
Https问题

### ISSUE THREAD

**Issue by DarkObject** [code4craft/webmagic#757]
导入的master项目GithubRepoPageProcessor这个可以跑 但是自建的只添加core和extension的话不能运行,报错javax.net.ssl.SSLException: Received fatal alert: protocol_version

**Comment by ShawnZK** [comment]
我出现了同样的情况。
看了一下debug日志，应该和github从2018/02/01开始弃用TLSV1和TLSV1.1有关系。
可能需要作者升级一下构建httpclient时的相关配置。

**Comment by inacionery** [comment]
:+1:

**Comment by Jerrick** [comment]
可能是Maven源上的包有问题，把webmagic checkout下来，然后mvn install 一下 webmagic-core这个项目就可以了(会自动覆盖已经从maven下载的webmagic-core包)。

**Comment by sutra** [comment]
Should be fixed in fe3d52e2a439d76025c26d258bd7f74472947548
