### ISSUE TITLE
希望修改HttpClientDownloader的日志输出级别

### ISSUE THREAD

**Issue by shinelon** [code4craft/webmagic#759]
希望将HttpClientDownloader    download 方法 logger.info("downloading page success {}", request.getUrl());的日志输出级别修改为debug

**Comment by FlatMan89** [comment]
嗯，同上，我这边也是，加了 Pipeline 每个 downloader 完了都有一条日志，瞬间就霸屏了，看其它日志很不方便，望关注。

**Comment by dengxiny** [comment]
log4j.logger.us.codecraft.webmagic = ERROR 对应类配置输出等级就可以去掉了
