### ISSUE TITLE
如何让每次的请求都切换代理呢？

### ISSUE THREAD

**Issue by wuxiongliu1** [code4craft/webmagic#776]
看了文档，现在的代理是通过HttpClientDownloader设置代理的，而httpCliendDownloader是在spider中设置进去的，那如果我想每次请求都切换掉代理，这个该怎么做到呢？pageProcessor中能够重新设置代理吗？

**Comment by lhc572** [comment]
怎么实现的？

**Comment by forrestlmj** [comment]
同问
