### ISSUE TITLE
0.7.3版本依赖的slf4j-api会有冲突

### ISSUE THREAD

**Issue by RogerGu007** [code4craft/webmagic#782]
webmagic 0.7.3会依赖slf4j-api的1.7.25版本，同时webmagic还依赖了json-path，而json-path依赖的slf4j-api是1.7.6版本，导致工程在tomcat中运行的时候报“java.lang.IncompatibleClassChangeError: Implementing class”，有什么其他办法解决么？还是只能降到0.7.2呢，我降到0.7.2，slf4j-api的jar就不会冲突了

**Comment by sutra** [comment]
试试利用 maven 的 Dependency Exclusions 机制来确保只有一个版本的 slf4j-api.
