### ISSUE TITLE
head中带有window.location该如何跳转？

### ISSUE THREAD

**Issue by jqsl2012** [code4craft/webmagic#803]
如题， 页面的内容为下，难道需要将所有可能的js跳转都取到？webmagic还是有更好的办法呢?
<head> 
  <script>window.location="overview.html"</script>
 </head>

**Comment by zbclove** [comment]
webmagic目前不处理js，建议采用headless浏览器进行访问

**Comment by jqsl2012** [comment]
@zbclove  能说的更详细下么？目前我们是直接解析script的方式

**Comment by zbclove** [comment]
@jqsl2012 我认为直接解析script是一个更优的方案，只不过由于很多反爬虫页面会定期更换页面结构，或者存在一些加密，导致解析script很麻烦。headless浏览器指的是无界面的浏览器，原理是借助浏览器自动化测试技术，直接通过浏览器加载数据，然后获取浏览器引擎渲染出的页面并且解析，优点是在编写过程中和编写静态爬虫很像，并且支持多种用户操作。缺点是在爬取过程中可能会由于网络等原因导致爬取失败（例如网站中某些资源的CDN站点无法访问就会导致失败）。
