### ISSUE TITLE
一个spider能否配置多种解析策略

### ISSUE THREAD

**Issue by sebastien-ma** [code4craft/webmagic#83]
目前我看到一个Spider使用一个PageProcessor来处理页面。我在想这个Spider和解析器是不是可以设为一对多的关系，通过pattern来匹配不同的页面不同的解析策略。比如允许Spider使用多个PageProcessor，或者我现在的做法是为PageProcessor添加多个Handler，这样可以根据Handler里定义的pattern来处理特定的页面。

**Comment by wwsq26** [comment]
请问一下列表分页链接如果是项目的相对路径有什么解决方法吗？

**Comment by wwsq26** [comment]
请问一下列表分页链接如果是项目的相对路径有什么解决方法吗？

**Comment by wwsq26** [comment]
请问一下列表分页链接如果是项目的相对路径有什么解决方法吗？
