### ISSUE TITLE
使用/webmagic-samples/src/main/java/us/codecraft/webmagic/model/samples/GithubRepo.java列子运行报如下错误

### ISSUE THREAD

**Issue by jimiyi** [code4craft/webmagic#838]
download page https://github.com/explore error javax.net.ssl.SSLException: Received fatal alert: protocol_version

**Comment by mstao** [comment]
参考：#788

**Comment by sutra** [comment]
Should be fixed in fe3d52e2a439d76025c26d258bd7f74472947548
