### ISSUE TITLE
运行例子webmagic-samples/src/main/java/us/codecraft/webmagic/model/samples/GithubRepo.java报错

### ISSUE THREAD

**Issue by jimiyi** [code4craft/webmagic#839]
91 2018-10-22;10 12:15.428 Logback-demo [pool-3-thread-1] WARN  [us.codecraft.webmagic.downloader.HttpClientDownloader] [us.codecra] - download page https://github.com/explore error javax.net.ssl.SSLException: Received fatal alert: protocol_version
报这样的错误，这是怎么回事？

**Comment by mstao** [comment]
参考： #788

**Comment by sutra** [comment]
Should be fixed in fe3d52e2a439d76025c26d258bd7f74472947548
