### ISSUE TITLE
javax.net.ssl.SSLException: Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by manyhelp** [code4craft/webmagic#866]
javax.net.ssl.SSLException: Received fatal alert: protocol_version

**Comment by firefishREAL** [comment]
参考：http://www.cnblogs.com/vcmq/p/9484418.html

**Comment by manyhelp** [comment]
为什么不更新版本来解决这个问题呢？ 这个项目不维护了吗

**Comment by 495640129** [comment]
@manyhelp +1

**Comment by huleski** [comment]
其实源代码已经修复了, 但是maven库里的webmagic包源没更新
你需要下载源码master, 然后install webmagic-core模块就好了

**Comment by fwk1010** [comment]
修复了为什么不发布版本呢？。。。
