### ISSUE TITLE
关于网页downloadsuccess时，code为400的问题

### ISSUE THREAD

**Issue by huangjianfeng1** [code4craft/webmagic#870]
采集项目时，偶尔会出现400，因为是概率问题，并不会每次都出现，所以添加了对400的处理：
            Set<Integer> acceptStatCodeSet = new HashSet();
            acceptStatCodeSet.add(200);
            acceptStatCodeSet.add(400);
            getSite().setAcceptStatCode(acceptStatCodeSet);
并在process中对400进行判断，并做如下测试：
        if(page.getStatusCode()==400){
            Request request = page.getRequest();
            page.addTargetRequest(request);
            return;
        }
但发现这条采集并不会重新触发，请问各路大仙们，有何解决办法？

**Comment by sutra** [comment]
我觉得应该override Downloader，将 HTTP 400 多做 page download failed 来处理。
