### ISSUE TITLE
关于 RedisScheduler 中 redis 回收连接方法过期，造成程序异常的问题

### ISSUE THREAD

**Issue by lvpiao** [code4craft/webmagic#872]
在**新版**的jedis中 `pool.returnResource(jedis);`已经被废弃！ 所以不能直接使用RedisScheduler ，否则程序将出现异常，但是却程序却不会报任何异常！解决办法就是：重写自己的RedisScheduler 。其实就是复制原来RedisScheduler 中的代码，把 所有 `pool.returnResource(jedis);`改成`jedis.close();` 就好了;

**Comment by sutra** [comment]
Resolved #979
