### ISSUE TITLE
maven 依赖无法引入0.7.3版本

### ISSUE THREAD

**Issue by nalone** [code4craft/webmagic#874]
![U0XE06ETU19(KDAZT2A% NN](https://user-images.githubusercontent.com/1676764/57668302-7f273480-7639-11e9-8de1-e25977a29d3d.png)

**Comment by dpfbeyond** [comment]
我用的 gradle，没有什么问题

**Comment by ChinLong** [comment]
可能是网络问题，可以使用阿里云的maven镜像。
[http://maven.aliyun.com/nexus/content/groups/public/](http://maven.aliyun.com/nexus/content/groups/public/)

**Comment by sutra** [comment]
应该是没有问题的： https://search.maven.org/artifact/us.codecraft/webmagic-core/0.7.3/jar

如果还有问题，提供一下错误提示。
