### ISSUE TITLE
samples项目里 没一个能用的爬虫

### ISSUE THREAD

**Issue by kuaile1993** [code4craft/webmagic#898]
samples项目里 没一个能用的爬虫  没有能爬成功的
![image](https://user-images.githubusercontent.com/52553619/66709275-4085d980-ed93-11e9-9873-5840d78ae1ad.png)

**Comment by Mr-Pluto** [comment]
你是来搞笑的吗?
爬虫项目都存在时效性,这已经是几年前的写的例子了,别人的网页更新等等,不能用很正常

**Comment by z1y1m1** [comment]
你应该去用火车头，八爪鱼
