### ISSUE TITLE
关于一个重定向的问题  我访问网站A会自动重定向到网址B一个验证页面，我需要获取网站B的url也可以说是需要网站A的响应体里面的location 这个怎么获取哎 我看封装回来的page对象里面完全没有这个，回来的page对象是页面B的内容，url确实网站A。。 

### ISSUE THREAD

**Issue by JunLock** [code4craft/webmagic#902]

**Comment by Belmode** [comment]
我试了一下，好像Downloader层处理了301和302响应，得到的结果其实是2次跳转后的结果。也就是url没变，但是返回的内容变了。这种问题，你只能自己设置Downloader的处理行为了。

**Comment by wlxxyw** [comment]
> _No description provided._

重定向 是在服务器完成的，
页面跳转 是在浏览器完成的，你可以自定义downloader的处理
