### ISSUE TITLE
怎么获取list<Selectable>

### ISSUE THREAD

**Issue by kuaile1993** [code4craft/webmagic#915]
![image](https://user-images.githubusercontent.com/52553619/75875791-5766be80-5e4f-11ea-9860-7fd9c6b603aa.png)
一个页面有很多li元素， 但是 用这个方法只能返回第一个li 元素， 怎么获取所有得 li 元素并将他们封装成List<Selectable>  .

**Comment by kuaile1993** [comment]
您好，您的框架封装得非常好，但是与scrapy 有点差别就是
1. 他返回得是 List<Selectable>   可以对子元素做更多得处理， 你的只有调用all方法后返回List<String> 感觉有点局限，是否能增加返回List<Selectable>得方法
2.有一个问题，爬虫能否爬小说类得有3级得网站，注解得形式在文档中只看到了TargetUrl和helpurl ，3级网站怎么支持呢

**Comment by kuaile1993** [comment]
抱歉，刚看到了nodes()方法

**Comment by ruby-ya** [comment]
.all()
