### ISSUE TITLE
Site.java 中 sleepTime 注释的单位是 micro second（微秒），但实际上应该是毫秒

### ISSUE THREAD

**Issue by super9du** [code4craft/webmagic#918]
Site.java 中 sleepTime 注释的单位是 micro second（微秒），但实际上应该是毫秒（millisecond）。
github上下载的源码如下：
```java
    /**
     * Set the interval between the processing of two pages.<br>
     * Time unit is micro seconds.<br>
     *
     * @param sleepTime sleepTime
     * @return this
     */
    public Site setSleepTime(int sleepTime) {
        this.sleepTime = sleepTime;
        return this;
    }

    /**
     * Get the interval between the processing of two pages.<br>
     * Time unit is micro seconds.<br>
     *
     * @return the interval between the processing of two pages,
     */
    public int getSleepTime() {
        return sleepTime;
    }
```
但实际上应该是毫秒（millisecond），[官方文档4.1](http://webmagic.io/docs/zh/posts/ch4-basic-page-processor/pageprocessor.html)位置写明了：

> 4.1.1 爬虫的配置
> 第一部分关于爬虫的配置，包括编码、抓取间隔、超时时间、重试次数等，也包括一些模拟的参数，例如User Agent、cookie，以及代理的设置，我们会在第5章-“爬虫的配置”里进行介绍。在这里我们先简单设置一下：重试次数为3次，抓取间隔为一秒。

注意，这里官方文档提到，爬取间隔为一秒，但官方此段文本上方的代码里使用的是`setSleepTime(1000)`，所以sleepTime的时间单位应该是毫秒。

在源码中我追溯到，sleepTime 实际上是设置的 `Thread.sleep(millis)` 中的 `millis`：
```java
private void onDownloadSuccess(Request request, Page page) {
        // omit...  （此处代码省略。。）
        sleep(site.getSleepTime());
        return;
    }

    protected void sleep(int time) {
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
            logger.error("Thread interrupted when sleep",e);
        }
    }
```

### **所以时间单位是millisecond无疑！**

**Comment by super9du** [comment]
1秒=1000毫秒，1毫秒=1000微秒；1s=1000ms=1,000,000μs。

**Comment by ruby-ya** [comment]
你看的还挺仔细的，确实注释写错了。不过，这种东西不是bug，根本就无关紧要，自己知道就行了，用起来不会出错的
