### ISSUE TITLE
爬取https协议的网站时，SSL报错，java.lang.IllegalArgumentException TSLv1.3

### ISSUE THREAD

**Issue by luoyeNOT** [code4craft/webmagic#927]
使用的是jdk1.8.0_131
直接在github下载的最新包，在爬取https协议的网站时，报java.lang.IllegalArgumentException TSLv1.3
后来发现大概一个月前有过一次更新，添加了对TSLv1.3的支持，可能是这个造成了不兼容，删除HttpClientGenerator中的TSLv1.3后恢复正常

**Comment by 1241492631** [comment]
卧槽 搞了我一下午 谢谢谢谢谢谢

**Comment by sutra** [comment]
你们都还没有升级到 Java 11 吗？
