### ISSUE TITLE
http://webmagic.io/docs/中的图片均无法显示

### ISSUE THREAD

**Issue by kzdw** [code4craft/webmagic#932]
文档说明网站中的所有图片均无法显示。这个问题非常影响阅读，还请作者尽快解决这个问题。

**Comment by sutra** [comment]
比如这个图片： http://webmagic.io/images/logo.jpeg 不能访问？

**Comment by sutra** [comment]
> 比如这个图片： http://webmagic.io/images/logo.jpeg 不能访问？

我知道了，应该是和 #931 是同一个问题。
