### ISSUE TITLE
为什么us.codecraft.webmagic.proxy.Proxy类中不标明代理的http还是https？

### ISSUE THREAD

**Issue by jasonlee529** [code4craft/webmagic#934]
Proxy类内预留了4个属性，host,port,username,password 。没有标记出是http还是https，如果要爬取https的网站，代理也是https的，默认都用http://host:port 去代理，不会有问题吗？

**Comment by Plume3362** [comment]
顶，另外问一下webmagic怎么使用socks代理

**Comment by Plume3362** [comment]
@code4craft

**Comment by sutra** [comment]
> 顶，另外问一下webmagic怎么使用socks代理

我看了下代码，暂时不支持，如果不想直接修改 webmagic 代码，可以通过自己实现 us.codecraft.webmagic.downloader.Downloader 来实现。

**Comment by sutra** [comment]
> > 顶，另外问一下webmagic怎么使用socks代理
> 
> 我看了下代码，暂时不支持，如果不想直接修改 webmagic 代码，可以通过自己实现 us.codecraft.webmagic.downloader.Downloader 来实现。

要想支持 socks，还需要做额外的工作： https://stackoverflow.com/questions/22937983/how-to-use-socks-5-proxy-with-apache-http-client-4

**Comment by sutra** [comment]
刚增加了 Proxy#scheme，缺省可以接受 http 和 https： 791323a5b0730f483a5a488dff149995f6722c75
