### ISSUE TITLE
失败重试

### ISSUE THREAD

**Issue by jason2015lxj** [code4craft/webmagic#938]
hello，现在的失败重试是在抛异常的时候才会执行重试，但是没有对于那些特殊的返回码重试的，只是打印了一下日志： if (site.getAcceptStatCode().contains(page.getStatusCode())){
            pageProcessor.process(page);
            extractAndAddRequests(page, spawnUrl);
            if (!page.getResultItems().isSkip()) {
                for (Pipeline pipeline : pipelines) {
                    pipeline.process(page.getResultItems(), this);
                }
            }
        } else {
            logger.info("page status code error, page {} , code: {}", request.getUrl(), page.getStatusCode());
        }
可不可加一个失败重试的code设置，在else里面判断如果是设置的失败重试的code返回码，就执行欧尼downloadfail方法啊

**Comment by sutra** [comment]
你可以实现自己的 Downloader，来将那些特殊的返回码处理成下载失败。
