### ISSUE TITLE
xpath 规则 没问题 为什么 找不到元素呢？

### ISSUE THREAD

**Issue by Code4Bug** [code4craft/webmagic#966]
抽取目标是百度贴吧详情页的评论时间
https://tieba.baidu.com/p/7087559145

xpath 抽取规则
`//div[@class='core_reply j_lzl_wrapper']/div[@class='core_reply_tail ']/ul[@class='p_tail']/li[2]/span/text()`

![图片](https://user-images.githubusercontent.com/18244566/100072836-b6ee7980-2e77-11eb-9bf0-96069b957f0b.png)

一直取不到  时间

**Comment by mygithub870705** [comment]
firefox xpath 工具执行这个规则 是可以验证并且成功获得和内容的
![图片](https://user-images.githubusercontent.com/18244566/100073852-f9fd1c80-2e78-11eb-8c72-d52be2d32b72.png)

**Comment by mygithub870705** [comment]
原来这个页面 不是 完全一次性 get 加载完的，评论时间是 通过页面js 二次加载的
