### ISSUE TITLE
爬虫状态的监控

### ISSUE THREAD

**Issue by code4craft** [code4craft/webmagic#98]
希望对某个任务下的已抓取、待抓取、失败数等状态进行监控。

**Comment by SailNow** [comment]
现在已经有了记录下各个spider运行状态的类了，可以有地方获取到吗，有获取的办法实际监控的逻辑让大家来自己写应该会很灵活了吧。我用java时间不长，对jmx不是很熟悉，阅读了源码，没找到能获取SpiderStatusMBean 的方法，您给的demo页面也失效了，很像自己实现监控

**Comment by code4craft** [comment]
你可以使用通过`SpiderListener`来实现的状态的记录。直接拿SpiderStatusMBean估计是拿不到的。

**Comment by woshihoujinxin** [comment]
群主方便的话能否出个例子，jmx并没有使用过，而且能不能支持 根据自己业务自定义返回爬取状态的这么个功能，比如我们做的爬虫，需要登录在登陆后可以返回登录成功，抓取成功后，可以返回抓取成功

**Comment by yuweiming2016** [comment]
同求如何使用jmx例子
