### ISSUE TITLE
xpath不支持preceding-sibling::text()

### ISSUE THREAD

**Issue by yuweiming2016** [code4craft/webmagic#984]
我在chrome调试通过了，但是放到代码里就不行，提示解析错误。是不是有点太老了
//body//p[2]/br[2]/preceding-sibling::text()

![image](https://user-images.githubusercontent.com/22490427/104686753-cfbd3200-5738-11eb-9d9b-afa4e970cc6f.png)

**Comment by yuweiming2016** [comment]
![image](https://user-images.githubusercontent.com/22490427/104687780-cdf46e00-573a-11eb-8a86-e29bc3f8df46.png)

我想提取这段文字，请问有谁知道xpath怎么写，本来我在chrome都调好了，可惜webmagic的xpath不支持preceding-sibling::text()

还有，请问一下，现在最新的qq群号是多少？我看主群人都满了，进不去

**Comment by sutra** [comment]
试试：
```
		us.codecraft.webmagic.selector.Xpath2Selector xpaht2Selector = new Xpath2Selector("//body//p[2]/br[2]/preceding-sibling::text()");
		var title = xpaht2Selector.select(text);
		System.out.println(title);
```

**Comment by yuweiming2016** [comment]
老大，没找到Xpath2Selector

**Comment by yuweiming2016** [comment]
引入：webmagic-saxon-0.7.4.jar
