### ISSUE TITLE
监控这块有什么好方案？直接可以拿到队列数量、已爬url数量错误数量，成功数量等等

### ISSUE THREAD

**Issue by yuweiming2016** [code4craft/webmagic#985]
监控这块有什么好方案？直接可以拿到队列数量、已爬url数量错误数量，成功数量等等，真的不想用那个jconsole客户端，我想在页面上展示相关数据，谢谢了

**Comment by yuweiming2016** [comment]
已扩展SpiderStatus实现了

**Comment by patience00** [comment]
> 已扩展SpiderStatus实现了

如何实现的,可以分享下代码吗
