### ISSUE TITLE
第一次使用，看到依赖排除，如下，是否有误？

### ISSUE THREAD

**Issue by wyc194** [code4craft/webmagic#987]
http://webmagic.io/docs/zh/posts/ch2-install/with-maven.html
2.1，应该在webmagic-core下排除吧？我使用的是gradle
`<dependency>
    <groupId>us.codecraft</groupId>
    <artifactId>webmagic-extension</artifactId>
    <version>0.7.3</version>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
    </exclusions>
</dependency>`

**Comment by sutra** [comment]
你可以通过 mvn dependency:tree 来分析，到底应该从哪里排除。

**Comment by wyc194** [comment]
贴出的是原文。是有误的，只是看到了提一下。提出时已使用gradle分析查看过。

**Comment by wyc194** [comment]
> 你可以通过 mvn dependency:tree 来分析，到底应该从哪里排除。

贴出的是原文。是有误的，只是看到了提一下。提出时已使用gradle分析查看过。
