### ISSUE TITLE
设置隧道代理后，没有每次请求都换一个IP，必须重启爬虫后才可以

### ISSUE THREAD

**Issue by tanchichong** [code4craft/webmagic#999]
我这边使用的是快代理的隧道代理服务，每次请求它都会用一个IP。
我这边设置代理后，发现不是每次请求它那边都会换IP，大概每分钟换一个，只有我将爬虫停止后，再重新启动爬虫，就会换IP。
框架本身有对代理做什么处理吗
HttpClientDownloader httpClientDownloader = new HttpClientDownloader();
httpClientDownloader.setProxyProvider(SimpleProxyProvider.from(new Proxy("tps114.kdpi.com",818)));
commonSpider.setDownloader(httpClientDownloader);

**Comment by sutra** [comment]
tps114.kdpi.com 這個更換 IP 地址是通過 DNS TTL 吧？

**Comment by tanchichong** [comment]
> tps114.kdpi.com 這個更換 IP 地址是通過 DNS TTL 吧？

刚看了下源码，好像是这里影响了 incrForLoop()方法

package us.codecraft.webmagic.proxy;

import us.codecraft.webmagic.Page;
import us.codecraft.webmagic.Task;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * A simple ProxyProvider. Provide proxy as round-robin without heartbeat and error check. It can be used when all proxies are stable.
 * @author code4crafter@gmail.com
 *         Date: 17/4/16
 *         Time: 10:18
 * @since 0.7.0
 */
public class SimpleProxyProvider implements ProxyProvider {

    private final List<Proxy> proxies;

    private final AtomicInteger pointer;

    public SimpleProxyProvider(List<Proxy> proxies) {
        this(proxies, new AtomicInteger(-1));
    }

    private SimpleProxyProvider(List<Proxy> proxies, AtomicInteger pointer) {
        this.proxies = proxies;
        this.pointer = pointer;
    }

    public static SimpleProxyProvider from(Proxy... proxies) {
        List<Proxy> proxiesTemp = new ArrayList<Proxy>(proxies.length);
        for (Proxy proxy : proxies) {
            proxiesTemp.add(proxy);
        }
        return new SimpleProxyProvider(Collections.unmodifiableList(proxiesTemp));
    }

    @Override
    public void returnProxy(Proxy proxy, Page page, Task task) {
        //Donothing
    }

    @Override
    public Proxy getProxy(Task task) {
        return proxies.get(incrForLoop());
    }

    private int incrForLoop() {
        int p = pointer.incrementAndGet();
        int size = proxies.size();
        if (p < size) {
            return p;
        }
        while (!pointer.compareAndSet(p, p % size)) {
            p = pointer.get();
        }
        return p % size;
    }

}

**Comment by tanchichong** [comment]
> tps114.kdpi.com 這個更換 IP 地址是通過 DNS TTL 吧？

按照快代理提供的配置隧道代理例子，改了下HttpClientDownloader ，可以用了，目前还不确定具体是什么问题，可能根这行代码有关 
修改前：httpClient.execute(requestContext.getHttpUriRequest(), requestContext.getHttpClientContext());
修改后：httpClient.execute(target, httpRequest);
修改后代码如下：
import cn.hutool.core.util.StrUtil;
import org.apache.commons.io.IOUtils;
import org.apache.http.HttpHost;
import org.apache.http.HttpResponse;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpRequestBase;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import us.codecraft.webmagic.Page;
import us.codecraft.webmagic.Request;
import us.codecraft.webmagic.Site;
import us.codecraft.webmagic.Task;
import us.codecraft.webmagic.downloader.AbstractDownloader;
import us.codecraft.webmagic.downloader.HttpClientGenerator;
import us.codecraft.webmagic.downloader.HttpClientRequestContext;
import us.codecraft.webmagic.downloader.HttpUriRequestConverter;
import us.codecraft.webmagic.proxy.Proxy;
import us.codecraft.webmagic.proxy.ProxyProvider;
import us.codecraft.webmagic.selector.PlainText;
import us.codecraft.webmagic.utils.CharsetUtils;
import us.codecraft.webmagic.utils.HttpClientUtils;

import java.io.IOException;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.Map;

/**
 * 修复webmagic中httpclient中proxy使用隧道代理无效的问题
 *
 * @author 周天星
 * @date 2021/02/24
 */
public class HttpClientProxyFixedDownloader extends AbstractDownloader {

    private Logger logger = LoggerFactory.getLogger(getClass());

    private final Map<String, CloseableHttpClient> httpClients = new HashMap<String, CloseableHttpClient>();

    private HttpClientGenerator httpClientGenerator = new HttpClientGenerator();

    private HttpUriRequestConverter httpUriRequestConverter = new HttpUriRequestConverter();
    
    private ProxyProvider proxyProvider;

    private boolean responseHeader = true;

    public HttpClientProxyFixedDownloader() {
        // JDK 8u111版本后，目标页面为HTTPS协议，启用proxy用户密码鉴权
        System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");
    }

    public void setHttpUriRequestConverter(HttpUriRequestConverter httpUriRequestConverter) {
        this.httpUriRequestConverter = httpUriRequestConverter;
    }

    public void setProxyProvider(ProxyProvider proxyProvider) {
        this.proxyProvider = proxyProvider;
    }

    private CloseableHttpClient getHttpClient(Site site, Proxy proxy) {
        if (site == null) {
            return httpClientGenerator.getClient(null);
        }
        String domain = site.getDomain();
        CredentialsProvider credsProvider = new BasicCredentialsProvider();
        credsProvider.setCredentials(new AuthScope(proxy.getHost(), proxy.getPort()),
                new UsernamePasswordCredentials(proxy.getUsername(), proxy.getPassword()));
        CloseableHttpClient httpClient = HttpClients.custom().setDefaultCredentialsProvider(credsProvider).build();
        if (httpClient == null) {
            synchronized (this) {
                httpClient = HttpClients.custom().setDefaultCredentialsProvider(credsProvider).build();
                if (httpClient == null) {
                    httpClient = HttpClients.custom().setDefaultCredentialsProvider(credsProvider).build();
                    httpClients.put(domain, httpClient);
                }
            }
        }
        return httpClient;
    }

    @Override
    public Page download(Request request, Task task) {
        if (task == null || task.getSite() == null) {
            throw new NullPointerException("task or site can not be null");
        }
        CloseableHttpResponse httpResponse = null;
        Proxy proxy = proxyProvider != null ? proxyProvider.getProxy(task) : null;
        CloseableHttpClient httpClient = getHttpClient(task.getSite(), proxy);
        HttpClientRequestContext requestContext = httpUriRequestConverter.convert(request, task.getSite(), null);
        Page page = Page.fail();
        try {
            HttpRequestBase httpRequest;
            String targetUrl = request.getUrl();
            String method = request.getMethod();
            if (StrUtil.isEmpty(method)) {
                httpRequest = new HttpGet(targetUrl);
            } else {
                method = method.toLowerCase();
                switch (method) {
                    case "get": httpRequest = new HttpGet(targetUrl);break;
                    case "post": httpRequest = new HttpPost(targetUrl);break;
                    default: httpRequest = new HttpGet(targetUrl);break;
                }
            }

            //proxy
            HttpHost proxyHost = new HttpHost(proxy.getHost(), proxy.getPort());
            RequestConfig config = RequestConfig.custom().setProxy(proxyHost).build();

            httpRequest.setConfig(config);
            //headers
            if (task.getSite().getHeaders() != null) {
                for (Map.Entry<String, String> headerEntry : task.getSite().getHeaders().entrySet()) {
                    httpRequest.addHeader(headerEntry.getKey(), headerEntry.getValue());
                }
            }
            if (request.getHeaders() != null) {
                for (Map.Entry<String, String> header : request.getHeaders().entrySet()) {
                    httpRequest.addHeader(header.getKey(), header.getValue());
                }
            }
            //cookies
            if (request.getCookies() != null) {
                StringBuffer cookies = new StringBuffer();
                for (Map.Entry<String, String> cookie : request.getCookies().entrySet()) {
                    cookies.append(cookie.getKey() + "=" + cookie.getValue()).append(";");
                }
                httpRequest.addHeader("Cookie", cookies.toString());
            }

            URL url = new URL(request.getUrl());
            HttpHost target = new HttpHost(url.getHost(), url.getDefaultPort(), url.getProtocol());
            httpResponse = httpClient.execute(target, httpRequest);

            page = handleResponse(request, request.getCharset() != null ? request.getCharset() : task.getSite().getCharset(), httpResponse, task);
            onSuccess(request);
            logger.info("downloading page success {}", request.getUrl());
            return page;
        } catch (IOException e) {
            logger.warn("download page {} error", request.getUrl(), e);
            onError(request);
            return page;
        } finally {
            if (httpResponse != null) {
                //ensure the connection is released back to pool
                EntityUtils.consumeQuietly(httpResponse.getEntity());
            }
            if (proxyProvider != null && proxy != null) {
                proxyProvider.returnProxy(proxy, page, task);
            }
        }
    }

    @Override
    public void setThread(int thread) {
        httpClientGenerator.setPoolSize(thread);
    }

    protected Page handleResponse(Request request, String charset, HttpResponse httpResponse, Task task) throws IOException {
        byte[] bytes = IOUtils.toByteArray(httpResponse.getEntity().getContent());
        String contentType = httpResponse.getEntity().getContentType() == null ? "" : httpResponse.getEntity().getContentType().getValue();
        Page page = new Page();
        page.setBytes(bytes);
        if (!request.isBinaryContent()){
            if (charset == null) {
                charset = getHtmlCharset(contentType, bytes);
            }
            page.setCharset(charset);
            page.setRawText(new String(bytes, charset));
        }
        page.setUrl(new PlainText(request.getUrl()));
        page.setRequest(request);
        page.setStatusCode(httpResponse.getStatusLine().getStatusCode());
        page.setDownloadSuccess(true);
        if (responseHeader) {
            page.setHeaders(HttpClientUtils.convertHeaders(httpResponse.getAllHeaders()));
        }
        return page;
    }

    private String getHtmlCharset(String contentType, byte[] contentBytes) throws IOException {
        String charset = CharsetUtils.detectCharset(contentType, contentBytes);
        if (charset == null) {
            charset = Charset.defaultCharset().name();
            logger.warn("Charset autodetect failed, use {} as charset. Please specify charset in Site.setCharset()", Charset.defaultCharset());
        }
        return charset;
    }
}
